// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "booking_catalog_service_query.proto" (package "BookingCatalogService", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { BookingCatalogServiceQuery } from "./booking_catalog_service_query";
import type { AdminGetAllBookingCatalogServicesRequest } from "./booking_catalog_service_query";
import type { GetDetailBookingCatalogServiceRequest } from "./booking_catalog_service_query";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { GetAllBookingCatalogServicesRequest } from "./booking_catalog_service_query";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service BookingCatalogService.BookingCatalogServiceQuery
 */
export interface IBookingCatalogServiceQueryClient {
    /**
     * @generated from protobuf rpc: GetAllBookingCatalogServices
     */
    getAllBookingCatalogServices(input: GetAllBookingCatalogServicesRequest, options?: RpcOptions): UnaryCall<GetAllBookingCatalogServicesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: GetDetailBookingCatalogService
     */
    getDetailBookingCatalogService(input: GetDetailBookingCatalogServiceRequest, options?: RpcOptions): UnaryCall<GetDetailBookingCatalogServiceRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminGetAllBookingCatalogServices
     */
    adminGetAllBookingCatalogServices(input: AdminGetAllBookingCatalogServicesRequest, options?: RpcOptions): UnaryCall<AdminGetAllBookingCatalogServicesRequest, CommonResult>;
}
/**
 * @generated from protobuf service BookingCatalogService.BookingCatalogServiceQuery
 */
export class BookingCatalogServiceQueryClient implements IBookingCatalogServiceQueryClient, ServiceInfo {
    typeName = BookingCatalogServiceQuery.typeName;
    methods = BookingCatalogServiceQuery.methods;
    options = BookingCatalogServiceQuery.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetAllBookingCatalogServices
     */
    getAllBookingCatalogServices(input: GetAllBookingCatalogServicesRequest, options?: RpcOptions): UnaryCall<GetAllBookingCatalogServicesRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllBookingCatalogServicesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDetailBookingCatalogService
     */
    getDetailBookingCatalogService(input: GetDetailBookingCatalogServiceRequest, options?: RpcOptions): UnaryCall<GetDetailBookingCatalogServiceRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDetailBookingCatalogServiceRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminGetAllBookingCatalogServices
     */
    adminGetAllBookingCatalogServices(input: AdminGetAllBookingCatalogServicesRequest, options?: RpcOptions): UnaryCall<AdminGetAllBookingCatalogServicesRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<AdminGetAllBookingCatalogServicesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
