// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "config_lang_command.proto" (package "ConfigLang", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ConfigLangCommand } from "./config_lang_command";
import type { DeleteConfigLangRequest } from "./config_lang_command";
import type { UpdateConfigLangRequest } from "./config_lang_command";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { CreateConfigLangRequest } from "./config_lang_command";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service ConfigLang.ConfigLangCommand
 */
export interface IConfigLangCommandClient {
    /**
     * @generated from protobuf rpc: CreateConfigLang
     */
    createConfigLang(input: CreateConfigLangRequest, options?: RpcOptions): UnaryCall<CreateConfigLangRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: UpdateConfigLang
     */
    updateConfigLang(input: UpdateConfigLangRequest, options?: RpcOptions): UnaryCall<UpdateConfigLangRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: DeleteConfigLang
     */
    deleteConfigLang(input: DeleteConfigLangRequest, options?: RpcOptions): UnaryCall<DeleteConfigLangRequest, CommonResult>;
}
/**
 * @generated from protobuf service ConfigLang.ConfigLangCommand
 */
export class ConfigLangCommandClient implements IConfigLangCommandClient, ServiceInfo {
    typeName = ConfigLangCommand.typeName;
    methods = ConfigLangCommand.methods;
    options = ConfigLangCommand.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateConfigLang
     */
    createConfigLang(input: CreateConfigLangRequest, options?: RpcOptions): UnaryCall<CreateConfigLangRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateConfigLangRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateConfigLang
     */
    updateConfigLang(input: UpdateConfigLangRequest, options?: RpcOptions): UnaryCall<UpdateConfigLangRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateConfigLangRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteConfigLang
     */
    deleteConfigLang(input: DeleteConfigLangRequest, options?: RpcOptions): UnaryCall<DeleteConfigLangRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteConfigLangRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
