// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "config_icon_command.proto" (package "ConfigIcon", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { StringValue } from "../../Utils/google/protobuf/wrappers";
/**
 * @generated from protobuf message ConfigIcon.CreateConfigIconRequest
 */
export interface CreateConfigIconRequest {
    /**
     * @generated from protobuf field: google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue Description = 2
     */
    description?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue Url = 3
     */
    url?: StringValue;
}
/**
 * @generated from protobuf message ConfigIcon.UpdateConfigIconRequest
 */
export interface UpdateConfigIconRequest {
    /**
     * @generated from protobuf field: google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue Description = 2
     */
    description?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue Url = 3
     */
    url?: StringValue;
}
/**
 * @generated from protobuf message ConfigIcon.DeleteConfigIconRequest
 */
export interface DeleteConfigIconRequest {
    /**
     * @generated from protobuf field: google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateConfigIconRequest$Type extends MessageType<CreateConfigIconRequest> {
    constructor() {
        super("ConfigIcon.CreateConfigIconRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue },
            { no: 2, name: "Description", kind: "message", jsonName: "Description", T: () => StringValue },
            { no: 3, name: "Url", kind: "message", jsonName: "Url", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<CreateConfigIconRequest>): CreateConfigIconRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateConfigIconRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateConfigIconRequest): CreateConfigIconRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* google.protobuf.StringValue Description */ 2:
                    message.description = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.description);
                    break;
                case /* google.protobuf.StringValue Url */ 3:
                    message.url = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.url);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateConfigIconRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue Description = 2; */
        if (message.description)
            StringValue.internalBinaryWrite(message.description, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue Url = 3; */
        if (message.url)
            StringValue.internalBinaryWrite(message.url, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ConfigIcon.CreateConfigIconRequest
 */
export const CreateConfigIconRequest = new CreateConfigIconRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateConfigIconRequest$Type extends MessageType<UpdateConfigIconRequest> {
    constructor() {
        super("ConfigIcon.UpdateConfigIconRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue },
            { no: 2, name: "Description", kind: "message", jsonName: "Description", T: () => StringValue },
            { no: 3, name: "Url", kind: "message", jsonName: "Url", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<UpdateConfigIconRequest>): UpdateConfigIconRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateConfigIconRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateConfigIconRequest): UpdateConfigIconRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* google.protobuf.StringValue Description */ 2:
                    message.description = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.description);
                    break;
                case /* google.protobuf.StringValue Url */ 3:
                    message.url = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.url);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateConfigIconRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue Description = 2; */
        if (message.description)
            StringValue.internalBinaryWrite(message.description, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue Url = 3; */
        if (message.url)
            StringValue.internalBinaryWrite(message.url, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ConfigIcon.UpdateConfigIconRequest
 */
export const UpdateConfigIconRequest = new UpdateConfigIconRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteConfigIconRequest$Type extends MessageType<DeleteConfigIconRequest> {
    constructor() {
        super("ConfigIcon.DeleteConfigIconRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<DeleteConfigIconRequest>): DeleteConfigIconRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DeleteConfigIconRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteConfigIconRequest): DeleteConfigIconRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteConfigIconRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ConfigIcon.DeleteConfigIconRequest
 */
export const DeleteConfigIconRequest = new DeleteConfigIconRequest$Type();
/**
 * @generated ServiceType for protobuf service ConfigIcon.ConfigIconCommand
 */
export const ConfigIconCommand = new ServiceType("ConfigIcon.ConfigIconCommand", [
    { name: "CreateConfigIcon", options: {}, I: CreateConfigIconRequest, O: CommonResult },
    { name: "UpdateConfigIcon", options: {}, I: UpdateConfigIconRequest, O: CommonResult },
    { name: "DeleteConfigIcon", options: {}, I: DeleteConfigIconRequest, O: CommonResult }
]);
