// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "config_emoji_command.proto" (package "ConfigEmoji", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ConfigEmojiCommand } from "./config_emoji_command";
import type { DeleteConfigEmojiRequest } from "./config_emoji_command";
import type { UpdateConfigEmojiRequest } from "./config_emoji_command";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { CreateConfigEmojiRequest } from "./config_emoji_command";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service ConfigEmoji.ConfigEmojiCommand
 */
export interface IConfigEmojiCommandClient {
    /**
     * @generated from protobuf rpc: CreateConfigEmoji
     */
    createConfigEmoji(input: CreateConfigEmojiRequest, options?: RpcOptions): UnaryCall<CreateConfigEmojiRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: UpdateConfigEmoji
     */
    updateConfigEmoji(input: UpdateConfigEmojiRequest, options?: RpcOptions): UnaryCall<UpdateConfigEmojiRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: DeleteConfigEmoji
     */
    deleteConfigEmoji(input: DeleteConfigEmojiRequest, options?: RpcOptions): UnaryCall<DeleteConfigEmojiRequest, CommonResult>;
}
/**
 * @generated from protobuf service ConfigEmoji.ConfigEmojiCommand
 */
export class ConfigEmojiCommandClient implements IConfigEmojiCommandClient, ServiceInfo {
    typeName = ConfigEmojiCommand.typeName;
    methods = ConfigEmojiCommand.methods;
    options = ConfigEmojiCommand.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateConfigEmoji
     */
    createConfigEmoji(input: CreateConfigEmojiRequest, options?: RpcOptions): UnaryCall<CreateConfigEmojiRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateConfigEmojiRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateConfigEmoji
     */
    updateConfigEmoji(input: UpdateConfigEmojiRequest, options?: RpcOptions): UnaryCall<UpdateConfigEmojiRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateConfigEmojiRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteConfigEmoji
     */
    deleteConfigEmoji(input: DeleteConfigEmojiRequest, options?: RpcOptions): UnaryCall<DeleteConfigEmojiRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteConfigEmojiRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
