// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "helpdesk_catalog_command.proto" (package "HelpdeskCatalog", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Int32Value } from "../../Utils/google/protobuf/wrappers";
import { BoolValue } from "../../Utils/google/protobuf/wrappers";
import { StringValue } from "../../Utils/google/protobuf/wrappers";
/**
 * @generated from protobuf message HelpdeskCatalog.CreateHelpdeskCatalogRequest
 */
export interface CreateHelpdeskCatalogRequest {
    /**
     * @generated from protobuf field: google.protobuf.StringValue KeyCatalog = 1
     */
    keyCatalog?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue NameVn = 2
     */
    nameVn?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue Url = 3
     */
    url?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.BoolValue IsActived = 4
     */
    isActived?: BoolValue;
    /**
     * @generated from protobuf field: repeated string ContentDetailsMessages = 5
     */
    contentDetailsMessages: string[];
}
/**
 * @generated from protobuf message HelpdeskCatalog.UpdateHelpdeskCatalogRequest
 */
export interface UpdateHelpdeskCatalogRequest {
    /**
     * @generated from protobuf field: google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.StringValue KeyCatalog = 2
     */
    keyCatalog?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue NameVn = 3
     */
    nameVn?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue Url = 4
     */
    url?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.BoolValue IsActived = 5
     */
    isActived?: BoolValue;
}
/**
 * @generated from protobuf message HelpdeskCatalog.DeleteHelpdeskCatalogRequest
 */
export interface DeleteHelpdeskCatalogRequest {
    /**
     * @generated from protobuf field: google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateHelpdeskCatalogRequest$Type extends MessageType<CreateHelpdeskCatalogRequest> {
    constructor() {
        super("HelpdeskCatalog.CreateHelpdeskCatalogRequest", [
            { no: 1, name: "KeyCatalog", kind: "message", jsonName: "KeyCatalog", T: () => StringValue },
            { no: 2, name: "NameVn", kind: "message", jsonName: "NameVn", T: () => StringValue },
            { no: 3, name: "Url", kind: "message", jsonName: "Url", T: () => StringValue },
            { no: 4, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => BoolValue },
            { no: 5, name: "ContentDetailsMessages", kind: "scalar", jsonName: "ContentDetailsMessages", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateHelpdeskCatalogRequest>): CreateHelpdeskCatalogRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.contentDetailsMessages = [];
        if (value !== undefined)
            reflectionMergePartial<CreateHelpdeskCatalogRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateHelpdeskCatalogRequest): CreateHelpdeskCatalogRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.StringValue KeyCatalog */ 1:
                    message.keyCatalog = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.keyCatalog);
                    break;
                case /* google.protobuf.StringValue NameVn */ 2:
                    message.nameVn = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.nameVn);
                    break;
                case /* google.protobuf.StringValue Url */ 3:
                    message.url = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.url);
                    break;
                case /* google.protobuf.BoolValue IsActived */ 4:
                    message.isActived = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                case /* repeated string ContentDetailsMessages */ 5:
                    message.contentDetailsMessages.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateHelpdeskCatalogRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.StringValue KeyCatalog = 1; */
        if (message.keyCatalog)
            StringValue.internalBinaryWrite(message.keyCatalog, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue NameVn = 2; */
        if (message.nameVn)
            StringValue.internalBinaryWrite(message.nameVn, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue Url = 3; */
        if (message.url)
            StringValue.internalBinaryWrite(message.url, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.BoolValue IsActived = 4; */
        if (message.isActived)
            BoolValue.internalBinaryWrite(message.isActived, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* repeated string ContentDetailsMessages = 5; */
        for (let i = 0; i < message.contentDetailsMessages.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.contentDetailsMessages[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message HelpdeskCatalog.CreateHelpdeskCatalogRequest
 */
export const CreateHelpdeskCatalogRequest = new CreateHelpdeskCatalogRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateHelpdeskCatalogRequest$Type extends MessageType<UpdateHelpdeskCatalogRequest> {
    constructor() {
        super("HelpdeskCatalog.UpdateHelpdeskCatalogRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value },
            { no: 2, name: "KeyCatalog", kind: "message", jsonName: "KeyCatalog", T: () => StringValue },
            { no: 3, name: "NameVn", kind: "message", jsonName: "NameVn", T: () => StringValue },
            { no: 4, name: "Url", kind: "message", jsonName: "Url", T: () => StringValue },
            { no: 5, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => BoolValue }
        ]);
    }
    create(value?: PartialMessage<UpdateHelpdeskCatalogRequest>): UpdateHelpdeskCatalogRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateHelpdeskCatalogRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateHelpdeskCatalogRequest): UpdateHelpdeskCatalogRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* google.protobuf.StringValue KeyCatalog */ 2:
                    message.keyCatalog = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.keyCatalog);
                    break;
                case /* google.protobuf.StringValue NameVn */ 3:
                    message.nameVn = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.nameVn);
                    break;
                case /* google.protobuf.StringValue Url */ 4:
                    message.url = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.url);
                    break;
                case /* google.protobuf.BoolValue IsActived */ 5:
                    message.isActived = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateHelpdeskCatalogRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue KeyCatalog = 2; */
        if (message.keyCatalog)
            StringValue.internalBinaryWrite(message.keyCatalog, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue NameVn = 3; */
        if (message.nameVn)
            StringValue.internalBinaryWrite(message.nameVn, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue Url = 4; */
        if (message.url)
            StringValue.internalBinaryWrite(message.url, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.BoolValue IsActived = 5; */
        if (message.isActived)
            BoolValue.internalBinaryWrite(message.isActived, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message HelpdeskCatalog.UpdateHelpdeskCatalogRequest
 */
export const UpdateHelpdeskCatalogRequest = new UpdateHelpdeskCatalogRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteHelpdeskCatalogRequest$Type extends MessageType<DeleteHelpdeskCatalogRequest> {
    constructor() {
        super("HelpdeskCatalog.DeleteHelpdeskCatalogRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<DeleteHelpdeskCatalogRequest>): DeleteHelpdeskCatalogRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DeleteHelpdeskCatalogRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteHelpdeskCatalogRequest): DeleteHelpdeskCatalogRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteHelpdeskCatalogRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message HelpdeskCatalog.DeleteHelpdeskCatalogRequest
 */
export const DeleteHelpdeskCatalogRequest = new DeleteHelpdeskCatalogRequest$Type();
/**
 * @generated ServiceType for protobuf service HelpdeskCatalog.HelpdeskCatalogCommand
 */
export const HelpdeskCatalogCommand = new ServiceType("HelpdeskCatalog.HelpdeskCatalogCommand", [
    { name: "CreateHelpdeskCatalog", options: {}, I: CreateHelpdeskCatalogRequest, O: CommonResult },
    { name: "UpdateHelpdeskCatalog", options: {}, I: UpdateHelpdeskCatalogRequest, O: CommonResult },
    { name: "DeleteHelpdeskCatalog", options: {}, I: DeleteHelpdeskCatalogRequest, O: CommonResult }
]);
