// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "relationship_catalog_command.proto" (package "RelationshipCatalog", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { RelationshipCatalogCommand } from "./relationship_catalog_command";
import type { DeleteRelationshipCatalogRequest } from "./relationship_catalog_command";
import type { UpdateRelationshipCatalogRequest } from "./relationship_catalog_command";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { CreateRelationshipCatalogRequest } from "./relationship_catalog_command";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service RelationshipCatalog.RelationshipCatalogCommand
 */
export interface IRelationshipCatalogCommandClient {
    /**
     * @generated from protobuf rpc: CreateRelationshipCatalog
     */
    createRelationshipCatalog(input: CreateRelationshipCatalogRequest, options?: RpcOptions): UnaryCall<CreateRelationshipCatalogRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: UpdateRelationshipCatalog
     */
    updateRelationshipCatalog(input: UpdateRelationshipCatalogRequest, options?: RpcOptions): UnaryCall<UpdateRelationshipCatalogRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: DeleteRelationshipCatalog
     */
    deleteRelationshipCatalog(input: DeleteRelationshipCatalogRequest, options?: RpcOptions): UnaryCall<DeleteRelationshipCatalogRequest, CommonResult>;
}
/**
 * @generated from protobuf service RelationshipCatalog.RelationshipCatalogCommand
 */
export class RelationshipCatalogCommandClient implements IRelationshipCatalogCommandClient, ServiceInfo {
    typeName = RelationshipCatalogCommand.typeName;
    methods = RelationshipCatalogCommand.methods;
    options = RelationshipCatalogCommand.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateRelationshipCatalog
     */
    createRelationshipCatalog(input: CreateRelationshipCatalogRequest, options?: RpcOptions): UnaryCall<CreateRelationshipCatalogRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateRelationshipCatalogRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateRelationshipCatalog
     */
    updateRelationshipCatalog(input: UpdateRelationshipCatalogRequest, options?: RpcOptions): UnaryCall<UpdateRelationshipCatalogRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateRelationshipCatalogRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteRelationshipCatalog
     */
    deleteRelationshipCatalog(input: DeleteRelationshipCatalogRequest, options?: RpcOptions): UnaryCall<DeleteRelationshipCatalogRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteRelationshipCatalogRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
