// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "share_social_network_command.proto" (package "ShareSocialNetwork", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { StringValue } from "../../Utils/google/protobuf/wrappers";
/**
 * @generated from protobuf message ShareSocialNetwork.CreateShareSocialNetworkRequest
 */
export interface CreateShareSocialNetworkRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Url = 2
     */
    url?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Icon = 3
     */
    icon?: StringValue;
}
/**
 * @generated from protobuf message ShareSocialNetwork.UpdateShareSocialNetworkRequest
 */
export interface UpdateShareSocialNetworkRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Url = 2
     */
    url?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Icon = 3
     */
    icon?: StringValue;
}
/**
 * @generated from protobuf message ShareSocialNetwork.DeleteShareSocialNetworkRequest
 */
export interface DeleteShareSocialNetworkRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateShareSocialNetworkRequest$Type extends MessageType<CreateShareSocialNetworkRequest> {
    constructor() {
        super("ShareSocialNetwork.CreateShareSocialNetworkRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue },
            { no: 2, name: "Url", kind: "message", jsonName: "Url", T: () => StringValue },
            { no: 3, name: "Icon", kind: "message", jsonName: "Icon", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<CreateShareSocialNetworkRequest>): CreateShareSocialNetworkRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateShareSocialNetworkRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateShareSocialNetworkRequest): CreateShareSocialNetworkRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* optional google.protobuf.StringValue Url */ 2:
                    message.url = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.url);
                    break;
                case /* optional google.protobuf.StringValue Icon */ 3:
                    message.icon = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.icon);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateShareSocialNetworkRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue Url = 2; */
        if (message.url)
            StringValue.internalBinaryWrite(message.url, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue Icon = 3; */
        if (message.icon)
            StringValue.internalBinaryWrite(message.icon, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ShareSocialNetwork.CreateShareSocialNetworkRequest
 */
export const CreateShareSocialNetworkRequest = new CreateShareSocialNetworkRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateShareSocialNetworkRequest$Type extends MessageType<UpdateShareSocialNetworkRequest> {
    constructor() {
        super("ShareSocialNetwork.UpdateShareSocialNetworkRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue },
            { no: 2, name: "Url", kind: "message", jsonName: "Url", T: () => StringValue },
            { no: 3, name: "Icon", kind: "message", jsonName: "Icon", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<UpdateShareSocialNetworkRequest>): UpdateShareSocialNetworkRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateShareSocialNetworkRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateShareSocialNetworkRequest): UpdateShareSocialNetworkRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* optional google.protobuf.StringValue Url */ 2:
                    message.url = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.url);
                    break;
                case /* optional google.protobuf.StringValue Icon */ 3:
                    message.icon = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.icon);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateShareSocialNetworkRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue Url = 2; */
        if (message.url)
            StringValue.internalBinaryWrite(message.url, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue Icon = 3; */
        if (message.icon)
            StringValue.internalBinaryWrite(message.icon, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ShareSocialNetwork.UpdateShareSocialNetworkRequest
 */
export const UpdateShareSocialNetworkRequest = new UpdateShareSocialNetworkRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteShareSocialNetworkRequest$Type extends MessageType<DeleteShareSocialNetworkRequest> {
    constructor() {
        super("ShareSocialNetwork.DeleteShareSocialNetworkRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<DeleteShareSocialNetworkRequest>): DeleteShareSocialNetworkRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DeleteShareSocialNetworkRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteShareSocialNetworkRequest): DeleteShareSocialNetworkRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteShareSocialNetworkRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ShareSocialNetwork.DeleteShareSocialNetworkRequest
 */
export const DeleteShareSocialNetworkRequest = new DeleteShareSocialNetworkRequest$Type();
/**
 * @generated ServiceType for protobuf service ShareSocialNetwork.ShareSocialNetworkCommand
 */
export const ShareSocialNetworkCommand = new ServiceType("ShareSocialNetwork.ShareSocialNetworkCommand", [
    { name: "CreateShareSocialNetwork", options: {}, I: CreateShareSocialNetworkRequest, O: CommonResult },
    { name: "UpdateShareSocialNetwork", options: {}, I: UpdateShareSocialNetworkRequest, O: CommonResult },
    { name: "DeleteShareSocialNetwork", options: {}, I: DeleteShareSocialNetworkRequest, O: CommonResult }
]);
