// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "style_scss_command.proto" (package "StyleScss", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { StyleScssCommand } from "./style_scss_command";
import type { DeleteStyleScssRequest } from "./style_scss_command";
import type { UpdateStyleScssRequest } from "./style_scss_command";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { CreateStyleScssRequest } from "./style_scss_command";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service StyleScss.StyleScssCommand
 */
export interface IStyleScssCommandClient {
    /**
     * @generated from protobuf rpc: CreateStyleScss
     */
    createStyleScss(input: CreateStyleScssRequest, options?: RpcOptions): UnaryCall<CreateStyleScssRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: UpdateStyleScss
     */
    updateStyleScss(input: UpdateStyleScssRequest, options?: RpcOptions): UnaryCall<UpdateStyleScssRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: DeleteStyleScss
     */
    deleteStyleScss(input: DeleteStyleScssRequest, options?: RpcOptions): UnaryCall<DeleteStyleScssRequest, CommonResult>;
}
/**
 * @generated from protobuf service StyleScss.StyleScssCommand
 */
export class StyleScssCommandClient implements IStyleScssCommandClient, ServiceInfo {
    typeName = StyleScssCommand.typeName;
    methods = StyleScssCommand.methods;
    options = StyleScssCommand.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateStyleScss
     */
    createStyleScss(input: CreateStyleScssRequest, options?: RpcOptions): UnaryCall<CreateStyleScssRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateStyleScssRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateStyleScss
     */
    updateStyleScss(input: UpdateStyleScssRequest, options?: RpcOptions): UnaryCall<UpdateStyleScssRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateStyleScssRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteStyleScss
     */
    deleteStyleScss(input: DeleteStyleScssRequest, options?: RpcOptions): UnaryCall<DeleteStyleScssRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteStyleScssRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
