// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "website_other_ip_command.proto" (package "WebsiteOtherIPAddress", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { WebsiteOtherIPAddressCommand } from "./website_other_ip_command";
import type { DeleteWebsiteOtherIPAddressRequest } from "./website_other_ip_command";
import type { UpdateWebsiteOtherIPAddressRequest } from "./website_other_ip_command";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { CreateWebsiteOtherIPAddressRequest } from "./website_other_ip_command";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service WebsiteOtherIPAddress.WebsiteOtherIPAddressCommand
 */
export interface IWebsiteOtherIPAddressCommandClient {
    /**
     * @generated from protobuf rpc: CreateWebsiteOtherIPAddress
     */
    createWebsiteOtherIPAddress(input: CreateWebsiteOtherIPAddressRequest, options?: RpcOptions): UnaryCall<CreateWebsiteOtherIPAddressRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: UpdateWebsiteOtherIPAddress
     */
    updateWebsiteOtherIPAddress(input: UpdateWebsiteOtherIPAddressRequest, options?: RpcOptions): UnaryCall<UpdateWebsiteOtherIPAddressRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: DeleteWebsiteOtherIPAddress
     */
    deleteWebsiteOtherIPAddress(input: DeleteWebsiteOtherIPAddressRequest, options?: RpcOptions): UnaryCall<DeleteWebsiteOtherIPAddressRequest, CommonResult>;
}
/**
 * @generated from protobuf service WebsiteOtherIPAddress.WebsiteOtherIPAddressCommand
 */
export class WebsiteOtherIPAddressCommandClient implements IWebsiteOtherIPAddressCommandClient, ServiceInfo {
    typeName = WebsiteOtherIPAddressCommand.typeName;
    methods = WebsiteOtherIPAddressCommand.methods;
    options = WebsiteOtherIPAddressCommand.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateWebsiteOtherIPAddress
     */
    createWebsiteOtherIPAddress(input: CreateWebsiteOtherIPAddressRequest, options?: RpcOptions): UnaryCall<CreateWebsiteOtherIPAddressRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateWebsiteOtherIPAddressRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateWebsiteOtherIPAddress
     */
    updateWebsiteOtherIPAddress(input: UpdateWebsiteOtherIPAddressRequest, options?: RpcOptions): UnaryCall<UpdateWebsiteOtherIPAddressRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateWebsiteOtherIPAddressRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteWebsiteOtherIPAddress
     */
    deleteWebsiteOtherIPAddress(input: DeleteWebsiteOtherIPAddressRequest, options?: RpcOptions): UnaryCall<DeleteWebsiteOtherIPAddressRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteWebsiteOtherIPAddressRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
