// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "website_file_setting_command.proto" (package "WebsiteFileSetting", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Int32Value } from "../../Utils/google/protobuf/wrappers";
import { StringValue } from "../../Utils/google/protobuf/wrappers";
/**
 * @generated from protobuf message WebsiteFileSetting.CreateWebsiteFileSettingRequest
 */
export interface CreateWebsiteFileSettingRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue FileAllowed = 2
     */
    fileAllowed?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value FileSizeMax = 3
     */
    fileSizeMax?: Int32Value;
}
/**
 * @generated from protobuf message WebsiteFileSetting.UpdateWebsiteFileSettingRequest
 */
export interface UpdateWebsiteFileSettingRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue FileAllowed = 2
     */
    fileAllowed?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value FileSizeMax = 3
     */
    fileSizeMax?: Int32Value;
}
/**
 * @generated from protobuf message WebsiteFileSetting.DeleteWebsiteFileSettingRequest
 */
export interface DeleteWebsiteFileSettingRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateWebsiteFileSettingRequest$Type extends MessageType<CreateWebsiteFileSettingRequest> {
    constructor() {
        super("WebsiteFileSetting.CreateWebsiteFileSettingRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue },
            { no: 2, name: "FileAllowed", kind: "message", jsonName: "FileAllowed", T: () => StringValue },
            { no: 3, name: "FileSizeMax", kind: "message", jsonName: "FileSizeMax", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<CreateWebsiteFileSettingRequest>): CreateWebsiteFileSettingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateWebsiteFileSettingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateWebsiteFileSettingRequest): CreateWebsiteFileSettingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* optional google.protobuf.StringValue FileAllowed */ 2:
                    message.fileAllowed = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.fileAllowed);
                    break;
                case /* optional google.protobuf.Int32Value FileSizeMax */ 3:
                    message.fileSizeMax = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.fileSizeMax);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateWebsiteFileSettingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue FileAllowed = 2; */
        if (message.fileAllowed)
            StringValue.internalBinaryWrite(message.fileAllowed, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value FileSizeMax = 3; */
        if (message.fileSizeMax)
            Int32Value.internalBinaryWrite(message.fileSizeMax, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message WebsiteFileSetting.CreateWebsiteFileSettingRequest
 */
export const CreateWebsiteFileSettingRequest = new CreateWebsiteFileSettingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateWebsiteFileSettingRequest$Type extends MessageType<UpdateWebsiteFileSettingRequest> {
    constructor() {
        super("WebsiteFileSetting.UpdateWebsiteFileSettingRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue },
            { no: 2, name: "FileAllowed", kind: "message", jsonName: "FileAllowed", T: () => StringValue },
            { no: 3, name: "FileSizeMax", kind: "message", jsonName: "FileSizeMax", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<UpdateWebsiteFileSettingRequest>): UpdateWebsiteFileSettingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateWebsiteFileSettingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateWebsiteFileSettingRequest): UpdateWebsiteFileSettingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* optional google.protobuf.StringValue FileAllowed */ 2:
                    message.fileAllowed = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.fileAllowed);
                    break;
                case /* optional google.protobuf.Int32Value FileSizeMax */ 3:
                    message.fileSizeMax = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.fileSizeMax);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateWebsiteFileSettingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue FileAllowed = 2; */
        if (message.fileAllowed)
            StringValue.internalBinaryWrite(message.fileAllowed, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value FileSizeMax = 3; */
        if (message.fileSizeMax)
            Int32Value.internalBinaryWrite(message.fileSizeMax, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message WebsiteFileSetting.UpdateWebsiteFileSettingRequest
 */
export const UpdateWebsiteFileSettingRequest = new UpdateWebsiteFileSettingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteWebsiteFileSettingRequest$Type extends MessageType<DeleteWebsiteFileSettingRequest> {
    constructor() {
        super("WebsiteFileSetting.DeleteWebsiteFileSettingRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<DeleteWebsiteFileSettingRequest>): DeleteWebsiteFileSettingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DeleteWebsiteFileSettingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteWebsiteFileSettingRequest): DeleteWebsiteFileSettingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteWebsiteFileSettingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message WebsiteFileSetting.DeleteWebsiteFileSettingRequest
 */
export const DeleteWebsiteFileSettingRequest = new DeleteWebsiteFileSettingRequest$Type();
/**
 * @generated ServiceType for protobuf service WebsiteFileSetting.WebsiteFileSettingCommand
 */
export const WebsiteFileSettingCommand = new ServiceType("WebsiteFileSetting.WebsiteFileSettingCommand", [
    { name: "CreateWebsiteFileSetting", options: {}, I: CreateWebsiteFileSettingRequest, O: CommonResult },
    { name: "UpdateWebsiteFileSetting", options: {}, I: UpdateWebsiteFileSettingRequest, O: CommonResult },
    { name: "DeleteWebsiteFileSetting", options: {}, I: DeleteWebsiteFileSettingRequest, O: CommonResult }
]);
