// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "website_currency_command.proto" (package "WebsiteCurrency", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { BoolValue } from "../../Utils/google/protobuf/wrappers";
import { StringValue } from "../../Utils/google/protobuf/wrappers";
/**
 * @generated from protobuf message WebsiteCurrency.CreateWebsiteCurrencyRequest
 */
export interface CreateWebsiteCurrencyRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.BoolValue IsActived = 2
     */
    isActived?: BoolValue;
}
/**
 * @generated from protobuf message WebsiteCurrency.UpdateWebsiteCurrencyRequest
 */
export interface UpdateWebsiteCurrencyRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.BoolValue IsActived = 2
     */
    isActived?: BoolValue;
}
/**
 * @generated from protobuf message WebsiteCurrency.DeleteWebsiteCurrencyRequest
 */
export interface DeleteWebsiteCurrencyRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateWebsiteCurrencyRequest$Type extends MessageType<CreateWebsiteCurrencyRequest> {
    constructor() {
        super("WebsiteCurrency.CreateWebsiteCurrencyRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue },
            { no: 2, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => BoolValue }
        ]);
    }
    create(value?: PartialMessage<CreateWebsiteCurrencyRequest>): CreateWebsiteCurrencyRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateWebsiteCurrencyRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateWebsiteCurrencyRequest): CreateWebsiteCurrencyRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* optional google.protobuf.BoolValue IsActived */ 2:
                    message.isActived = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateWebsiteCurrencyRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.BoolValue IsActived = 2; */
        if (message.isActived)
            BoolValue.internalBinaryWrite(message.isActived, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message WebsiteCurrency.CreateWebsiteCurrencyRequest
 */
export const CreateWebsiteCurrencyRequest = new CreateWebsiteCurrencyRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateWebsiteCurrencyRequest$Type extends MessageType<UpdateWebsiteCurrencyRequest> {
    constructor() {
        super("WebsiteCurrency.UpdateWebsiteCurrencyRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue },
            { no: 2, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => BoolValue }
        ]);
    }
    create(value?: PartialMessage<UpdateWebsiteCurrencyRequest>): UpdateWebsiteCurrencyRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateWebsiteCurrencyRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateWebsiteCurrencyRequest): UpdateWebsiteCurrencyRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* optional google.protobuf.BoolValue IsActived */ 2:
                    message.isActived = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateWebsiteCurrencyRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.BoolValue IsActived = 2; */
        if (message.isActived)
            BoolValue.internalBinaryWrite(message.isActived, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message WebsiteCurrency.UpdateWebsiteCurrencyRequest
 */
export const UpdateWebsiteCurrencyRequest = new UpdateWebsiteCurrencyRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteWebsiteCurrencyRequest$Type extends MessageType<DeleteWebsiteCurrencyRequest> {
    constructor() {
        super("WebsiteCurrency.DeleteWebsiteCurrencyRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<DeleteWebsiteCurrencyRequest>): DeleteWebsiteCurrencyRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DeleteWebsiteCurrencyRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteWebsiteCurrencyRequest): DeleteWebsiteCurrencyRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteWebsiteCurrencyRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message WebsiteCurrency.DeleteWebsiteCurrencyRequest
 */
export const DeleteWebsiteCurrencyRequest = new DeleteWebsiteCurrencyRequest$Type();
/**
 * @generated ServiceType for protobuf service WebsiteCurrency.WebsiteCurrencyCommand
 */
export const WebsiteCurrencyCommand = new ServiceType("WebsiteCurrency.WebsiteCurrencyCommand", [
    { name: "CreateWebsiteCurrency", options: {}, I: CreateWebsiteCurrencyRequest, O: CommonResult },
    { name: "UpdateWebsiteCurrency", options: {}, I: UpdateWebsiteCurrencyRequest, O: CommonResult },
    { name: "DeleteWebsiteCurrency", options: {}, I: DeleteWebsiteCurrencyRequest, O: CommonResult }
]);
