const langConfig = [
    { key: 'hb-w-home-why-us-main-title', fallback: 'Tại sao chọn HomeBooking?' },
    { key: 'hb-w-home-why-us-subtitle', fallback: 'Subtitle here' },
    // Login Page - Branding Section
    { key: 'hb-w-login-ecosystem-badge', fallback: 'Hệ sinh thái 365' },
    { key: 'hb-w-login-welcome-prefix', fallback: 'Chào mừng bạn đến với' },
    { key: 'hb-w-login-platform-description', fallback: 'Nền tảng hợp nhất giúp bạn đặt và quản lý mọi dịch vụ tại nhà chỉ trong một ứng dụng.' },
    { key: 'hb-w-login-download-app-label', fallback: 'Tải ứng dụng ngay' },
    { key: 'hb-w-login-download-on', fallback: 'Download on the' },
    { key: 'hb-w-login-app-store', fallback: 'App Store' },
    { key: 'hb-w-login-get-it-on', fallback: 'Get it on' },
    { key: 'hb-w-login-google-play', fallback: 'Google Play' },
    { key: 'hb-w-login-app-interface-alt', fallback: 'App Interface' },
    // Login Page - Form Section
    { key: 'hb-w-login-back-to-home', fallback: 'Quay về trang chủ' },
    { key: 'hb-w-login-download-mobile', fallback: 'Tải App ngay' },
    { key: 'hb-w-login-title', fallback: 'Đăng nhập' },
    { key: 'hb-w-login-welcome-message', fallback: 'Chào mừng bạn đến với HomeBooking' },
    { key: 'hb-w-login-phone-label', fallback: 'Số điện thoại' },
    { key: 'hb-w-login-phone-placeholder', fallback: '123 456 789' },
    { key: 'hb-w-login-country-code', fallback: '+84' },
    { key: 'hb-w-login-password-label', fallback: 'Mật khẩu' },
    { key: 'hb-w-login-password-placeholder', fallback: '••••••••' },
    { key: 'hb-w-login-forgot-password', fallback: 'Quên mật khẩu?' },
    { key: 'hb-w-login-submit-loading', fallback: 'Đang đăng nhập...' },
    { key: 'hb-w-login-submit', fallback: 'Đăng nhập' },
    { key: 'hb-w-login-no-account', fallback: 'Chưa có tài khoản?' },
    { key: 'hb-w-login-register-now', fallback: 'Đăng ký ngay' },
    // Login Page - Toast Messages
    { key: 'hb-w-login-error-general', fallback: 'Đăng nhập thất bại' },
    { key: 'hb-w-login-success-title', fallback: 'Đăng nhập thành công' },
    { key: 'hb-w-login-success-message', fallback: 'Chào mừng bạn quay trở lại!' },
    { key: 'hb-w-login-error-title', fallback: 'Lỗi đăng nhập' },
    { key: 'hb-w-login-error-invalid', fallback: 'Số điện thoại hoặc mật khẩu không chính xác' },
    // Forgot Password Page
    { key: 'hb-w-forgot-password-title', fallback: 'Đặt lại mật khẩu' },
    { key: 'hb-w-forgot-password-subtitle', fallback: 'Nhập số điện thoại của bạn để bắt đầu khôi phục mật khẩu.' },
    { key: 'hb-w-forgot-password-phone-placeholder', fallback: 'Nhập số điện thoại' },
    { key: 'hb-w-forgot-password-submit-loading', fallback: 'Đang gửi...' },
    { key: 'hb-w-forgot-password-submit', fallback: 'Gửi mã xác thực' },
    { key: 'hb-w-forgot-password-remember', fallback: 'Nhớ lại mật khẩu?' },
    { key: 'hb-w-forgot-password-login-now', fallback: 'Đăng nhập ngay' },
    { key: 'hb-w-forgot-password-modal-title', fallback: 'Quên mật khẩu' },
    { key: 'hb-w-forgot-password-modal-message-1', fallback: 'Mật khẩu của bạn đã được gửi lại email.' },
    { key: 'hb-w-forgot-password-modal-message-2', fallback: 'Vui lòng kiểm tra email của bạn để lấy mật khẩu' },
    { key: 'hb-w-forgot-password-modal-confirm', fallback: 'Xác nhận' },
    { key: 'hb-w-forgot-password-error-send', fallback: 'Lỗi gửi mã' },
    { key: 'hb-w-forgot-password-error-send-message', fallback: 'Không thể gửi mã xác thực. Vui lòng thử lại sau.' },
    { key: 'hb-w-forgot-password-error-title', fallback: 'Lỗi' },
    { key: 'hb-w-forgot-password-error-not-found', fallback: 'Không tìm thấy tài khoản với số điện thoại này.' },
    { key: 'hb-w-forgot-password-error-account', fallback: 'Không thể tìm thấy thông tin tài khoản.' },
    { key: 'hb-w-forgot-password-success', fallback: 'Thay đổi mật khẩu thành công' },
    { key: 'hb-w-forgot-password-error-reset', fallback: 'Lỗi đặt lại mật khẩu' },
    { key: 'hb-w-forgot-password-error-reset-message', fallback: 'Có lỗi xảy ra khi đặt lại mật khẩu.' },
    // Register Page
    { key: 'hb-w-register-title', fallback: 'Tạo tài khoản' },
    { key: 'hb-w-register-subtitle', fallback: 'Tham gia cùng chúng tôi ngay hôm nay và trải nghiệm sự khác biệt.' },
    { key: 'hb-w-register-phone-placeholder', fallback: 'Nhập số điện thoại' },
    { key: 'hb-w-register-name-label', fallback: 'Họ và tên' },
    { key: 'hb-w-register-name-placeholder', fallback: 'Nhập họ và tên' },
    { key: 'hb-w-register-email-label', fallback: 'Email' },
    { key: 'hb-w-register-email-placeholder', fallback: 'Nhập địa chỉ email' },
    { key: 'hb-w-register-password-placeholder', fallback: 'Nhập mật khẩu' },
    { key: 'hb-w-register-confirm-password-label', fallback: 'Xác nhận mật khẩu' },
    { key: 'hb-w-register-confirm-password-placeholder', fallback: 'Nhập lại mật khẩu' },
    { key: 'hb-w-register-terms-label', fallback: 'Tôi đồng ý với các' },
    { key: 'hb-w-register-terms-link', fallback: 'điều khoản' },
    { key: 'hb-w-register-and', fallback: 'và' },
    { key: 'hb-w-register-policy-link', fallback: 'Chính sách bảo mật' },
    { key: 'hb-w-register-of-homebooking', fallback: 'của HomeBooking' },
    { key: 'hb-w-register-submit-loading', fallback: 'Đang xử lý...' },
    { key: 'hb-w-register-submit', fallback: 'Tạo tài khoản' },
    { key: 'hb-w-register-have-account', fallback: 'Đã có tài khoản?' },
    { key: 'hb-w-register-login-now', fallback: 'Đăng nhập ngay' },
    { key: 'hb-w-register-error-title', fallback: 'Lỗi đăng ký' },
    { key: 'hb-w-register-error-already-exists', fallback: 'Số điện thoại hoặc Email đã được sử dụng.' },
    { key: 'hb-w-register-terms-modal-title', fallback: 'Điều khoản dịch vụ' },
    { key: 'hb-w-register-policy-modal-title', fallback: 'Chính sách bảo mật' },
    { key: 'hb-w-register-terms-section-1', fallback: '1. Chấp thuận các điều khoản' },
    { key: 'hb-w-register-terms-content-1', fallback: 'Chào mừng bạn đến với HomeBooking. Bằng cách sử dụng dịch vụ của chúng tôi, bạn đồng ý tuân thủ các điều khoản và điều kiện được nêu tại đây.' },
    { key: 'hb-w-register-terms-section-2', fallback: '2. Quyền và nghĩa vụ' },
    { key: 'hb-w-register-terms-content-2', fallback: 'Người dùng có trách nhiệm bảo mật thông tin tài khoản và chịu trách nhiệm cho mọi hoạt động diễn ra dưới tài khoản của mình.' },
    { key: 'hb-w-register-terms-section-3', fallback: '3. Bảo mật thông tin' },
    { key: 'hb-w-register-terms-content-3', fallback: 'Chúng tôi cam kết bảo vệ thông tin cá nhân của bạn theo đúng quy định pháp luật và chính sách bảo mật của công ty.' },
    { key: 'hb-w-register-terms-placeholder', fallback: 'Đây là nội dung mẫu cho Điều khoản dịch vụ. Bạn có thể thay thế bằng nội dung chi tiết của dự án.' },
    { key: 'hb-w-register-terms-placeholder-policy', fallback: 'Đây là nội dung mẫu cho Chính sách bảo mật. Bạn có thể thay thế bằng nội dung chi tiết của dự án.' },
    { key: 'hb-w-register-understood', fallback: 'Tôi đã hiểu' },
    { key: 'hb-w-register-phone-label', fallback: 'Số điện thoại' },
    { key: 'hb-w-register-password-label', fallback: 'Mật khẩu' },
    // Profile Page - Sidebar
    { key: 'hb-w-profile-sidebar-dashboard', fallback: 'Tổng quan' },
    { key: 'hb-w-profile-sidebar-personal-info', fallback: 'Thông tin cá nhân' },
    { key: 'hb-w-profile-sidebar-booking-history', fallback: 'Lịch sử đặt lịch' },
    { key: 'hb-w-profile-sidebar-address', fallback: 'Địa chỉ' },
    { key: 'hb-w-profile-sidebar-change-password', fallback: 'Đổi mật khẩu' },
    // Profile Page - Main
    { key: 'hb-w-profile-edit-button', fallback: 'Chỉnh sửa' },
    { key: 'hb-w-profile-label-full-name', fallback: 'Họ và tên' },
    { key: 'hb-w-profile-label-email', fallback: 'Email' },
    { key: 'hb-w-profile-label-phone', fallback: 'Số điện thoại' },
    { key: 'hb-w-profile-label-gender', fallback: 'Giới tính' },
    { key: 'hb-w-profile-label-birthday', fallback: 'Sinh nhật' },
    { key: 'hb-w-profile-label-id-card', fallback: 'Số căn cước' },
    { key: 'hb-w-profile-label-insurance', fallback: 'Số bảo hiểm' },
    { key: 'hb-w-profile-label-city', fallback: 'Tỉnh/Thành phố' },
    { key: 'hb-w-profile-label-ward', fallback: 'Xã/Phường' },
    { key: 'hb-w-profile-label-address', fallback: 'Địa chỉ' },
    // Dashboard Page
    { key: 'hb-w-profile-dashboard-greeting', fallback: 'Xin chào, {{name}}!' },
    { key: 'hb-w-profile-dashboard-wish-message', fallback: 'Chúc bạn một ngày tốt lành và tìm được dịch vụ ưng ý.' },
    { key: 'hb-w-profile-dashboard-empty-message', fallback: 'Chưa có thông tin tổng quan' },
    // Booking History Page
    { key: 'hb-w-profile-booking-history-title', fallback: 'Lịch sử đặt lịch' },
    { key: 'hb-w-profile-booking-history-subtitle', fallback: 'Xem lại tất cả các dịch vụ bạn đã trải nghiệm' },
    { key: 'hb-w-profile-booking-history-empty', fallback: 'Không có lịch sử đặt lịch' },
    // Change Password Page
    { key: 'hb-w-profile-change-password-title', fallback: 'Đổi mật khẩu' },
    { key: 'hb-w-profile-change-password-subtitle', fallback: 'Cập nhật mật khẩu để bảo vệ tài khoản của bạn' },
    { key: 'hb-w-profile-change-password-current', fallback: 'Mật khẩu hiện tại' },
    { key: 'hb-w-profile-change-password-current-placeholder', fallback: 'Nhập mật khẩu hiện tại' },
    { key: 'hb-w-profile-change-password-new', fallback: 'Mật khẩu mới' },
    { key: 'hb-w-profile-change-password-new-placeholder', fallback: 'Nhập mật khẩu mới' },
    { key: 'hb-w-profile-change-password-confirm', fallback: 'Xác nhận mật khẩu mới' },
    { key: 'hb-w-profile-change-password-confirm-placeholder', fallback: 'Nhập lại mật khẩu mới' },
    { key: 'hb-w-profile-change-password-submit-loading', fallback: 'Đang cập nhật...' },
    { key: 'hb-w-profile-change-password-submit', fallback: 'Cập nhật mật khẩu' },
    { key: 'hb-w-profile-change-password-requirements-title', fallback: 'Yêu cầu mật khẩu' },
    { key: 'hb-w-profile-change-password-req-length', fallback: 'Từ 8 đến 32 ký tự' },
    { key: 'hb-w-profile-change-password-req-case', fallback: 'Phải chứa chữ hoa, chữ thường và số' },
    { key: 'hb-w-profile-change-password-req-number', fallback: 'Phải có ít nhất 1 số' },
    { key: 'hb-w-profile-change-password-success', fallback: 'Mật khẩu đã được cập nhật thành công!' },
    { key: 'hb-w-profile-change-password-update-title', fallback: 'Cập nhật mật khẩu' },
    { key: 'hb-w-profile-change-password-update-message-1', fallback: 'Mật khẩu của bạn đã được thay đổi thành công.' },
    { key: 'hb-w-profile-change-password-update-message-2', fallback: 'Bạn có muốn tiếp tục phiên đăng nhập này không?' },
    { key: 'hb-w-profile-change-password-logout', fallback: 'Đăng xuất' },
    { key: 'hb-w-profile-change-password-continue', fallback: 'Tiếp tục' },
    { key: 'hb-w-profile-change-password-error', fallback: 'Lỗi thay đổi' },
    { key: 'hb-w-profile-change-password-logout-success', fallback: 'Đăng xuất thành công' },
    // Address Page
    { key: 'hb-w-profile-address-list-title', fallback: 'Danh sách địa chỉ' },
    { key: 'hb-w-profile-address-list-subtitle', fallback: 'Các địa chỉ đã lưu để bạn dễ dàng chọn khi đặt dịch vụ' },
    { key: 'hb-w-profile-address-add-new', fallback: 'Thêm mới' },
    { key: 'hb-w-profile-address-empty', fallback: 'Không có địa chỉ' },
    { key: 'hb-w-profile-address-default-badge', fallback: 'Mặc định' },
    { key: 'hb-w-profile-address-set-default', fallback: 'Đặt làm mặc định' },
    { key: 'hb-w-profile-address-delete-title', fallback: 'Xóa địa chỉ' },
    { key: 'hb-w-profile-address-delete-confirm', fallback: 'Bạn có chắc chắn muốn xóa địa chỉ này không?' },
    { key: 'hb-w-profile-address-cancel', fallback: 'Hủy' },
    { key: 'hb-w-profile-address-delete-loading', fallback: 'Đang xóa...' },
    { key: 'hb-w-profile-address-delete', fallback: 'Xóa' },
    // Address Form - Create/Update
    { key: 'hb-w-profile-address-form-add-title', fallback: 'Thêm mới địa chỉ' },
    { key: 'hb-w-profile-address-form-update-title', fallback: 'Cập nhật địa chỉ' },
    { key: 'hb-w-profile-address-form-name-label', fallback: 'Tên địa chỉ' },
    { key: 'hb-w-profile-address-form-name-placeholder', fallback: 'Nhập tên của bạn' },
    { key: 'hb-w-profile-address-form-description-label', fallback: 'Mô tả' },
    { key: 'hb-w-profile-address-form-description-placeholder', fallback: 'Nhập mô tả' },
    { key: 'hb-w-profile-address-form-city-label', fallback: 'Tỉnh/Thành phố' },
    { key: 'hb-w-profile-address-form-ward-label', fallback: 'Phường/Xã' },
    { key: 'hb-w-profile-address-form-detail-label', fallback: 'Địa chỉ chi tiết' },
    { key: 'hb-w-profile-address-form-detail-placeholder', fallback: 'Nhập địa chỉ chi tiết' },
    { key: 'hb-w-profile-address-form-set-default', fallback: 'Đặt làm địa chỉ mặc định' },
    { key: 'hb-w-profile-address-form-save-loading', fallback: 'Đang lưu...' },
    { key: 'hb-w-profile-address-form-save', fallback: 'Lưu địa chỉ' },
    // Address Toast Messages
    { key: 'hb-w-profile-address-create-success', fallback: 'Thêm mới địa chỉ thành công' },
    { key: 'hb-w-profile-address-update-success', fallback: 'Cập nhật địa chỉ thành công' },
    { key: 'hb-w-profile-address-delete-success', fallback: 'Xóa địa chỉ thành công' },
    { key: 'hb-w-profile-address-error-general', fallback: 'Quá trình xãy ra lỗi. Vui lòng thử lại sau' },
    // Form Partner Page
    { key: 'hb-w-form-partner-title', fallback: 'Đăng ký trở thành đối tác' },
    { key: 'hb-w-form-partner-subtitle', fallback: 'Điền thông tin bên dưới, chúng tôi sẽ liên hệ với bạn trong vòng 24h.' },
    { key: 'hb-w-form-partner-step-personal', fallback: 'Thông tin cá nhân' },
    { key: 'hb-w-form-partner-step-career', fallback: 'Hồ sơ nghề nghiệp' },
    { key: 'hb-w-form-partner-basic-info', fallback: 'Thông tin cơ bản' },
    { key: 'hb-w-form-partner-career-info', fallback: 'Thông tin nghề nghiệp' },
    { key: 'hb-w-form-partner-work-location', fallback: 'Vị trí làm việc' },
    { key: 'hb-w-form-partner-update', fallback: 'Cập nhật' },
    { key: 'hb-w-form-partner-name-label', fallback: 'Họ và tên' },
    { key: 'hb-w-form-partner-name-placeholder', fallback: 'Nhập họ và tên của bạn' },
    { key: 'hb-w-form-partner-email-label', fallback: 'Email' },
    { key: 'hb-w-form-partner-email-placeholder', fallback: 'Nhập email của bạn' },
    { key: 'hb-w-form-partner-phone-label', fallback: 'Số điện thoại' },
    { key: 'hb-w-form-partner-phone-placeholder', fallback: 'Nhập số điện thoại của bạn' },
    { key: 'hb-w-form-partner-experience-label', fallback: 'Số năm kinh nghiệm' },
    { key: 'hb-w-form-partner-about-label', fallback: 'Giới thiệu bản thân' },
    { key: 'hb-w-form-partner-about-placeholder', fallback: 'Nhập giới thiệu bản thân' },
    { key: 'hb-w-form-partner-province-label', fallback: 'Tỉnh/Thành phố' },
    { key: 'hb-w-form-partner-ward-label', fallback: 'Phường/Xã' },
    { key: 'hb-w-form-partner-submit-success', fallback: 'Thông tin của bạn đang được xét duyệt.' },
    { key: 'hb-w-form-partner-submit-success-sub', fallback: 'Bạn sẽ nhận được thông báo khi tài khoản được kích hoạt.' },
    { key: 'hb-w-form-partner-back-home', fallback: 'Quay lại trang chủ' },
    { key: 'hb-w-form-partner-continue', fallback: 'Tiếp tục' },
    { key: 'hb-w-form-partner-change-service-title', fallback: 'Thay đổi dịch vụ' },
    { key: 'hb-w-form-partner-change-service-message', fallback: 'Bạn đã thay đổi dịch vụ. Tất cả hồ sơ nghề nghiệp trước đó sẽ bị xoá. Bạn có chắc muốn tiếp tục không?' },
    { key: 'hb-w-form-partner-cancel', fallback: 'Huỷ' },
    { key: 'hb-w-form-partner-check-info-error', fallback: 'Vui lòng kiểm tra lại thông tin partner' },
    // Form Partner - Toast Messages
    { key: 'hb-w-form-partner-error-general', fallback: 'Quá trình xãy ra lỗi. Vui lòng thử lại sau' },
    { key: 'hb-w-form-partner-update-info-success', fallback: 'Cập nhật thông tin thành công' },
    // Select Service
    { key: 'hb-w-form-partner-service-category', fallback: 'Danh mục dịch vụ' },
    { key: 'hb-w-form-partner-service-category-placeholder', fallback: 'Chọn danh mục' },
    { key: 'hb-w-form-partner-service-label', fallback: 'Dịch vụ' },
    { key: 'hb-w-form-partner-service-select-parent-first', fallback: 'Vui lòng chọn danh mục trước' },
    { key: 'hb-w-form-partner-service-loading', fallback: 'Đang tải dịch vụ...' },
    { key: 'hb-w-form-partner-service-select', fallback: 'Chọn dịch vụ' },
    // Image Upload
    { key: 'hb-w-form-partner-upload-image', fallback: 'Tải ảnh' },
    { key: 'hb-w-form-partner-upload-size', fallback: 'Tối đa tải lên: 1MB' },
    { key: 'hb-w-form-partner-upload-format', fallback: 'Hỗ trợ các file: JPG, PNG' },
    // Document Tabs
    { key: 'hb-w-form-partner-history', fallback: 'lịch sử' },
    { key: 'hb-w-form-partner-back', fallback: 'Quay lại' },
    { key: 'hb-w-form-partner-upload-profile', fallback: 'Tải lên hồ sơ' },
    // History Modal
    { key: 'hb-w-form-partner-register-history-title', fallback: 'Lịch sử đăng ký' },
    { key: 'hb-w-form-partner-history-uploaded', fallback: 'Đã gửi yêu cầu' },
    { key: 'hb-w-form-partner-history-verified', fallback: 'Đã xác minh' },
    { key: 'hb-w-form-partner-history-approved', fallback: 'Đã phê duyệt' },
    { key: 'hb-w-form-partner-history-rejected', fallback: 'Đã từ chối' },
    { key: 'hb-w-form-partner-history-disabled', fallback: 'Đã tắt' },
    { key: 'hb-w-form-partner-history-by', fallback: 'bởi' },
    { key: 'hb-w-form-partner-close', fallback: 'Đóng' },
    // Document Status
    { key: 'hb-w-form-partner-status-verifying', fallback: 'Đang xác minh' },
    { key: 'hb-w-form-partner-status-verified', fallback: 'Đã xác minh' },
    { key: 'hb-w-form-partner-status-rejected', fallback: 'Đã từ chối' },
    // Pending Page
    { key: 'hb-w-form-partner-pending-status', fallback: 'Đang xử lý' },
    { key: 'hb-w-form-partner-pending-title', fallback: 'Bạn đã gửi hồ sơ đăng ký đối tác' },
    { key: 'hb-w-form-partner-pending-description', fallback: 'Cảm ơn bạn đã quan tâm đến chương trình hợp tác của chúng tôi. Đơn đăng ký đã được ghi nhận và đang trong quá trình thẩm định. Chúng tôi sẽ phản hồi sớm nhất qua email.' },
    { key: 'hb-w-form-partner-view-profile', fallback: 'Xem hồ sơ' },
    // Success Page
    { key: 'hb-w-form-partner-success-title', fallback: 'Đăng ký thành công!' },
    { key: 'hb-w-form-partner-success-description', fallback: 'Cảm ơn bạn đã trở thành đối tác của chúng tôi. Hồ sơ của bạn đã được phê duyệt và tài khoản đã sẵn sàng để sử dụng.' },
    { key: 'hb-w-form-partner-success-email-hint', fallback: 'Vui lòng kiểm tra email của bạn để nhận thông tin hướng dẫn chi tiết và bắt đầu hành trình của chúng ta.' },
    // Save Tab / Document
    { key: 'hb-w-form-partner-save-minimum-error', fallback: 'Vui lòng nhập hoặc tải lên ít nhất một thông tin trước khi gửi' },
    { key: 'hb-w-form-partner-save-success', fallback: 'Tải lên hồ sơ thành công' },
    // Schema Validation
    { key: 'hb-w-form-partner-validate-ward', fallback: 'Vui lòng chọn phường/xã' },
    { key: 'hb-w-form-partner-validate-service', fallback: 'Vui lòng chọn dịch vụ' },
    { key: 'hb-w-form-partner-validate-province', fallback: 'Vui lòng chọn Tỉnh/Thành phố' },
    { key: 'hb-w-form-partner-validate-name', fallback: 'Vui lòng nhập họ và tên' },
    { key: 'hb-w-form-partner-validate-name-invalid', fallback: 'Tên không hợp lệ' },
    { key: 'hb-w-form-partner-validate-phone', fallback: 'Số điện thoại không hợp lệ' },
    { key: 'hb-w-form-partner-validate-email', fallback: 'Email không hợp lệ' },
    { key: 'hb-w-form-partner-validate-required', fallback: 'Trường thông tin bắt buộc' },
    { key: 'hb-w-form-partner-validate-experience-invalid', fallback: 'Số năm kinh nghiệm không hợp lệ' },
    { key: 'hb-w-form-partner-validate-experience-min', fallback: 'Không được nhỏ hơn 0 năm' },
    { key: 'hb-w-form-partner-validate-experience-max', fallback: 'Không được quá 100 năm' },
    // MainHeader - Navigation
    { key: 'hb-w-main-nav-home', fallback: 'Trang chủ' },
    { key: 'hb-w-main-nav-news', fallback: 'Tin tức' },
    { key: 'hb-w-main-nav-services', fallback: 'Dịch vụ' },
    { key: 'hb-w-main-nav-membership', fallback: 'Hội viên' },
    { key: 'hb-w-main-nav-experts', fallback: 'Chuyên gia' },
    // MainHeader - User Menu
    { key: 'hb-w-main-user-dropdown-personal-info', fallback: 'Thông tin cá nhân' },
    { key: 'hb-w-main-user-dropdown-register-partner', fallback: 'Đăng ký đối tác' },
    { key: 'hb-w-main-user-dropdown-logout', fallback: 'Đăng xuất' },
    // MainHeader - Mobile Menu
    { key: 'hb-w-main-mobile-menu-close', fallback: 'Đóng menu' },
    { key: 'hb-w-main-mobile-menu-open', fallback: 'Mở menu' },
    // MainHeader - Buttons & Login
    { key: 'hb-w-main-login-button', fallback: 'Đăng nhập' },
    // MainHeader - Logout Modal
    { key: 'hb-w-main-logout-modal-title', fallback: 'Xác nhận đăng xuất' },
    { key: 'hb-w-main-logout-modal-message', fallback: 'Bạn có chắc chắn muốn đăng xuất khỏi ứng dụng?' },
    { key: 'hb-w-main-logout-modal-cancel', fallback: 'Hủy' },
    { key: 'hb-w-main-logout-modal-confirm', fallback: 'Xác nhận' },
    // MainHeader - Toast Messages
    { key: 'hb-w-main-logout-success-title', fallback: 'Đăng xuất thành công' },
    { key: 'hb-w-main-logout-success-message', fallback: 'Hẹn gặp lại bạn sớm!' },
    { key: 'hb-w-main-logout-error-title', fallback: 'Đăng xuất thất bại' },
    { key: 'hb-w-main-logout-error-message', fallback: 'Vui lòng thử lại sau.' },
    // MainFooter - Section Headers
    { key: 'hb-w-main-footer-services-title', fallback: 'Dịch vụ' },
    { key: 'hb-w-main-footer-company-title', fallback: 'Công ty' },
    { key: 'hb-w-main-footer-support-title', fallback: 'Hỗ trợ' },
    // MainFooter - Services Links
    { key: 'hb-w-main-footer-service-cleaning', fallback: 'Dọn dẹp Giúp việc - Vệ sinh' },
    { key: 'hb-w-main-footer-service-repair', fallback: 'Sửa chữa Lắp đặt - Bảo trì' },
    { key: 'hb-w-main-footer-service-elder-baby', fallback: 'Mẹ & bé Người cao tuổi' },
    { key: 'hb-w-main-footer-service-massage', fallback: 'Massage body - foot' },
    { key: 'hb-w-main-footer-service-education', fallback: 'Giáo dục Huấn luyện - Giải trí' },
    { key: 'hb-w-main-footer-service-health', fallback: 'Chăm sóc sức khỏe' },
    { key: 'hb-w-main-footer-service-pet', fallback: 'Thú cưng' },
    { key: 'hb-w-main-footer-service-beauty', fallback: 'Làm móng Trang điểm - Làm tóc' },
    { key: 'hb-w-main-footer-service-other', fallback: 'Các dịch vụ khác' },
    // MainFooter - Company Links
    { key: 'hb-w-main-footer-company-about', fallback: 'Về chúng tôi' },
    { key: 'hb-w-main-footer-company-blog', fallback: 'Blog chuyên gia' },
    { key: 'hb-w-main-footer-company-careers', fallback: 'Tuyển dụng' },
    { key: 'hb-w-main-footer-company-privacy', fallback: 'Chính sách bảo mật' },
    // MainFooter - Support Links
    { key: 'hb-w-main-footer-support-help-center', fallback: 'Trung tâm trợ giúp' },
    { key: 'hb-w-main-footer-support-become-partner', fallback: 'Trở thành đối tác' },
    { key: 'hb-w-main-footer-support-safety', fallback: 'Biện pháp an toàn' },
    { key: 'hb-w-main-footer-support-contact', fallback: 'Liên hệ' },
    // MainFooter - Bottom
    { key: 'hb-w-main-footer-copyright', fallback: '© 2026 Homebooking. Tất cả quyền được bảo lưu.' },
    { key: 'hb-w-main-footer-cookie-settings', fallback: 'Cài đặt Cookie' },
    // HomePage - Hero Banner
    { key: 'hb-w-home-hero-banner-alt', fallback: 'Homebooking Banner' },
    // HomePage - Feature Section Header
    { key: 'hb-w-home-why-us-subtitle', fallback: 'Siêu app cung cấp đầy đủ các tính năng dịch vụ nhà tiện lợi và chuyên nghiệp.' },
    { key: 'hb-w-home-feature-price-title', fallback: 'Giá cả minh bạch' },
    { key: 'hb-w-home-feature-price-desc', fallback: 'Biết được chi phí trước. Không có phí ẩn hoặc bất ngờ.' },
    { key: 'hb-w-home-feature-expert-title', fallback: 'Chuyên gia' },
    { key: 'hb-w-home-feature-expert-desc', fallback: 'Chuyên gia được xác thực và được đào tạo cao cấp cho mọi tác vụ.' },
    { key: 'hb-w-home-feature-safety-title', fallback: 'An toàn' },
    { key: 'hb-w-home-feature-safety-desc', fallback: 'Tiêu chuẩn an toàn hàng đầu và bảo hiểm đầy đủ cho sự yên tâm của bạn.' },
    { key: 'hb-w-home-feature-guarantee-title', fallback: 'Đảm bảo dịch vụ' },
    { key: 'hb-w-home-feature-guarantee-desc', fallback: 'Cung cấp đầy đủ dịch vụ và đảm bảo chất lượng.' },
    // HomePage - Featured Services
    { key: 'hb-w-home-services-group-title', fallback: 'Nhóm dịch vụ' },
    { key: 'hb-w-home-services-group-badge', fallback: 'nổi bật' },
    { key: 'hb-w-home-services-group-subtitle', fallback: 'Các nhóm dịch vụ nổi bật nhất' },
    { key: 'hb-w-home-services-view-all', fallback: 'Xem tất cả' },
    { key: 'hb-w-home-services-see-more', fallback: 'Xem thêm' },
    { key: 'hb-w-home-services-loading', fallback: 'Đang tải dịch vụ...' },
    { key: 'hb-w-home-services-empty-title', fallback: 'Không có dữ liệu' },
    { key: 'hb-w-home-services-group-empty', fallback: 'Hiện tại chưa có nhóm dịch vụ nào' },
    { key: 'hb-w-home-services-section-title', fallback: 'Dịch vụ' },
    { key: 'hb-w-home-services-section-subtitle', fallback: 'Các dịch vụ được đặt nhiều nhất' },
    { key: 'hb-w-home-services-empty-featured', fallback: 'Chưa có dịch vụ nổi bật!' },
    { key: 'hb-w-home-services-no-rating', fallback: 'Chưa có lượt đánh giá' },
    // HomePage - Featured News
    { key: 'hb-w-home-news-title', fallback: 'Tin tức' },
    { key: 'hb-w-home-news-subtitle', fallback: 'Cập nhật tin tức và mẹo hàng tuần để giữ gìn ngôi nhà của bạn trong tốt nhất' },
    // HomePage - Partner Benefits
    { key: 'hb-w-home-partner-badge', fallback: 'Mạng lưới Chuyên gia' },
    { key: 'hb-w-home-partner-title-main', fallback: 'Trao quyền cho chuyên gia' },
    { key: 'hb-w-home-partner-title-sub', fallback: 'phát triển sự nghiệp' },
    { key: 'hb-w-home-partner-income-title', fallback: 'Thu nhập ổn định' },
    { key: 'hb-w-home-partner-income-desc', fallback: 'Tiếp cận hàng nghìn đặt chỗ có ý định cao mỗi tháng với thanh toán hàng tuần được đảm bảo.' },
    { key: 'hb-w-home-partner-schedule-title', fallback: 'Lịch làm việc linh hoạt' },
    { key: 'hb-w-home-partner-schedule-desc', fallback: 'Làm chủ thời gian của bạn. Làm việc khi bạn muốn và chọn khu vực dịch vụ phù hợp nhất với bạn.' },
    { key: 'hb-w-home-partner-training-title', fallback: 'Đào tạo chuyên nghiệp' },
    { key: 'hb-w-home-partner-training-desc', fallback: 'Nâng cao kỹ năng với các mô-đun đào tạo tiêu chuẩn vàng và chương trình chứng nhận của chúng tôi.' },
    { key: 'hb-w-home-partner-cta-button', fallback: 'Tham gia làm đối tác' },
    { key: 'hb-w-home-partner-stats-active', fallback: 'Đối tác hoạt động' },
    { key: 'hb-w-home-partner-stats-success', fallback: 'Tỷ lệ thành công' },
    // HomePage - Membership Program
    { key: 'hb-w-home-membership-badge', fallback: 'Chương trình Hội viên' },
    { key: 'hb-w-home-membership-title-main', fallback: 'Mở khóa' },
    { key: 'hb-w-home-membership-title-sub', fallback: 'Đặc quyền Vàng' },
    { key: 'hb-w-home-membership-desc', fallback: 'Tham gia chương trình hội viên độc quyền và trải nghiệm dịch vụ nhà như một VIP. Tiết kiệm hơn cho mỗi đặt chỗ và tận hưởng dịch vụ ưu tiên.' },
    { key: 'hb-w-home-membership-benefit-discount', fallback: 'Giảm 10% cho tất cả dịch vụ' },
    { key: 'hb-w-home-membership-benefit-free-exam', fallback: 'Miễn phí phí thăm khám' },
    { key: 'hb-w-home-membership-benefit-priority-booking', fallback: 'Đặt chỗ ưu tiên trong 4 giờ' },
    { key: 'hb-w-home-membership-benefit-dedicated-rm', fallback: 'Quản lý quan hệ chuyên dụng' },
    { key: 'hb-w-home-membership-register-btn', fallback: 'Đăng ký ngay' },
    { key: 'hb-w-home-membership-learn-btn', fallback: 'Tìm hiểu thêm' },
    { key: 'hb-w-home-membership-card-label', fallback: 'Tên thành viên' },
    { key: 'hb-w-home-membership-card-value', fallback: 'ĐỐI TÁC QUÝ GIÁ' },
    { key: 'hb-w-home-membership-card-validity', fallback: 'Có hiệu lực đến' },
    { key: 'hb-w-home-membership-stats', fallback: 'Tham gia cùng 500k+ thành viên Vàng đang hoạt động' },
    // HomePage - App Download Section
    { key: 'hb-w-home-app-download-title', fallback: 'Tất cả nhu cầu, một ứng dụng duy nhất.' },
    { key: 'hb-w-home-app-download-desc', fallback: 'Homebooking là siêu app đa dịch vụ giúp bạn đặt mọi nhu cầu chỉ trong một ứng dụng duy nhất – từ quán ăn, cà phê, homestay, khách sạn, tour du lịch, dịch vụ địa phương đến thanh toán, quản lý đặt chỗ và ưu đãi thông minh, mang lại trải nghiệm nhanh – tiện – đồng bộ cho cả người dùng và đối tác.' },
    { key: 'hb-w-home-app-download-appstore-label', fallback: 'Tải xuống trên' },
    { key: 'hb-w-home-app-download-appstore', fallback: 'App Store' },
    { key: 'hb-w-home-app-download-googleplay-label', fallback: 'Tải trên' },
    { key: 'hb-w-home-app-download-googleplay', fallback: 'Google Play' },
    { key: 'hb-w-home-app-download-image-alt', fallback: 'HomeBooking App' },
    // ChangeInfo Page
    { key: 'hb-w-change-info-title', fallback: 'Cập nhật hồ sơ' },
    { key: 'hb-w-change-info-cancel', fallback: 'Hủy' },
    { key: 'hb-w-change-info-save', fallback: 'Lưu thay đổi' },
    { key: 'hb-w-change-info-basic-info-title', fallback: 'Thông tin cơ bản' },
    { key: 'hb-w-change-info-firstname-label', fallback: 'Họ' },
    { key: 'hb-w-change-info-firstname-placeholder', fallback: 'Nhập họ của bạn' },
    { key: 'hb-w-change-info-lastname-label', fallback: 'Tên' },
    { key: 'hb-w-change-info-lastname-placeholder', fallback: 'Nhập tên của bạn' },
    { key: 'hb-w-change-info-dob-label', fallback: 'Ngày sinh' },
    { key: 'hb-w-change-info-gender-label', fallback: 'Giới tính' },
    { key: 'hb-w-change-info-gender-male', fallback: 'Nam' },
    { key: 'hb-w-change-info-gender-female', fallback: 'Nữ' },
    { key: 'hb-w-change-info-gender-other', fallback: 'Khác' },
    { key: 'hb-w-change-info-document-title', fallback: 'Thông tin giấy tờ' },
    { key: 'hb-w-change-info-idcard-label', fallback: 'Số căn cước' },
    { key: 'hb-w-change-info-idcard-placeholder', fallback: 'Nhập số căn cước của bạn' },
    { key: 'hb-w-change-info-insurance-label', fallback: 'Số bảo hiểm' },
    { key: 'hb-w-change-info-insurance-placeholder', fallback: 'Nhập số bảo hiểm của bạn' },
    { key: 'hb-w-change-info-address-title', fallback: 'Địa chỉ' },
    { key: 'hb-w-change-info-province-label', fallback: 'Tỉnh/Thành phố' },
    { key: 'hb-w-change-info-ward-label', fallback: 'Phường/Xã' },
    { key: 'hb-w-change-info-detail-address-label', fallback: 'Địa chỉ chi tiết' },
    { key: 'hb-w-change-info-detail-address-placeholder', fallback: 'Số nhà, tên đường...' },
    { key: 'hb-w-change-info-upload-avatar-hint', fallback: 'Chỉ chấp nhận ảnh có dung lượng dưới 2MB và định dạng .jpg, .jpeg, .png' },
    { key: 'hb-w-change-info-upload-button', fallback: 'Tải ảnh lên' },
    { key: 'hb-w-change-info-update-success', fallback: 'Cập nhật thông tin thành công' },
    { key: 'hb-w-change-info-error-general', fallback: 'Quá trình xảy ra lỗi. Vui lòng thử lại sau' },
    { key: 'hb-w-change-info-upload-size-error', fallback: 'Ảnh vượt quá giới hạn cho phép, vui lòng chọn ảnh khác!' },
    // ChangeInfo Schema Validation
    { key: 'hb-w-change-info-validate-firstname-required', fallback: 'Họ không được để trống' },
    { key: 'hb-w-change-info-validate-firstname-max', fallback: 'Họ không được quá 50 ký tự' },
    { key: 'hb-w-change-info-validate-lastname-required', fallback: 'Tên không được để trống' },
    { key: 'hb-w-change-info-validate-lastname-max', fallback: 'Tên không được quá 50 ký tự' },
    { key: 'hb-w-change-info-validate-gender-required', fallback: 'Vui lòng chọn giới tính' },
    { key: 'hb-w-change-info-validate-idcard-invalid', fallback: 'CMND/CCCD không hợp lệ' },
    { key: 'hb-w-change-info-validate-address-min', fallback: 'Địa chỉ chi tiết phải có ít nhất 5 ký tự' },
    { key: 'hb-w-change-info-validate-province-required', fallback: 'Vui lòng chọn Tỉnh/Thành phố' },
    { key: 'hb-w-change-info-validate-ward-required', fallback: 'Vui lòng chọn Phường/Xã' },
    { key: 'hb-w-profile-address-form-update-title', fallback: 'Cập nhật địa chỉ' },
    { key: 'hb-w-profile-address-update-success', fallback: 'Cập nhật địa chỉ thành công' },
] as const

const toConstName = (key: string) => key.toUpperCase().replace(/-/g, '_')

export const LANG_KEYS = Object.fromEntries(
    langConfig.map(item => [toConstName(item.key), item])
)
