export const PROVINCES = [
    { label: 'An Giang', value: 'an-giang' },
    { label: 'Bắc Ninh', value: 'bac-ninh' },
    { label: 'Cà Mau', value: 'ca-mau' },
    { label: 'Cao Bằng', value: 'cao-bang' },
    { label: 'Đắk Lắk', value: 'dak-lak' },
    { label: 'Điện Biên', value: 'dien-bien' },
    { label: 'Đồng Nai', value: 'dong-nai' },
    { label: 'Đồng Tháp', value: 'dong-thap' },
    { label: 'Gia Lai', value: 'gia-lai' },
    { label: 'Hà Tĩnh', value: 'ha-tinh' },
    { label: 'Hưng Yên', value: 'hung-yen' },
    { label: 'Khánh Hòa', value: 'khanh-hoa' },
    { label: 'Lai Châu', value: 'lai-chau' },
    { label: 'Lạng Sơn', value: 'lang-son' },
    { label: 'Lào Cai', value: 'lao-cai' },
    { label: 'Lâm Đồng', value: 'lam-dong' },
    { label: 'Nghệ An', value: 'nghe-an' },
    { label: 'Ninh Bình', value: 'ninh-binh' },
    { label: 'Phú Thọ', value: 'phu-tho' },
    { label: 'Quảng Ngãi', value: 'quang-ngai' },
    { label: 'Quảng Ninh', value: 'quang-ninh' },
    { label: 'Quảng Trị', value: 'quang-tri' },
    { label: 'Sơn La', value: 'son-la' },
    { label: 'Tây Ninh', value: 'tay-ninh' },
    { label: 'Thái Nguyên', value: 'thai-nguyen' },
    { label: 'Thanh Hóa', value: 'thanh-hoa' },
    { label: 'Thành phố Cần Thơ', value: 'can-tho' },
    { label: 'Thành phố Đà Nẵng', value: 'da-nang' },
    { label: 'Thành phố Hà Nội', value: 'ha-noi' },
    { label: 'Thành phố Hải Phòng', value: 'hai-phong' },
    { label: 'Thành phố Hồ Chí Minh', value: 'ho-chi-minh' },
    { label: 'Thành phố Huế', value: 'hue' },
    { label: 'Tuyên Quang', value: 'tuyen-quang' },
    { label: 'Vĩnh Long', value: 'vinh-long' }
];

export const WARDS = [
    { label: 'Phường 1', value: 'p1' },
    { label: 'Phường 2', value: 'p2' },
    { label: 'Phường 3', value: 'p3' },
    { label: 'Phường 4', value: 'p4' },
    { label: 'Phường 5', value: 'p5' },
    { label: 'Phường 6', value: 'p6' },
    { label: 'Phường 7', value: 'p7' },
    { label: 'Phường 8', value: 'p8' },
    { label: 'Phường 9', value: 'p9' },
    { label: 'Phường 10', value: 'p10' },
    { label: 'Phường 11', value: 'p11' },
    { label: 'Phường 12', value: 'p12' },
    { label: 'Phường 13', value: 'p13' },
    { label: 'Phường 14', value: 'p14' },
    { label: 'Phường 15', value: 'p15' },
    { label: 'Phường Bến Nghé', value: 'ben-nghe' },
    { label: 'Phường Bến Thành', value: 'ben-thanh' },
    { label: 'Phường Cô Giang', value: 'co-giang' },
    { label: 'Phường Nguyễn Thái Bình', value: 'nguyen-thai-binh' },
    { label: 'Phường Phạm Ngũ Lão', value: 'pham-ngu-lao' },
    { label: 'Phường Thảo Điền', value: 'thao-dien' },
    { label: 'Phường An Phú', value: 'an-phu' },
    { label: 'Phường Thủ Thiêm', value: 'thu-thiem' },
    { label: 'Phường Bình Khánh', value: 'binh-khanh' },
    { label: 'Phường Tân Thuận Đông', value: 'tan-thuan-dong' },
    { label: 'Phường Tân Thuận Tây', value: 'tan-thuan-tay' },
    { label: 'Phường Phú Mỹ', value: 'phu-my' },
    { label: 'Phường Tân Phong', value: 'tan-phong' },
    { label: 'Phường Tân Phú', value: 'tan-phu' },
    { label: 'Phường Hiệp Bình Chánh', value: 'hiep-binh-chanh' },
    { label: 'Phường Hiệp Bình Phước', value: 'hiep-binh-phuoc' },
    { label: 'Phường Linh Chiểu', value: 'linh-chieu' },
    { label: 'Phường Linh Đông', value: 'linh-dong' },
    { label: 'Phường Linh Tây', value: 'linh-tay' },
    { label: 'Phường Linh Trung', value: 'linh-trung' },
    { label: 'Phường Linh Xuân', value: 'linh-xuan' },
    { label: 'Phường Bình Thọ', value: 'binh-tho' },
    { label: 'Phường Trường Thọ', value: 'truong-tho' },
    { label: 'Phường Bình Tân', value: 'binh-tan' },
    { label: 'Phường Hiệp Tân', value: 'hiep-tan' },
    { label: 'Phường Hòa Thạnh', value: 'hoa-thanh' },
    { label: 'Phường Phú Thạnh', value: 'phu-thanh' },
    { label: 'Phường Phú Thọ Hòa', value: 'phu-tho-hoa' },
    { label: 'Phường Phú Trung', value: 'phu-trung' },
    { label: 'Phường Sơn Kỳ', value: 'son-ky' },
    { label: 'Phường Tân Quý', value: 'tan-quy' },
    { label: 'Phường Tân Sơn Nhì', value: 'tan-son-nhi' },
    { label: 'Phường Tân Thành', value: 'tan-thanh' },
    { label: 'Phường Tân Thới Hòa', value: 'tan-thoi-hoa' },
    { label: 'Phường Tây Thạnh', value: 'tay-thanh' },
    { label: 'Phường Cầu Ông Lãnh', value: 'cau-ong-lanh' },
    { label: 'Phường Đa Kao', value: 'da-kao' },
    { label: 'Phường Tân Định', value: 'tan-dinh' },
    { label: 'Phường Cầu Kho', value: 'cau-kho' },
    { label: 'Phường Nguyễn Cư Trinh', value: 'nguyen-cu-trinh' },
    { label: 'Phường Tràng Tiền', value: 'trang-tien' },
    { label: 'Phường Hàng Bài', value: 'hang-bai' },
    { label: 'Phường Phan Chu Trinh', value: 'phan-chu-trinh' },
    { label: 'Phường Hàng Trống', value: 'hang-trong' },
    { label: 'Phường Điện Biên', value: 'dien-bien-phuong' },
    { label: 'Phường Kim Mã', value: 'kim-ma' },
    { label: 'Phường Ngọc Khánh', value: 'ngoc-khanh' },
    { label: 'Phường Trúc Bạch', value: 'truc-bach' },
    { label: 'Phường Cát Linh', value: 'cat-linh' },
    { label: 'Phường Văn Miếu', value: 'van-mieu' },
    { label: 'Phường Quốc Tử Giám', value: 'quoc-tu-giam' },
    { label: 'Phường Mỹ Đình 1', value: 'my-dinh-1' },
    { label: 'Phường Mỹ Đình 2', value: 'my-dinh-2' },
    { label: 'Phường Cầu Diễn', value: 'cau-dien' },
    { label: 'Phường Dịch Vọng', value: 'dich-vong' },
    { label: 'Phường Nghĩa Đô', value: 'nghia-do' },
    { label: 'Phường Quan Hoa', value: 'quan-hoa' },
    { label: 'Phường Trung Hòa', value: 'trung-hoa' },
    { label: 'Phường Yên Hòa', value: 'yen-hoa' },
    { label: 'Xã Bình Hưng', value: 'binh-hung' },
    { label: 'Xã Phong Phú', value: 'phong-phu' },
    { label: 'Xã Vĩnh Lộc A', value: 'vinh-loc-a' },
    { label: 'Xã Vĩnh Lộc B', value: 'vinh-loc-b' },
    { label: 'Xã Phạm Văn Hai', value: 'pham-van-hai' },
    { label: 'Xã Tân Kiên', value: 'tan-kien' },
    { label: 'Xã Bà Điểm', value: 'ba-diem' },
    { label: 'Xã Xuân Thới Thượng', value: 'xuan-thoi-thuong' },
    { label: 'Thị trấn Hóc Môn', value: 'tt-hoc-mon' },
    { label: 'Thị trấn Củ Chi', value: 'tt-cu-chi' }
];
