// 'DEFAULT' | 'ACTIVATE_ACCOUNT' | 'RESET_PASSWORD' | 'SEND_NEW_PASSWORD'
export const OTP_CASE = {
    DEFAULT: 'DEFAULT',
    ACTIVATE_ACCOUNT: 'ACTIVATE_ACCOUNT',
    RESET_PASSWORD: 'RESET_PASSWORD',
    SEND_NEW_PASSWORD: 'SEND_NEW_PASSWORD',
};
