export const TANSTACK_KEY = {
  GET_ALL_WARD: "GET_ALL_WARD",
  GET_ALL_SERVICE: "GET_ALL_SERVICE",
  GET_DETAIL_SERVICE: "GET_DETAIL_SERVICE",
  GET_USER_INFO: 'GET_USER_INFO',
  GET_ALL_SERVICE_REQUIREMENT: "GET_ALL_SERVICE_REQUIREMENT",
  GET_DETAIL_PARTNER_PROFILE: 'GET_DETAIL_PARTNER_PROFILE',
  GET_ALL_PROVINCE: 'GET_ALL_PROVINCE',
  GET_DETAIL_WARD: 'GET_DETAIL_WARD',
  GET_ALL_SERVICE_CHILD: "GET_ALL_SERVICE_CHILD",
  GET_SERVICE_DETAIL: 'GET_SERVICE_DETAIL',
  GET_ALL_LANGUAGES: 'GET_ALL_LANGUAGES',
  GET_ALL_LANGS: 'GET_ALL_LANGS',
  GET_AVERAGE_PRICE_APPLIED: 'GET_AVERAGE_PRICE_APPLIED',
  GET_ALL_PARTNER_UNIT_CATALOG: 'GET_ALL_PARTNER_UNIT_CATALOG',
  GET_ALL_PARTNER_SERVICES: 'GET_ALL_PARTNER_SERVICES'
} as const
