// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "partner_doc_review_history_command.proto" (package "PartnerDocReviewHistory", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PartnerDocReviewHistoryCommand } from "./partner_doc_review_history_command";
import type { DeletePartnerDocReviewHistoryRequest } from "./partner_doc_review_history_command";
import type { UpdatePartnerDocReviewHistoryRequest } from "./partner_doc_review_history_command";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { CreatePartnerDocReviewHistoryRequest } from "./partner_doc_review_history_command";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service PartnerDocReviewHistory.PartnerDocReviewHistoryCommand
 */
export interface IPartnerDocReviewHistoryCommandClient {
    /**
     * @generated from protobuf rpc: CreatePartnerDocReviewHistory
     */
    createPartnerDocReviewHistory(input: CreatePartnerDocReviewHistoryRequest, options?: RpcOptions): UnaryCall<CreatePartnerDocReviewHistoryRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: UpdatePartnerDocReviewHistory
     */
    updatePartnerDocReviewHistory(input: UpdatePartnerDocReviewHistoryRequest, options?: RpcOptions): UnaryCall<UpdatePartnerDocReviewHistoryRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: DeletePartnerDocReviewHistory
     */
    deletePartnerDocReviewHistory(input: DeletePartnerDocReviewHistoryRequest, options?: RpcOptions): UnaryCall<DeletePartnerDocReviewHistoryRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminCreatePartnerDocReviewHistory
     */
    adminCreatePartnerDocReviewHistory(input: CreatePartnerDocReviewHistoryRequest, options?: RpcOptions): UnaryCall<CreatePartnerDocReviewHistoryRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminUpdatePartnerDocReviewHistory
     */
    adminUpdatePartnerDocReviewHistory(input: UpdatePartnerDocReviewHistoryRequest, options?: RpcOptions): UnaryCall<UpdatePartnerDocReviewHistoryRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminDeletePartnerDocReviewHistory
     */
    adminDeletePartnerDocReviewHistory(input: DeletePartnerDocReviewHistoryRequest, options?: RpcOptions): UnaryCall<DeletePartnerDocReviewHistoryRequest, CommonResult>;
}
/**
 * @generated from protobuf service PartnerDocReviewHistory.PartnerDocReviewHistoryCommand
 */
export class PartnerDocReviewHistoryCommandClient implements IPartnerDocReviewHistoryCommandClient, ServiceInfo {
    typeName = PartnerDocReviewHistoryCommand.typeName;
    methods = PartnerDocReviewHistoryCommand.methods;
    options = PartnerDocReviewHistoryCommand.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreatePartnerDocReviewHistory
     */
    createPartnerDocReviewHistory(input: CreatePartnerDocReviewHistoryRequest, options?: RpcOptions): UnaryCall<CreatePartnerDocReviewHistoryRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePartnerDocReviewHistoryRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePartnerDocReviewHistory
     */
    updatePartnerDocReviewHistory(input: UpdatePartnerDocReviewHistoryRequest, options?: RpcOptions): UnaryCall<UpdatePartnerDocReviewHistoryRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePartnerDocReviewHistoryRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeletePartnerDocReviewHistory
     */
    deletePartnerDocReviewHistory(input: DeletePartnerDocReviewHistoryRequest, options?: RpcOptions): UnaryCall<DeletePartnerDocReviewHistoryRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePartnerDocReviewHistoryRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminCreatePartnerDocReviewHistory
     */
    adminCreatePartnerDocReviewHistory(input: CreatePartnerDocReviewHistoryRequest, options?: RpcOptions): UnaryCall<CreatePartnerDocReviewHistoryRequest, CommonResult> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePartnerDocReviewHistoryRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminUpdatePartnerDocReviewHistory
     */
    adminUpdatePartnerDocReviewHistory(input: UpdatePartnerDocReviewHistoryRequest, options?: RpcOptions): UnaryCall<UpdatePartnerDocReviewHistoryRequest, CommonResult> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePartnerDocReviewHistoryRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminDeletePartnerDocReviewHistory
     */
    adminDeletePartnerDocReviewHistory(input: DeletePartnerDocReviewHistoryRequest, options?: RpcOptions): UnaryCall<DeletePartnerDocReviewHistoryRequest, CommonResult> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePartnerDocReviewHistoryRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
