// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "partner_unit_catalog_command.proto" (package "PartnerUnitCatalog", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PartnerUnitCatalogCommand } from "./partner_unit_catalog_command";
import type { AdminUpdatePartnerUnitCatalogRequest } from "./partner_unit_catalog_command";
import type { AdminCreatePartnerUnitCatalogRequest } from "./partner_unit_catalog_command";
import type { DeletePartnerUnitCatalogRequest } from "./partner_unit_catalog_command";
import type { UpdatePartnerUnitCatalogRequest } from "./partner_unit_catalog_command";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { CreatePartnerUnitCatalogRequest } from "./partner_unit_catalog_command";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service PartnerUnitCatalog.PartnerUnitCatalogCommand
 */
export interface IPartnerUnitCatalogCommandClient {
    /**
     * @generated from protobuf rpc: CreatePartnerUnitCatalog
     */
    createPartnerUnitCatalog(input: CreatePartnerUnitCatalogRequest, options?: RpcOptions): UnaryCall<CreatePartnerUnitCatalogRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: UpdatePartnerUnitCatalog
     */
    updatePartnerUnitCatalog(input: UpdatePartnerUnitCatalogRequest, options?: RpcOptions): UnaryCall<UpdatePartnerUnitCatalogRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: DeletePartnerUnitCatalog
     */
    deletePartnerUnitCatalog(input: DeletePartnerUnitCatalogRequest, options?: RpcOptions): UnaryCall<DeletePartnerUnitCatalogRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminCreatePartnerUnitCatalog
     */
    adminCreatePartnerUnitCatalog(input: AdminCreatePartnerUnitCatalogRequest, options?: RpcOptions): UnaryCall<AdminCreatePartnerUnitCatalogRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminUpdatePartnerUnitCatalog
     */
    adminUpdatePartnerUnitCatalog(input: AdminUpdatePartnerUnitCatalogRequest, options?: RpcOptions): UnaryCall<AdminUpdatePartnerUnitCatalogRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminDeletePartnerUnitCatalog
     */
    adminDeletePartnerUnitCatalog(input: DeletePartnerUnitCatalogRequest, options?: RpcOptions): UnaryCall<DeletePartnerUnitCatalogRequest, CommonResult>;
}
/**
 * @generated from protobuf service PartnerUnitCatalog.PartnerUnitCatalogCommand
 */
export class PartnerUnitCatalogCommandClient implements IPartnerUnitCatalogCommandClient, ServiceInfo {
    typeName = PartnerUnitCatalogCommand.typeName;
    methods = PartnerUnitCatalogCommand.methods;
    options = PartnerUnitCatalogCommand.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreatePartnerUnitCatalog
     */
    createPartnerUnitCatalog(input: CreatePartnerUnitCatalogRequest, options?: RpcOptions): UnaryCall<CreatePartnerUnitCatalogRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePartnerUnitCatalogRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePartnerUnitCatalog
     */
    updatePartnerUnitCatalog(input: UpdatePartnerUnitCatalogRequest, options?: RpcOptions): UnaryCall<UpdatePartnerUnitCatalogRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePartnerUnitCatalogRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeletePartnerUnitCatalog
     */
    deletePartnerUnitCatalog(input: DeletePartnerUnitCatalogRequest, options?: RpcOptions): UnaryCall<DeletePartnerUnitCatalogRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePartnerUnitCatalogRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminCreatePartnerUnitCatalog
     */
    adminCreatePartnerUnitCatalog(input: AdminCreatePartnerUnitCatalogRequest, options?: RpcOptions): UnaryCall<AdminCreatePartnerUnitCatalogRequest, CommonResult> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<AdminCreatePartnerUnitCatalogRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminUpdatePartnerUnitCatalog
     */
    adminUpdatePartnerUnitCatalog(input: AdminUpdatePartnerUnitCatalogRequest, options?: RpcOptions): UnaryCall<AdminUpdatePartnerUnitCatalogRequest, CommonResult> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<AdminUpdatePartnerUnitCatalogRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminDeletePartnerUnitCatalog
     */
    adminDeletePartnerUnitCatalog(input: DeletePartnerUnitCatalogRequest, options?: RpcOptions): UnaryCall<DeletePartnerUnitCatalogRequest, CommonResult> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePartnerUnitCatalogRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
