// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "partner_document_types_command.proto" (package "PartnerDocumentTypes", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PartnerDocumentTypesCommand } from "./partner_document_types_command";
import type { AdminUpdatePartnerDocumentTypesRequest } from "./partner_document_types_command";
import type { AdminCreatePartnerDocumentTypesRequest } from "./partner_document_types_command";
import type { DeletePartnerDocumentTypesRequest } from "./partner_document_types_command";
import type { UpdatePartnerDocumentTypesRequest } from "./partner_document_types_command";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { CreatePartnerDocumentTypesRequest } from "./partner_document_types_command";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service PartnerDocumentTypes.PartnerDocumentTypesCommand
 */
export interface IPartnerDocumentTypesCommandClient {
    /**
     * @generated from protobuf rpc: CreatePartnerDocumentTypes
     */
    createPartnerDocumentTypes(input: CreatePartnerDocumentTypesRequest, options?: RpcOptions): UnaryCall<CreatePartnerDocumentTypesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: UpdatePartnerDocumentTypes
     */
    updatePartnerDocumentTypes(input: UpdatePartnerDocumentTypesRequest, options?: RpcOptions): UnaryCall<UpdatePartnerDocumentTypesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: DeletePartnerDocumentTypes
     */
    deletePartnerDocumentTypes(input: DeletePartnerDocumentTypesRequest, options?: RpcOptions): UnaryCall<DeletePartnerDocumentTypesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminCreatePartnerDocumentTypes
     */
    adminCreatePartnerDocumentTypes(input: AdminCreatePartnerDocumentTypesRequest, options?: RpcOptions): UnaryCall<AdminCreatePartnerDocumentTypesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminUpdatePartnerDocumentTypes
     */
    adminUpdatePartnerDocumentTypes(input: AdminUpdatePartnerDocumentTypesRequest, options?: RpcOptions): UnaryCall<AdminUpdatePartnerDocumentTypesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminDeletePartnerDocumentTypes
     */
    adminDeletePartnerDocumentTypes(input: DeletePartnerDocumentTypesRequest, options?: RpcOptions): UnaryCall<DeletePartnerDocumentTypesRequest, CommonResult>;
}
/**
 * @generated from protobuf service PartnerDocumentTypes.PartnerDocumentTypesCommand
 */
export class PartnerDocumentTypesCommandClient implements IPartnerDocumentTypesCommandClient, ServiceInfo {
    typeName = PartnerDocumentTypesCommand.typeName;
    methods = PartnerDocumentTypesCommand.methods;
    options = PartnerDocumentTypesCommand.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreatePartnerDocumentTypes
     */
    createPartnerDocumentTypes(input: CreatePartnerDocumentTypesRequest, options?: RpcOptions): UnaryCall<CreatePartnerDocumentTypesRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePartnerDocumentTypesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePartnerDocumentTypes
     */
    updatePartnerDocumentTypes(input: UpdatePartnerDocumentTypesRequest, options?: RpcOptions): UnaryCall<UpdatePartnerDocumentTypesRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePartnerDocumentTypesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeletePartnerDocumentTypes
     */
    deletePartnerDocumentTypes(input: DeletePartnerDocumentTypesRequest, options?: RpcOptions): UnaryCall<DeletePartnerDocumentTypesRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePartnerDocumentTypesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminCreatePartnerDocumentTypes
     */
    adminCreatePartnerDocumentTypes(input: AdminCreatePartnerDocumentTypesRequest, options?: RpcOptions): UnaryCall<AdminCreatePartnerDocumentTypesRequest, CommonResult> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<AdminCreatePartnerDocumentTypesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminUpdatePartnerDocumentTypes
     */
    adminUpdatePartnerDocumentTypes(input: AdminUpdatePartnerDocumentTypesRequest, options?: RpcOptions): UnaryCall<AdminUpdatePartnerDocumentTypesRequest, CommonResult> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<AdminUpdatePartnerDocumentTypesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminDeletePartnerDocumentTypes
     */
    adminDeletePartnerDocumentTypes(input: DeletePartnerDocumentTypesRequest, options?: RpcOptions): UnaryCall<DeletePartnerDocumentTypesRequest, CommonResult> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePartnerDocumentTypesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
