// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "partner_profiles_command.proto" (package "PartnerProfiles", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { StringValue } from "../../Utils/google/protobuf/wrappers";
import { Int32Value } from "../../Utils/google/protobuf/wrappers";
/**
 * @generated from protobuf message PartnerProfiles.CreatePartnerProfilesRequest
 */
export interface CreatePartnerProfilesRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value InformationId = 1
     */
    informationId?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue PartnerBiography = 2
     */
    partnerBiography?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value WardId = 3
     */
    wardId?: Int32Value;
    /**
     * @generated from protobuf field: PartnerProfiles.PartnerServicesMessage PartnerServicesMessage = 4
     */
    partnerServicesMessage?: PartnerServicesMessage;
}
/**
 * @generated from protobuf message PartnerProfiles.UpdatePartnerProfilesRequest
 */
export interface UpdatePartnerProfilesRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value InformationId = 2
     */
    informationId?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue PartnerBiography = 3
     */
    partnerBiography?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value WardId = 4
     */
    wardId?: Int32Value;
    /**
     * @generated from protobuf field: PartnerProfiles.PartnerServicesMessage PartnerServicesMessage = 5
     */
    partnerServicesMessage?: PartnerServicesMessage;
}
/**
 * @generated from protobuf message PartnerProfiles.DeletePartnerProfilesRequest
 */
export interface DeletePartnerProfilesRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
}
/**
 * @generated from protobuf message PartnerProfiles.PartnerServicesMessage
 */
export interface PartnerServicesMessage {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value ServiceId = 1
     */
    serviceId?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue PartnerServiceYearsExp = 2
     */
    partnerServiceYearsExp?: StringValue;
}
/**
 * Admin
 *
 * @generated from protobuf message PartnerProfiles.AdminCreatePartnerProfilesRequest
 */
export interface AdminCreatePartnerProfilesRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value InformationId = 1
     */
    informationId?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue PartnerCode = 2
     */
    partnerCode?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value PartnerStatus = 3
     */
    partnerStatus?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue PartnerBiography = 4
     */
    partnerBiography?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value PartnerIsAvailable = 5
     */
    partnerIsAvailable?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value WardId = 6
     */
    wardId?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value IsActived = 7
     */
    isActived?: Int32Value;
}
/**
 * @generated from protobuf message PartnerProfiles.AdminUpdatePartnerProfilesRequest
 */
export interface AdminUpdatePartnerProfilesRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value InformationId = 2
     */
    informationId?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue PartnerCode = 3
     */
    partnerCode?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value PartnerStatus = 4
     */
    partnerStatus?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue PartnerBiography = 5
     */
    partnerBiography?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value PartnerIsAvailable = 6
     */
    partnerIsAvailable?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value WardId = 7
     */
    wardId?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value IsActived = 8
     */
    isActived?: Int32Value;
}
/**
 * @generated from protobuf message PartnerProfiles.AdminReviewPartnerProfileRequest
 */
export interface AdminReviewPartnerProfileRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value Status = 2
     */
    status?: Int32Value;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreatePartnerProfilesRequest$Type extends MessageType<CreatePartnerProfilesRequest> {
    constructor() {
        super("PartnerProfiles.CreatePartnerProfilesRequest", [
            { no: 1, name: "InformationId", kind: "message", jsonName: "InformationId", T: () => Int32Value },
            { no: 2, name: "PartnerBiography", kind: "message", jsonName: "PartnerBiography", T: () => StringValue },
            { no: 3, name: "WardId", kind: "message", jsonName: "WardId", T: () => Int32Value },
            { no: 4, name: "PartnerServicesMessage", kind: "message", jsonName: "PartnerServicesMessage", T: () => PartnerServicesMessage }
        ]);
    }
    create(value?: PartialMessage<CreatePartnerProfilesRequest>): CreatePartnerProfilesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreatePartnerProfilesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePartnerProfilesRequest): CreatePartnerProfilesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value InformationId */ 1:
                    message.informationId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.informationId);
                    break;
                case /* optional google.protobuf.StringValue PartnerBiography */ 2:
                    message.partnerBiography = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.partnerBiography);
                    break;
                case /* optional google.protobuf.Int32Value WardId */ 3:
                    message.wardId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.wardId);
                    break;
                case /* PartnerProfiles.PartnerServicesMessage PartnerServicesMessage */ 4:
                    message.partnerServicesMessage = PartnerServicesMessage.internalBinaryRead(reader, reader.uint32(), options, message.partnerServicesMessage);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePartnerProfilesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value InformationId = 1; */
        if (message.informationId)
            Int32Value.internalBinaryWrite(message.informationId, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue PartnerBiography = 2; */
        if (message.partnerBiography)
            StringValue.internalBinaryWrite(message.partnerBiography, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value WardId = 3; */
        if (message.wardId)
            Int32Value.internalBinaryWrite(message.wardId, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* PartnerProfiles.PartnerServicesMessage PartnerServicesMessage = 4; */
        if (message.partnerServicesMessage)
            PartnerServicesMessage.internalBinaryWrite(message.partnerServicesMessage, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerProfiles.CreatePartnerProfilesRequest
 */
export const CreatePartnerProfilesRequest = new CreatePartnerProfilesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatePartnerProfilesRequest$Type extends MessageType<UpdatePartnerProfilesRequest> {
    constructor() {
        super("PartnerProfiles.UpdatePartnerProfilesRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value },
            { no: 2, name: "InformationId", kind: "message", jsonName: "InformationId", T: () => Int32Value },
            { no: 3, name: "PartnerBiography", kind: "message", jsonName: "PartnerBiography", T: () => StringValue },
            { no: 4, name: "WardId", kind: "message", jsonName: "WardId", T: () => Int32Value },
            { no: 5, name: "PartnerServicesMessage", kind: "message", jsonName: "PartnerServicesMessage", T: () => PartnerServicesMessage }
        ]);
    }
    create(value?: PartialMessage<UpdatePartnerProfilesRequest>): UpdatePartnerProfilesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdatePartnerProfilesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdatePartnerProfilesRequest): UpdatePartnerProfilesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* optional google.protobuf.Int32Value InformationId */ 2:
                    message.informationId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.informationId);
                    break;
                case /* optional google.protobuf.StringValue PartnerBiography */ 3:
                    message.partnerBiography = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.partnerBiography);
                    break;
                case /* optional google.protobuf.Int32Value WardId */ 4:
                    message.wardId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.wardId);
                    break;
                case /* PartnerProfiles.PartnerServicesMessage PartnerServicesMessage */ 5:
                    message.partnerServicesMessage = PartnerServicesMessage.internalBinaryRead(reader, reader.uint32(), options, message.partnerServicesMessage);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdatePartnerProfilesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value InformationId = 2; */
        if (message.informationId)
            Int32Value.internalBinaryWrite(message.informationId, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue PartnerBiography = 3; */
        if (message.partnerBiography)
            StringValue.internalBinaryWrite(message.partnerBiography, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value WardId = 4; */
        if (message.wardId)
            Int32Value.internalBinaryWrite(message.wardId, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* PartnerProfiles.PartnerServicesMessage PartnerServicesMessage = 5; */
        if (message.partnerServicesMessage)
            PartnerServicesMessage.internalBinaryWrite(message.partnerServicesMessage, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerProfiles.UpdatePartnerProfilesRequest
 */
export const UpdatePartnerProfilesRequest = new UpdatePartnerProfilesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeletePartnerProfilesRequest$Type extends MessageType<DeletePartnerProfilesRequest> {
    constructor() {
        super("PartnerProfiles.DeletePartnerProfilesRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<DeletePartnerProfilesRequest>): DeletePartnerProfilesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DeletePartnerProfilesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeletePartnerProfilesRequest): DeletePartnerProfilesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeletePartnerProfilesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerProfiles.DeletePartnerProfilesRequest
 */
export const DeletePartnerProfilesRequest = new DeletePartnerProfilesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PartnerServicesMessage$Type extends MessageType<PartnerServicesMessage> {
    constructor() {
        super("PartnerProfiles.PartnerServicesMessage", [
            { no: 1, name: "ServiceId", kind: "message", jsonName: "ServiceId", T: () => Int32Value },
            { no: 2, name: "PartnerServiceYearsExp", kind: "message", jsonName: "PartnerServiceYearsExp", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<PartnerServicesMessage>): PartnerServicesMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<PartnerServicesMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PartnerServicesMessage): PartnerServicesMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value ServiceId */ 1:
                    message.serviceId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.serviceId);
                    break;
                case /* optional google.protobuf.StringValue PartnerServiceYearsExp */ 2:
                    message.partnerServiceYearsExp = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.partnerServiceYearsExp);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PartnerServicesMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value ServiceId = 1; */
        if (message.serviceId)
            Int32Value.internalBinaryWrite(message.serviceId, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue PartnerServiceYearsExp = 2; */
        if (message.partnerServiceYearsExp)
            StringValue.internalBinaryWrite(message.partnerServiceYearsExp, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerProfiles.PartnerServicesMessage
 */
export const PartnerServicesMessage = new PartnerServicesMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AdminCreatePartnerProfilesRequest$Type extends MessageType<AdminCreatePartnerProfilesRequest> {
    constructor() {
        super("PartnerProfiles.AdminCreatePartnerProfilesRequest", [
            { no: 1, name: "InformationId", kind: "message", jsonName: "InformationId", T: () => Int32Value },
            { no: 2, name: "PartnerCode", kind: "message", jsonName: "PartnerCode", T: () => StringValue },
            { no: 3, name: "PartnerStatus", kind: "message", jsonName: "PartnerStatus", T: () => Int32Value },
            { no: 4, name: "PartnerBiography", kind: "message", jsonName: "PartnerBiography", T: () => StringValue },
            { no: 5, name: "PartnerIsAvailable", kind: "message", jsonName: "PartnerIsAvailable", T: () => Int32Value },
            { no: 6, name: "WardId", kind: "message", jsonName: "WardId", T: () => Int32Value },
            { no: 7, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<AdminCreatePartnerProfilesRequest>): AdminCreatePartnerProfilesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AdminCreatePartnerProfilesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AdminCreatePartnerProfilesRequest): AdminCreatePartnerProfilesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value InformationId */ 1:
                    message.informationId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.informationId);
                    break;
                case /* optional google.protobuf.StringValue PartnerCode */ 2:
                    message.partnerCode = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.partnerCode);
                    break;
                case /* optional google.protobuf.Int32Value PartnerStatus */ 3:
                    message.partnerStatus = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.partnerStatus);
                    break;
                case /* optional google.protobuf.StringValue PartnerBiography */ 4:
                    message.partnerBiography = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.partnerBiography);
                    break;
                case /* optional google.protobuf.Int32Value PartnerIsAvailable */ 5:
                    message.partnerIsAvailable = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.partnerIsAvailable);
                    break;
                case /* optional google.protobuf.Int32Value WardId */ 6:
                    message.wardId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.wardId);
                    break;
                case /* optional google.protobuf.Int32Value IsActived */ 7:
                    message.isActived = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AdminCreatePartnerProfilesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value InformationId = 1; */
        if (message.informationId)
            Int32Value.internalBinaryWrite(message.informationId, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue PartnerCode = 2; */
        if (message.partnerCode)
            StringValue.internalBinaryWrite(message.partnerCode, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value PartnerStatus = 3; */
        if (message.partnerStatus)
            Int32Value.internalBinaryWrite(message.partnerStatus, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue PartnerBiography = 4; */
        if (message.partnerBiography)
            StringValue.internalBinaryWrite(message.partnerBiography, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value PartnerIsAvailable = 5; */
        if (message.partnerIsAvailable)
            Int32Value.internalBinaryWrite(message.partnerIsAvailable, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value WardId = 6; */
        if (message.wardId)
            Int32Value.internalBinaryWrite(message.wardId, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value IsActived = 7; */
        if (message.isActived)
            Int32Value.internalBinaryWrite(message.isActived, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerProfiles.AdminCreatePartnerProfilesRequest
 */
export const AdminCreatePartnerProfilesRequest = new AdminCreatePartnerProfilesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AdminUpdatePartnerProfilesRequest$Type extends MessageType<AdminUpdatePartnerProfilesRequest> {
    constructor() {
        super("PartnerProfiles.AdminUpdatePartnerProfilesRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value },
            { no: 2, name: "InformationId", kind: "message", jsonName: "InformationId", T: () => Int32Value },
            { no: 3, name: "PartnerCode", kind: "message", jsonName: "PartnerCode", T: () => StringValue },
            { no: 4, name: "PartnerStatus", kind: "message", jsonName: "PartnerStatus", T: () => Int32Value },
            { no: 5, name: "PartnerBiography", kind: "message", jsonName: "PartnerBiography", T: () => StringValue },
            { no: 6, name: "PartnerIsAvailable", kind: "message", jsonName: "PartnerIsAvailable", T: () => Int32Value },
            { no: 7, name: "WardId", kind: "message", jsonName: "WardId", T: () => Int32Value },
            { no: 8, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<AdminUpdatePartnerProfilesRequest>): AdminUpdatePartnerProfilesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AdminUpdatePartnerProfilesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AdminUpdatePartnerProfilesRequest): AdminUpdatePartnerProfilesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* optional google.protobuf.Int32Value InformationId */ 2:
                    message.informationId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.informationId);
                    break;
                case /* optional google.protobuf.StringValue PartnerCode */ 3:
                    message.partnerCode = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.partnerCode);
                    break;
                case /* optional google.protobuf.Int32Value PartnerStatus */ 4:
                    message.partnerStatus = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.partnerStatus);
                    break;
                case /* optional google.protobuf.StringValue PartnerBiography */ 5:
                    message.partnerBiography = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.partnerBiography);
                    break;
                case /* optional google.protobuf.Int32Value PartnerIsAvailable */ 6:
                    message.partnerIsAvailable = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.partnerIsAvailable);
                    break;
                case /* optional google.protobuf.Int32Value WardId */ 7:
                    message.wardId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.wardId);
                    break;
                case /* optional google.protobuf.Int32Value IsActived */ 8:
                    message.isActived = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AdminUpdatePartnerProfilesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value InformationId = 2; */
        if (message.informationId)
            Int32Value.internalBinaryWrite(message.informationId, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue PartnerCode = 3; */
        if (message.partnerCode)
            StringValue.internalBinaryWrite(message.partnerCode, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value PartnerStatus = 4; */
        if (message.partnerStatus)
            Int32Value.internalBinaryWrite(message.partnerStatus, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue PartnerBiography = 5; */
        if (message.partnerBiography)
            StringValue.internalBinaryWrite(message.partnerBiography, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value PartnerIsAvailable = 6; */
        if (message.partnerIsAvailable)
            Int32Value.internalBinaryWrite(message.partnerIsAvailable, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value WardId = 7; */
        if (message.wardId)
            Int32Value.internalBinaryWrite(message.wardId, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value IsActived = 8; */
        if (message.isActived)
            Int32Value.internalBinaryWrite(message.isActived, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerProfiles.AdminUpdatePartnerProfilesRequest
 */
export const AdminUpdatePartnerProfilesRequest = new AdminUpdatePartnerProfilesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AdminReviewPartnerProfileRequest$Type extends MessageType<AdminReviewPartnerProfileRequest> {
    constructor() {
        super("PartnerProfiles.AdminReviewPartnerProfileRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value },
            { no: 2, name: "Status", kind: "message", jsonName: "Status", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<AdminReviewPartnerProfileRequest>): AdminReviewPartnerProfileRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AdminReviewPartnerProfileRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AdminReviewPartnerProfileRequest): AdminReviewPartnerProfileRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* optional google.protobuf.Int32Value Status */ 2:
                    message.status = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.status);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AdminReviewPartnerProfileRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value Status = 2; */
        if (message.status)
            Int32Value.internalBinaryWrite(message.status, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerProfiles.AdminReviewPartnerProfileRequest
 */
export const AdminReviewPartnerProfileRequest = new AdminReviewPartnerProfileRequest$Type();
/**
 * @generated ServiceType for protobuf service PartnerProfiles.PartnerProfilesCommand
 */
export const PartnerProfilesCommand = new ServiceType("PartnerProfiles.PartnerProfilesCommand", [
    { name: "CreatePartnerProfiles", options: {}, I: CreatePartnerProfilesRequest, O: CommonResult },
    { name: "UpdatePartnerProfiles", options: {}, I: UpdatePartnerProfilesRequest, O: CommonResult },
    { name: "DeletePartnerProfiles", options: {}, I: DeletePartnerProfilesRequest, O: CommonResult },
    { name: "AdminCreatePartnerProfiles", options: {}, I: AdminCreatePartnerProfilesRequest, O: CommonResult },
    { name: "AdminUpdatePartnerProfiles", options: {}, I: AdminUpdatePartnerProfilesRequest, O: CommonResult },
    { name: "AdminDeletePartnerProfiles", options: {}, I: DeletePartnerProfilesRequest, O: CommonResult },
    { name: "AdminReviewPartnerProfile", options: {}, I: AdminReviewPartnerProfileRequest, O: CommonResult }
]);
