// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "partner_doc_field_configs_command.proto" (package "PartnerDocFieldConfigs", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PartnerDocFieldConfigsCommand } from "./partner_doc_field_configs_command";
import type { DeletePartnerDocFieldConfigsRequest } from "./partner_doc_field_configs_command";
import type { UpdatePartnerDocFieldConfigsRequest } from "./partner_doc_field_configs_command";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { CreatePartnerDocFieldConfigsRequest } from "./partner_doc_field_configs_command";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service PartnerDocFieldConfigs.PartnerDocFieldConfigsCommand
 */
export interface IPartnerDocFieldConfigsCommandClient {
    /**
     * @generated from protobuf rpc: CreatePartnerDocFieldConfigs
     */
    createPartnerDocFieldConfigs(input: CreatePartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<CreatePartnerDocFieldConfigsRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: UpdatePartnerDocFieldConfigs
     */
    updatePartnerDocFieldConfigs(input: UpdatePartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<UpdatePartnerDocFieldConfigsRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: DeletePartnerDocFieldConfigs
     */
    deletePartnerDocFieldConfigs(input: DeletePartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<DeletePartnerDocFieldConfigsRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminCreatePartnerDocFieldConfigs
     */
    adminCreatePartnerDocFieldConfigs(input: CreatePartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<CreatePartnerDocFieldConfigsRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminUpdatePartnerDocFieldConfigs
     */
    adminUpdatePartnerDocFieldConfigs(input: UpdatePartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<UpdatePartnerDocFieldConfigsRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminDeletePartnerDocFieldConfigs
     */
    adminDeletePartnerDocFieldConfigs(input: DeletePartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<DeletePartnerDocFieldConfigsRequest, CommonResult>;
}
/**
 * @generated from protobuf service PartnerDocFieldConfigs.PartnerDocFieldConfigsCommand
 */
export class PartnerDocFieldConfigsCommandClient implements IPartnerDocFieldConfigsCommandClient, ServiceInfo {
    typeName = PartnerDocFieldConfigsCommand.typeName;
    methods = PartnerDocFieldConfigsCommand.methods;
    options = PartnerDocFieldConfigsCommand.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreatePartnerDocFieldConfigs
     */
    createPartnerDocFieldConfigs(input: CreatePartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<CreatePartnerDocFieldConfigsRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePartnerDocFieldConfigsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePartnerDocFieldConfigs
     */
    updatePartnerDocFieldConfigs(input: UpdatePartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<UpdatePartnerDocFieldConfigsRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePartnerDocFieldConfigsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeletePartnerDocFieldConfigs
     */
    deletePartnerDocFieldConfigs(input: DeletePartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<DeletePartnerDocFieldConfigsRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePartnerDocFieldConfigsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminCreatePartnerDocFieldConfigs
     */
    adminCreatePartnerDocFieldConfigs(input: CreatePartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<CreatePartnerDocFieldConfigsRequest, CommonResult> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePartnerDocFieldConfigsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminUpdatePartnerDocFieldConfigs
     */
    adminUpdatePartnerDocFieldConfigs(input: UpdatePartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<UpdatePartnerDocFieldConfigsRequest, CommonResult> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePartnerDocFieldConfigsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminDeletePartnerDocFieldConfigs
     */
    adminDeletePartnerDocFieldConfigs(input: DeletePartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<DeletePartnerDocFieldConfigsRequest, CommonResult> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePartnerDocFieldConfigsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
