// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "partner_profiles_command.proto" (package "PartnerProfiles", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PartnerProfilesCommand } from "./partner_profiles_command";
import type { AdminReviewPartnerProfileRequest } from "./partner_profiles_command";
import type { AdminUpdatePartnerProfilesRequest } from "./partner_profiles_command";
import type { AdminCreatePartnerProfilesRequest } from "./partner_profiles_command";
import type { DeletePartnerProfilesRequest } from "./partner_profiles_command";
import type { UpdatePartnerProfilesRequest } from "./partner_profiles_command";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { CreatePartnerProfilesRequest } from "./partner_profiles_command";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service PartnerProfiles.PartnerProfilesCommand
 */
export interface IPartnerProfilesCommandClient {
    /**
     * @generated from protobuf rpc: CreatePartnerProfiles
     */
    createPartnerProfiles(input: CreatePartnerProfilesRequest, options?: RpcOptions): UnaryCall<CreatePartnerProfilesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: UpdatePartnerProfiles
     */
    updatePartnerProfiles(input: UpdatePartnerProfilesRequest, options?: RpcOptions): UnaryCall<UpdatePartnerProfilesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: DeletePartnerProfiles
     */
    deletePartnerProfiles(input: DeletePartnerProfilesRequest, options?: RpcOptions): UnaryCall<DeletePartnerProfilesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminCreatePartnerProfiles
     */
    adminCreatePartnerProfiles(input: AdminCreatePartnerProfilesRequest, options?: RpcOptions): UnaryCall<AdminCreatePartnerProfilesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminUpdatePartnerProfiles
     */
    adminUpdatePartnerProfiles(input: AdminUpdatePartnerProfilesRequest, options?: RpcOptions): UnaryCall<AdminUpdatePartnerProfilesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminDeletePartnerProfiles
     */
    adminDeletePartnerProfiles(input: DeletePartnerProfilesRequest, options?: RpcOptions): UnaryCall<DeletePartnerProfilesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminReviewPartnerProfile
     */
    adminReviewPartnerProfile(input: AdminReviewPartnerProfileRequest, options?: RpcOptions): UnaryCall<AdminReviewPartnerProfileRequest, CommonResult>;
}
/**
 * @generated from protobuf service PartnerProfiles.PartnerProfilesCommand
 */
export class PartnerProfilesCommandClient implements IPartnerProfilesCommandClient, ServiceInfo {
    typeName = PartnerProfilesCommand.typeName;
    methods = PartnerProfilesCommand.methods;
    options = PartnerProfilesCommand.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreatePartnerProfiles
     */
    createPartnerProfiles(input: CreatePartnerProfilesRequest, options?: RpcOptions): UnaryCall<CreatePartnerProfilesRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePartnerProfilesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePartnerProfiles
     */
    updatePartnerProfiles(input: UpdatePartnerProfilesRequest, options?: RpcOptions): UnaryCall<UpdatePartnerProfilesRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePartnerProfilesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeletePartnerProfiles
     */
    deletePartnerProfiles(input: DeletePartnerProfilesRequest, options?: RpcOptions): UnaryCall<DeletePartnerProfilesRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePartnerProfilesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminCreatePartnerProfiles
     */
    adminCreatePartnerProfiles(input: AdminCreatePartnerProfilesRequest, options?: RpcOptions): UnaryCall<AdminCreatePartnerProfilesRequest, CommonResult> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<AdminCreatePartnerProfilesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminUpdatePartnerProfiles
     */
    adminUpdatePartnerProfiles(input: AdminUpdatePartnerProfilesRequest, options?: RpcOptions): UnaryCall<AdminUpdatePartnerProfilesRequest, CommonResult> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<AdminUpdatePartnerProfilesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminDeletePartnerProfiles
     */
    adminDeletePartnerProfiles(input: DeletePartnerProfilesRequest, options?: RpcOptions): UnaryCall<DeletePartnerProfilesRequest, CommonResult> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePartnerProfilesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminReviewPartnerProfile
     */
    adminReviewPartnerProfile(input: AdminReviewPartnerProfileRequest, options?: RpcOptions): UnaryCall<AdminReviewPartnerProfileRequest, CommonResult> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<AdminReviewPartnerProfileRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
