// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "partner_service_pricing_command.proto" (package "PartnerServicePricing", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { NullListInt32 } from "../../Utils/common";
import { BoolValue } from "../../Utils/google/protobuf/wrappers";
import { DoubleValue } from "../../Utils/google/protobuf/wrappers";
import { StringValue } from "../../Utils/google/protobuf/wrappers";
import { Int32Value } from "../../Utils/google/protobuf/wrappers";
/**
 * Request and Response Messages
 *
 * @generated from protobuf message PartnerServicePricing.CreatePartnerServicePricingRequest
 */
export interface CreatePartnerServicePricingRequest {
    /**
     * @generated from protobuf field: google.protobuf.Int32Value PartnerSerId = 1
     */
    partnerSerId?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpCode = 2
     */
    spCode?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpName = 3
     */
    spName?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpDescription = 4
     */
    spDescription?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpPricingApplyDate = 5
     */
    spPricingApplyDate?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.DoubleValue SpPriceTotal = 6
     */
    spPriceTotal?: DoubleValue;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpUnitId = 7
     */
    spUnitId?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value IsActived = 8
     */
    isActived?: Int32Value;
}
/**
 * @generated from protobuf message PartnerServicePricing.UpdatePartnerServicePricingRequest
 */
export interface UpdatePartnerServicePricingRequest {
    /**
     * @generated from protobuf field: google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value PartnerSerId = 2
     */
    partnerSerId?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpCode = 3
     */
    spCode?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpName = 4
     */
    spName?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpDescription = 5
     */
    spDescription?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpPricingApplyDate = 6
     */
    spPricingApplyDate?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.DoubleValue SpPriceTotal = 7
     */
    spPriceTotal?: DoubleValue;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpUnitId = 8
     */
    spUnitId?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value IsActived = 9
     */
    isActived?: Int32Value;
}
/**
 * @generated from protobuf message PartnerServicePricing.DeletePartnerServicePricingRequest
 */
export interface DeletePartnerServicePricingRequest {
    /**
     * @generated from protobuf field: google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
}
/**
 * @generated from protobuf message PartnerServicePricing.CreatePartnerServicePricingMultiplesRequest
 */
export interface CreatePartnerServicePricingMultiplesRequest {
    /**
     * @generated from protobuf field: repeated PartnerServicePricing.CreatePartnerServicePricingRequest PartnerServicePricings = 1
     */
    partnerServicePricings: CreatePartnerServicePricingRequest[];
}
/**
 * @generated from protobuf message PartnerServicePricing.UpdatePartnerServicePricingMultiplesRequest
 */
export interface UpdatePartnerServicePricingMultiplesRequest {
    /**
     * @generated from protobuf field: repeated PartnerServicePricing.UpdatePartnerServicePricingRequest PartnerServicePricings = 1
     */
    partnerServicePricings: UpdatePartnerServicePricingRequest[];
}
/**
 * @generated from protobuf message PartnerServicePricing.AdminCreatePartnerServicePricingRequest
 */
export interface AdminCreatePartnerServicePricingRequest {
    /**
     * @generated from protobuf field: google.protobuf.Int32Value PartnerSerId = 1
     */
    partnerSerId?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpCode = 2
     */
    spCode?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpName = 3
     */
    spName?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpDescription = 4
     */
    spDescription?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpPricingApplyDate = 5
     */
    spPricingApplyDate?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpCreatedDate = 6
     */
    spCreatedDate?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpIpaddress = 7
     */
    spIpaddress?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpBrowser = 8
     */
    spBrowser?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.BoolValue SpType = 9
     */
    spType?: BoolValue;
    /**
     * @generated from protobuf field: google.protobuf.DoubleValue SpPriceTotal = 10
     */
    spPriceTotal?: DoubleValue;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpUnitId = 11
     */
    spUnitId?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpRejectedDate = 12
     */
    spRejectedDate?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpRejectedBy = 13
     */
    spRejectedBy?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpRejectedReason = 14
     */
    spRejectedReason?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpStatus = 15
     */
    spStatus?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value IsActived = 16
     */
    isActived?: Int32Value;
}
/**
 * @generated from protobuf message PartnerServicePricing.AdminUpdatePartnerServicePricingRequest
 */
export interface AdminUpdatePartnerServicePricingRequest {
    /**
     * @generated from protobuf field: google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value PartnerSerId = 2
     */
    partnerSerId?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpCode = 3
     */
    spCode?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpName = 4
     */
    spName?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpDescription = 5
     */
    spDescription?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpPricingApplyDate = 6
     */
    spPricingApplyDate?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpCreatedDate = 7
     */
    spCreatedDate?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpIpaddress = 8
     */
    spIpaddress?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpBrowser = 9
     */
    spBrowser?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.BoolValue SpType = 10
     */
    spType?: BoolValue;
    /**
     * @generated from protobuf field: google.protobuf.DoubleValue SpPriceTotal = 11
     */
    spPriceTotal?: DoubleValue;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpUnitId = 12
     */
    spUnitId?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpRejectedDate = 13
     */
    spRejectedDate?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpRejectedBy = 14
     */
    spRejectedBy?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpRejectedReason = 15
     */
    spRejectedReason?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value SpStatus = 16
     */
    spStatus?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value IsActived = 17
     */
    isActived?: Int32Value;
}
/**
 * @generated from protobuf message PartnerServicePricing.AdminApprovePartnerServicePricingRequest
 */
export interface AdminApprovePartnerServicePricingRequest {
    /**
     * @generated from protobuf field: google.protobuf.Int32Value PartnerId = 1
     */
    partnerId?: Int32Value;
    /**
     * @generated from protobuf field: NullListInt32 PartnerServicePricingIds = 2
     */
    partnerServicePricingIds?: NullListInt32;
}
/**
 * @generated from protobuf message PartnerServicePricing.AdminRefusePartnerServicePricingRequest
 */
export interface AdminRefusePartnerServicePricingRequest {
    /**
     * @generated from protobuf field: repeated PartnerServicePricing.RefusePartnerServicePricingRequest RefusePartnerServicePricings = 1
     */
    refusePartnerServicePricings: RefusePartnerServicePricingRequest[];
}
/**
 * @generated from protobuf message PartnerServicePricing.RefusePartnerServicePricingRequest
 */
export interface RefusePartnerServicePricingRequest {
    /**
     * @generated from protobuf field: google.protobuf.Int32Value PartnerServicePricingId = 1
     */
    partnerServicePricingId?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.StringValue SpRejectedReason = 2
     */
    spRejectedReason?: StringValue;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreatePartnerServicePricingRequest$Type extends MessageType<CreatePartnerServicePricingRequest> {
    constructor() {
        super("PartnerServicePricing.CreatePartnerServicePricingRequest", [
            { no: 1, name: "PartnerSerId", kind: "message", jsonName: "PartnerSerId", T: () => Int32Value },
            { no: 2, name: "SpCode", kind: "message", jsonName: "SpCode", T: () => StringValue },
            { no: 3, name: "SpName", kind: "message", jsonName: "SpName", T: () => StringValue },
            { no: 4, name: "SpDescription", kind: "message", jsonName: "SpDescription", T: () => StringValue },
            { no: 5, name: "SpPricingApplyDate", kind: "message", jsonName: "SpPricingApplyDate", T: () => Int32Value },
            { no: 6, name: "SpPriceTotal", kind: "message", jsonName: "SpPriceTotal", T: () => DoubleValue },
            { no: 7, name: "SpUnitId", kind: "message", jsonName: "SpUnitId", T: () => Int32Value },
            { no: 8, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<CreatePartnerServicePricingRequest>): CreatePartnerServicePricingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreatePartnerServicePricingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePartnerServicePricingRequest): CreatePartnerServicePricingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Int32Value PartnerSerId */ 1:
                    message.partnerSerId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.partnerSerId);
                    break;
                case /* google.protobuf.StringValue SpCode */ 2:
                    message.spCode = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spCode);
                    break;
                case /* google.protobuf.StringValue SpName */ 3:
                    message.spName = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spName);
                    break;
                case /* google.protobuf.StringValue SpDescription */ 4:
                    message.spDescription = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spDescription);
                    break;
                case /* google.protobuf.Int32Value SpPricingApplyDate */ 5:
                    message.spPricingApplyDate = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spPricingApplyDate);
                    break;
                case /* google.protobuf.DoubleValue SpPriceTotal */ 6:
                    message.spPriceTotal = DoubleValue.internalBinaryRead(reader, reader.uint32(), options, message.spPriceTotal);
                    break;
                case /* google.protobuf.Int32Value SpUnitId */ 7:
                    message.spUnitId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spUnitId);
                    break;
                case /* google.protobuf.Int32Value IsActived */ 8:
                    message.isActived = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePartnerServicePricingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Int32Value PartnerSerId = 1; */
        if (message.partnerSerId)
            Int32Value.internalBinaryWrite(message.partnerSerId, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpCode = 2; */
        if (message.spCode)
            StringValue.internalBinaryWrite(message.spCode, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpName = 3; */
        if (message.spName)
            StringValue.internalBinaryWrite(message.spName, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpDescription = 4; */
        if (message.spDescription)
            StringValue.internalBinaryWrite(message.spDescription, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpPricingApplyDate = 5; */
        if (message.spPricingApplyDate)
            Int32Value.internalBinaryWrite(message.spPricingApplyDate, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.DoubleValue SpPriceTotal = 6; */
        if (message.spPriceTotal)
            DoubleValue.internalBinaryWrite(message.spPriceTotal, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpUnitId = 7; */
        if (message.spUnitId)
            Int32Value.internalBinaryWrite(message.spUnitId, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value IsActived = 8; */
        if (message.isActived)
            Int32Value.internalBinaryWrite(message.isActived, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerServicePricing.CreatePartnerServicePricingRequest
 */
export const CreatePartnerServicePricingRequest = new CreatePartnerServicePricingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatePartnerServicePricingRequest$Type extends MessageType<UpdatePartnerServicePricingRequest> {
    constructor() {
        super("PartnerServicePricing.UpdatePartnerServicePricingRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value },
            { no: 2, name: "PartnerSerId", kind: "message", jsonName: "PartnerSerId", T: () => Int32Value },
            { no: 3, name: "SpCode", kind: "message", jsonName: "SpCode", T: () => StringValue },
            { no: 4, name: "SpName", kind: "message", jsonName: "SpName", T: () => StringValue },
            { no: 5, name: "SpDescription", kind: "message", jsonName: "SpDescription", T: () => StringValue },
            { no: 6, name: "SpPricingApplyDate", kind: "message", jsonName: "SpPricingApplyDate", T: () => Int32Value },
            { no: 7, name: "SpPriceTotal", kind: "message", jsonName: "SpPriceTotal", T: () => DoubleValue },
            { no: 8, name: "SpUnitId", kind: "message", jsonName: "SpUnitId", T: () => Int32Value },
            { no: 9, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<UpdatePartnerServicePricingRequest>): UpdatePartnerServicePricingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdatePartnerServicePricingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdatePartnerServicePricingRequest): UpdatePartnerServicePricingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* google.protobuf.Int32Value PartnerSerId */ 2:
                    message.partnerSerId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.partnerSerId);
                    break;
                case /* google.protobuf.StringValue SpCode */ 3:
                    message.spCode = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spCode);
                    break;
                case /* google.protobuf.StringValue SpName */ 4:
                    message.spName = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spName);
                    break;
                case /* google.protobuf.StringValue SpDescription */ 5:
                    message.spDescription = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spDescription);
                    break;
                case /* google.protobuf.Int32Value SpPricingApplyDate */ 6:
                    message.spPricingApplyDate = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spPricingApplyDate);
                    break;
                case /* google.protobuf.DoubleValue SpPriceTotal */ 7:
                    message.spPriceTotal = DoubleValue.internalBinaryRead(reader, reader.uint32(), options, message.spPriceTotal);
                    break;
                case /* google.protobuf.Int32Value SpUnitId */ 8:
                    message.spUnitId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spUnitId);
                    break;
                case /* google.protobuf.Int32Value IsActived */ 9:
                    message.isActived = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdatePartnerServicePricingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value PartnerSerId = 2; */
        if (message.partnerSerId)
            Int32Value.internalBinaryWrite(message.partnerSerId, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpCode = 3; */
        if (message.spCode)
            StringValue.internalBinaryWrite(message.spCode, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpName = 4; */
        if (message.spName)
            StringValue.internalBinaryWrite(message.spName, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpDescription = 5; */
        if (message.spDescription)
            StringValue.internalBinaryWrite(message.spDescription, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpPricingApplyDate = 6; */
        if (message.spPricingApplyDate)
            Int32Value.internalBinaryWrite(message.spPricingApplyDate, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.DoubleValue SpPriceTotal = 7; */
        if (message.spPriceTotal)
            DoubleValue.internalBinaryWrite(message.spPriceTotal, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpUnitId = 8; */
        if (message.spUnitId)
            Int32Value.internalBinaryWrite(message.spUnitId, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value IsActived = 9; */
        if (message.isActived)
            Int32Value.internalBinaryWrite(message.isActived, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerServicePricing.UpdatePartnerServicePricingRequest
 */
export const UpdatePartnerServicePricingRequest = new UpdatePartnerServicePricingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeletePartnerServicePricingRequest$Type extends MessageType<DeletePartnerServicePricingRequest> {
    constructor() {
        super("PartnerServicePricing.DeletePartnerServicePricingRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<DeletePartnerServicePricingRequest>): DeletePartnerServicePricingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DeletePartnerServicePricingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeletePartnerServicePricingRequest): DeletePartnerServicePricingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeletePartnerServicePricingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerServicePricing.DeletePartnerServicePricingRequest
 */
export const DeletePartnerServicePricingRequest = new DeletePartnerServicePricingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreatePartnerServicePricingMultiplesRequest$Type extends MessageType<CreatePartnerServicePricingMultiplesRequest> {
    constructor() {
        super("PartnerServicePricing.CreatePartnerServicePricingMultiplesRequest", [
            { no: 1, name: "PartnerServicePricings", kind: "message", jsonName: "PartnerServicePricings", repeat: 2 /*RepeatType.UNPACKED*/, T: () => CreatePartnerServicePricingRequest }
        ]);
    }
    create(value?: PartialMessage<CreatePartnerServicePricingMultiplesRequest>): CreatePartnerServicePricingMultiplesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.partnerServicePricings = [];
        if (value !== undefined)
            reflectionMergePartial<CreatePartnerServicePricingMultiplesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePartnerServicePricingMultiplesRequest): CreatePartnerServicePricingMultiplesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated PartnerServicePricing.CreatePartnerServicePricingRequest PartnerServicePricings */ 1:
                    message.partnerServicePricings.push(CreatePartnerServicePricingRequest.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePartnerServicePricingMultiplesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated PartnerServicePricing.CreatePartnerServicePricingRequest PartnerServicePricings = 1; */
        for (let i = 0; i < message.partnerServicePricings.length; i++)
            CreatePartnerServicePricingRequest.internalBinaryWrite(message.partnerServicePricings[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerServicePricing.CreatePartnerServicePricingMultiplesRequest
 */
export const CreatePartnerServicePricingMultiplesRequest = new CreatePartnerServicePricingMultiplesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatePartnerServicePricingMultiplesRequest$Type extends MessageType<UpdatePartnerServicePricingMultiplesRequest> {
    constructor() {
        super("PartnerServicePricing.UpdatePartnerServicePricingMultiplesRequest", [
            { no: 1, name: "PartnerServicePricings", kind: "message", jsonName: "PartnerServicePricings", repeat: 2 /*RepeatType.UNPACKED*/, T: () => UpdatePartnerServicePricingRequest }
        ]);
    }
    create(value?: PartialMessage<UpdatePartnerServicePricingMultiplesRequest>): UpdatePartnerServicePricingMultiplesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.partnerServicePricings = [];
        if (value !== undefined)
            reflectionMergePartial<UpdatePartnerServicePricingMultiplesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdatePartnerServicePricingMultiplesRequest): UpdatePartnerServicePricingMultiplesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated PartnerServicePricing.UpdatePartnerServicePricingRequest PartnerServicePricings */ 1:
                    message.partnerServicePricings.push(UpdatePartnerServicePricingRequest.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdatePartnerServicePricingMultiplesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated PartnerServicePricing.UpdatePartnerServicePricingRequest PartnerServicePricings = 1; */
        for (let i = 0; i < message.partnerServicePricings.length; i++)
            UpdatePartnerServicePricingRequest.internalBinaryWrite(message.partnerServicePricings[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerServicePricing.UpdatePartnerServicePricingMultiplesRequest
 */
export const UpdatePartnerServicePricingMultiplesRequest = new UpdatePartnerServicePricingMultiplesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AdminCreatePartnerServicePricingRequest$Type extends MessageType<AdminCreatePartnerServicePricingRequest> {
    constructor() {
        super("PartnerServicePricing.AdminCreatePartnerServicePricingRequest", [
            { no: 1, name: "PartnerSerId", kind: "message", jsonName: "PartnerSerId", T: () => Int32Value },
            { no: 2, name: "SpCode", kind: "message", jsonName: "SpCode", T: () => StringValue },
            { no: 3, name: "SpName", kind: "message", jsonName: "SpName", T: () => StringValue },
            { no: 4, name: "SpDescription", kind: "message", jsonName: "SpDescription", T: () => StringValue },
            { no: 5, name: "SpPricingApplyDate", kind: "message", jsonName: "SpPricingApplyDate", T: () => Int32Value },
            { no: 6, name: "SpCreatedDate", kind: "message", jsonName: "SpCreatedDate", T: () => Int32Value },
            { no: 7, name: "SpIpaddress", kind: "message", jsonName: "SpIpaddress", T: () => StringValue },
            { no: 8, name: "SpBrowser", kind: "message", jsonName: "SpBrowser", T: () => StringValue },
            { no: 9, name: "SpType", kind: "message", jsonName: "SpType", T: () => BoolValue },
            { no: 10, name: "SpPriceTotal", kind: "message", jsonName: "SpPriceTotal", T: () => DoubleValue },
            { no: 11, name: "SpUnitId", kind: "message", jsonName: "SpUnitId", T: () => Int32Value },
            { no: 12, name: "SpRejectedDate", kind: "message", jsonName: "SpRejectedDate", T: () => Int32Value },
            { no: 13, name: "SpRejectedBy", kind: "message", jsonName: "SpRejectedBy", T: () => Int32Value },
            { no: 14, name: "SpRejectedReason", kind: "message", jsonName: "SpRejectedReason", T: () => StringValue },
            { no: 15, name: "SpStatus", kind: "message", jsonName: "SpStatus", T: () => Int32Value },
            { no: 16, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<AdminCreatePartnerServicePricingRequest>): AdminCreatePartnerServicePricingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AdminCreatePartnerServicePricingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AdminCreatePartnerServicePricingRequest): AdminCreatePartnerServicePricingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Int32Value PartnerSerId */ 1:
                    message.partnerSerId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.partnerSerId);
                    break;
                case /* google.protobuf.StringValue SpCode */ 2:
                    message.spCode = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spCode);
                    break;
                case /* google.protobuf.StringValue SpName */ 3:
                    message.spName = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spName);
                    break;
                case /* google.protobuf.StringValue SpDescription */ 4:
                    message.spDescription = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spDescription);
                    break;
                case /* google.protobuf.Int32Value SpPricingApplyDate */ 5:
                    message.spPricingApplyDate = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spPricingApplyDate);
                    break;
                case /* google.protobuf.Int32Value SpCreatedDate */ 6:
                    message.spCreatedDate = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spCreatedDate);
                    break;
                case /* google.protobuf.StringValue SpIpaddress */ 7:
                    message.spIpaddress = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spIpaddress);
                    break;
                case /* google.protobuf.StringValue SpBrowser */ 8:
                    message.spBrowser = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spBrowser);
                    break;
                case /* google.protobuf.BoolValue SpType */ 9:
                    message.spType = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.spType);
                    break;
                case /* google.protobuf.DoubleValue SpPriceTotal */ 10:
                    message.spPriceTotal = DoubleValue.internalBinaryRead(reader, reader.uint32(), options, message.spPriceTotal);
                    break;
                case /* google.protobuf.Int32Value SpUnitId */ 11:
                    message.spUnitId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spUnitId);
                    break;
                case /* google.protobuf.Int32Value SpRejectedDate */ 12:
                    message.spRejectedDate = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spRejectedDate);
                    break;
                case /* google.protobuf.Int32Value SpRejectedBy */ 13:
                    message.spRejectedBy = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spRejectedBy);
                    break;
                case /* google.protobuf.StringValue SpRejectedReason */ 14:
                    message.spRejectedReason = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spRejectedReason);
                    break;
                case /* google.protobuf.Int32Value SpStatus */ 15:
                    message.spStatus = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spStatus);
                    break;
                case /* google.protobuf.Int32Value IsActived */ 16:
                    message.isActived = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AdminCreatePartnerServicePricingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Int32Value PartnerSerId = 1; */
        if (message.partnerSerId)
            Int32Value.internalBinaryWrite(message.partnerSerId, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpCode = 2; */
        if (message.spCode)
            StringValue.internalBinaryWrite(message.spCode, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpName = 3; */
        if (message.spName)
            StringValue.internalBinaryWrite(message.spName, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpDescription = 4; */
        if (message.spDescription)
            StringValue.internalBinaryWrite(message.spDescription, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpPricingApplyDate = 5; */
        if (message.spPricingApplyDate)
            Int32Value.internalBinaryWrite(message.spPricingApplyDate, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpCreatedDate = 6; */
        if (message.spCreatedDate)
            Int32Value.internalBinaryWrite(message.spCreatedDate, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpIpaddress = 7; */
        if (message.spIpaddress)
            StringValue.internalBinaryWrite(message.spIpaddress, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpBrowser = 8; */
        if (message.spBrowser)
            StringValue.internalBinaryWrite(message.spBrowser, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.BoolValue SpType = 9; */
        if (message.spType)
            BoolValue.internalBinaryWrite(message.spType, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.DoubleValue SpPriceTotal = 10; */
        if (message.spPriceTotal)
            DoubleValue.internalBinaryWrite(message.spPriceTotal, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpUnitId = 11; */
        if (message.spUnitId)
            Int32Value.internalBinaryWrite(message.spUnitId, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpRejectedDate = 12; */
        if (message.spRejectedDate)
            Int32Value.internalBinaryWrite(message.spRejectedDate, writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpRejectedBy = 13; */
        if (message.spRejectedBy)
            Int32Value.internalBinaryWrite(message.spRejectedBy, writer.tag(13, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpRejectedReason = 14; */
        if (message.spRejectedReason)
            StringValue.internalBinaryWrite(message.spRejectedReason, writer.tag(14, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpStatus = 15; */
        if (message.spStatus)
            Int32Value.internalBinaryWrite(message.spStatus, writer.tag(15, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value IsActived = 16; */
        if (message.isActived)
            Int32Value.internalBinaryWrite(message.isActived, writer.tag(16, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerServicePricing.AdminCreatePartnerServicePricingRequest
 */
export const AdminCreatePartnerServicePricingRequest = new AdminCreatePartnerServicePricingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AdminUpdatePartnerServicePricingRequest$Type extends MessageType<AdminUpdatePartnerServicePricingRequest> {
    constructor() {
        super("PartnerServicePricing.AdminUpdatePartnerServicePricingRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value },
            { no: 2, name: "PartnerSerId", kind: "message", jsonName: "PartnerSerId", T: () => Int32Value },
            { no: 3, name: "SpCode", kind: "message", jsonName: "SpCode", T: () => StringValue },
            { no: 4, name: "SpName", kind: "message", jsonName: "SpName", T: () => StringValue },
            { no: 5, name: "SpDescription", kind: "message", jsonName: "SpDescription", T: () => StringValue },
            { no: 6, name: "SpPricingApplyDate", kind: "message", jsonName: "SpPricingApplyDate", T: () => Int32Value },
            { no: 7, name: "SpCreatedDate", kind: "message", jsonName: "SpCreatedDate", T: () => Int32Value },
            { no: 8, name: "SpIpaddress", kind: "message", jsonName: "SpIpaddress", T: () => StringValue },
            { no: 9, name: "SpBrowser", kind: "message", jsonName: "SpBrowser", T: () => StringValue },
            { no: 10, name: "SpType", kind: "message", jsonName: "SpType", T: () => BoolValue },
            { no: 11, name: "SpPriceTotal", kind: "message", jsonName: "SpPriceTotal", T: () => DoubleValue },
            { no: 12, name: "SpUnitId", kind: "message", jsonName: "SpUnitId", T: () => Int32Value },
            { no: 13, name: "SpRejectedDate", kind: "message", jsonName: "SpRejectedDate", T: () => Int32Value },
            { no: 14, name: "SpRejectedBy", kind: "message", jsonName: "SpRejectedBy", T: () => Int32Value },
            { no: 15, name: "SpRejectedReason", kind: "message", jsonName: "SpRejectedReason", T: () => StringValue },
            { no: 16, name: "SpStatus", kind: "message", jsonName: "SpStatus", T: () => Int32Value },
            { no: 17, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<AdminUpdatePartnerServicePricingRequest>): AdminUpdatePartnerServicePricingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AdminUpdatePartnerServicePricingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AdminUpdatePartnerServicePricingRequest): AdminUpdatePartnerServicePricingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* google.protobuf.Int32Value PartnerSerId */ 2:
                    message.partnerSerId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.partnerSerId);
                    break;
                case /* google.protobuf.StringValue SpCode */ 3:
                    message.spCode = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spCode);
                    break;
                case /* google.protobuf.StringValue SpName */ 4:
                    message.spName = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spName);
                    break;
                case /* google.protobuf.StringValue SpDescription */ 5:
                    message.spDescription = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spDescription);
                    break;
                case /* google.protobuf.Int32Value SpPricingApplyDate */ 6:
                    message.spPricingApplyDate = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spPricingApplyDate);
                    break;
                case /* google.protobuf.Int32Value SpCreatedDate */ 7:
                    message.spCreatedDate = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spCreatedDate);
                    break;
                case /* google.protobuf.StringValue SpIpaddress */ 8:
                    message.spIpaddress = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spIpaddress);
                    break;
                case /* google.protobuf.StringValue SpBrowser */ 9:
                    message.spBrowser = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spBrowser);
                    break;
                case /* google.protobuf.BoolValue SpType */ 10:
                    message.spType = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.spType);
                    break;
                case /* google.protobuf.DoubleValue SpPriceTotal */ 11:
                    message.spPriceTotal = DoubleValue.internalBinaryRead(reader, reader.uint32(), options, message.spPriceTotal);
                    break;
                case /* google.protobuf.Int32Value SpUnitId */ 12:
                    message.spUnitId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spUnitId);
                    break;
                case /* google.protobuf.Int32Value SpRejectedDate */ 13:
                    message.spRejectedDate = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spRejectedDate);
                    break;
                case /* google.protobuf.Int32Value SpRejectedBy */ 14:
                    message.spRejectedBy = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spRejectedBy);
                    break;
                case /* google.protobuf.StringValue SpRejectedReason */ 15:
                    message.spRejectedReason = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spRejectedReason);
                    break;
                case /* google.protobuf.Int32Value SpStatus */ 16:
                    message.spStatus = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.spStatus);
                    break;
                case /* google.protobuf.Int32Value IsActived */ 17:
                    message.isActived = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AdminUpdatePartnerServicePricingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value PartnerSerId = 2; */
        if (message.partnerSerId)
            Int32Value.internalBinaryWrite(message.partnerSerId, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpCode = 3; */
        if (message.spCode)
            StringValue.internalBinaryWrite(message.spCode, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpName = 4; */
        if (message.spName)
            StringValue.internalBinaryWrite(message.spName, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpDescription = 5; */
        if (message.spDescription)
            StringValue.internalBinaryWrite(message.spDescription, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpPricingApplyDate = 6; */
        if (message.spPricingApplyDate)
            Int32Value.internalBinaryWrite(message.spPricingApplyDate, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpCreatedDate = 7; */
        if (message.spCreatedDate)
            Int32Value.internalBinaryWrite(message.spCreatedDate, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpIpaddress = 8; */
        if (message.spIpaddress)
            StringValue.internalBinaryWrite(message.spIpaddress, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpBrowser = 9; */
        if (message.spBrowser)
            StringValue.internalBinaryWrite(message.spBrowser, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.BoolValue SpType = 10; */
        if (message.spType)
            BoolValue.internalBinaryWrite(message.spType, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.DoubleValue SpPriceTotal = 11; */
        if (message.spPriceTotal)
            DoubleValue.internalBinaryWrite(message.spPriceTotal, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpUnitId = 12; */
        if (message.spUnitId)
            Int32Value.internalBinaryWrite(message.spUnitId, writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpRejectedDate = 13; */
        if (message.spRejectedDate)
            Int32Value.internalBinaryWrite(message.spRejectedDate, writer.tag(13, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpRejectedBy = 14; */
        if (message.spRejectedBy)
            Int32Value.internalBinaryWrite(message.spRejectedBy, writer.tag(14, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpRejectedReason = 15; */
        if (message.spRejectedReason)
            StringValue.internalBinaryWrite(message.spRejectedReason, writer.tag(15, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value SpStatus = 16; */
        if (message.spStatus)
            Int32Value.internalBinaryWrite(message.spStatus, writer.tag(16, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value IsActived = 17; */
        if (message.isActived)
            Int32Value.internalBinaryWrite(message.isActived, writer.tag(17, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerServicePricing.AdminUpdatePartnerServicePricingRequest
 */
export const AdminUpdatePartnerServicePricingRequest = new AdminUpdatePartnerServicePricingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AdminApprovePartnerServicePricingRequest$Type extends MessageType<AdminApprovePartnerServicePricingRequest> {
    constructor() {
        super("PartnerServicePricing.AdminApprovePartnerServicePricingRequest", [
            { no: 1, name: "PartnerId", kind: "message", jsonName: "PartnerId", T: () => Int32Value },
            { no: 2, name: "PartnerServicePricingIds", kind: "message", jsonName: "PartnerServicePricingIds", T: () => NullListInt32 }
        ]);
    }
    create(value?: PartialMessage<AdminApprovePartnerServicePricingRequest>): AdminApprovePartnerServicePricingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AdminApprovePartnerServicePricingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AdminApprovePartnerServicePricingRequest): AdminApprovePartnerServicePricingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Int32Value PartnerId */ 1:
                    message.partnerId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.partnerId);
                    break;
                case /* NullListInt32 PartnerServicePricingIds */ 2:
                    message.partnerServicePricingIds = NullListInt32.internalBinaryRead(reader, reader.uint32(), options, message.partnerServicePricingIds);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AdminApprovePartnerServicePricingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Int32Value PartnerId = 1; */
        if (message.partnerId)
            Int32Value.internalBinaryWrite(message.partnerId, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* NullListInt32 PartnerServicePricingIds = 2; */
        if (message.partnerServicePricingIds)
            NullListInt32.internalBinaryWrite(message.partnerServicePricingIds, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerServicePricing.AdminApprovePartnerServicePricingRequest
 */
export const AdminApprovePartnerServicePricingRequest = new AdminApprovePartnerServicePricingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AdminRefusePartnerServicePricingRequest$Type extends MessageType<AdminRefusePartnerServicePricingRequest> {
    constructor() {
        super("PartnerServicePricing.AdminRefusePartnerServicePricingRequest", [
            { no: 1, name: "RefusePartnerServicePricings", kind: "message", jsonName: "RefusePartnerServicePricings", repeat: 2 /*RepeatType.UNPACKED*/, T: () => RefusePartnerServicePricingRequest }
        ]);
    }
    create(value?: PartialMessage<AdminRefusePartnerServicePricingRequest>): AdminRefusePartnerServicePricingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.refusePartnerServicePricings = [];
        if (value !== undefined)
            reflectionMergePartial<AdminRefusePartnerServicePricingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AdminRefusePartnerServicePricingRequest): AdminRefusePartnerServicePricingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated PartnerServicePricing.RefusePartnerServicePricingRequest RefusePartnerServicePricings */ 1:
                    message.refusePartnerServicePricings.push(RefusePartnerServicePricingRequest.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AdminRefusePartnerServicePricingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated PartnerServicePricing.RefusePartnerServicePricingRequest RefusePartnerServicePricings = 1; */
        for (let i = 0; i < message.refusePartnerServicePricings.length; i++)
            RefusePartnerServicePricingRequest.internalBinaryWrite(message.refusePartnerServicePricings[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerServicePricing.AdminRefusePartnerServicePricingRequest
 */
export const AdminRefusePartnerServicePricingRequest = new AdminRefusePartnerServicePricingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RefusePartnerServicePricingRequest$Type extends MessageType<RefusePartnerServicePricingRequest> {
    constructor() {
        super("PartnerServicePricing.RefusePartnerServicePricingRequest", [
            { no: 1, name: "PartnerServicePricingId", kind: "message", jsonName: "PartnerServicePricingId", T: () => Int32Value },
            { no: 2, name: "SpRejectedReason", kind: "message", jsonName: "SpRejectedReason", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<RefusePartnerServicePricingRequest>): RefusePartnerServicePricingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<RefusePartnerServicePricingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RefusePartnerServicePricingRequest): RefusePartnerServicePricingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Int32Value PartnerServicePricingId */ 1:
                    message.partnerServicePricingId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.partnerServicePricingId);
                    break;
                case /* google.protobuf.StringValue SpRejectedReason */ 2:
                    message.spRejectedReason = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.spRejectedReason);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RefusePartnerServicePricingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Int32Value PartnerServicePricingId = 1; */
        if (message.partnerServicePricingId)
            Int32Value.internalBinaryWrite(message.partnerServicePricingId, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue SpRejectedReason = 2; */
        if (message.spRejectedReason)
            StringValue.internalBinaryWrite(message.spRejectedReason, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerServicePricing.RefusePartnerServicePricingRequest
 */
export const RefusePartnerServicePricingRequest = new RefusePartnerServicePricingRequest$Type();
/**
 * @generated ServiceType for protobuf service PartnerServicePricing.PartnerServicePricingCommand
 */
export const PartnerServicePricingCommand = new ServiceType("PartnerServicePricing.PartnerServicePricingCommand", [
    { name: "CreatePartnerServicePricing", options: {}, I: CreatePartnerServicePricingRequest, O: CommonResult },
    { name: "UpdatePartnerServicePricing", options: {}, I: UpdatePartnerServicePricingRequest, O: CommonResult },
    { name: "DeletePartnerServicePricing", options: {}, I: DeletePartnerServicePricingRequest, O: CommonResult },
    { name: "CreatePartnerServicePricingMultiples", options: {}, I: CreatePartnerServicePricingMultiplesRequest, O: CommonResult },
    { name: "UpdatePartnerServicePricingMultiples", options: {}, I: UpdatePartnerServicePricingMultiplesRequest, O: CommonResult },
    { name: "AdminCreatePartnerServicePricing", options: {}, I: AdminCreatePartnerServicePricingRequest, O: CommonResult },
    { name: "AdminUpdatePartnerServicePricing", options: {}, I: AdminUpdatePartnerServicePricingRequest, O: CommonResult },
    { name: "AdminDeletePartnerServicePricing", options: {}, I: DeletePartnerServicePricingRequest, O: CommonResult },
    { name: "AdminApprovePartnerServicePricing", options: {}, I: AdminApprovePartnerServicePricingRequest, O: CommonResult },
    { name: "AdminRefusePartnerServicePricing", options: {}, I: AdminRefusePartnerServicePricingRequest, O: CommonResult }
]);
