// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "partner_doc_field_values_command.proto" (package "PartnerDocFieldValues", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { StringValue } from "../../Utils/google/protobuf/wrappers";
import { Int32Value } from "../../Utils/google/protobuf/wrappers";
/**
 * @generated from protobuf message PartnerDocFieldValues.CreatePartnerDocFieldValuesRequest
 */
export interface CreatePartnerDocFieldValuesRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value PartnerDocId = 1
     */
    partnerDocId?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value FieldConfigId = 2
     */
    fieldConfigId?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue FieldValueText = 3
     */
    fieldValueText?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value IsActived = 4
     */
    isActived?: Int32Value;
}
/**
 * @generated from protobuf message PartnerDocFieldValues.UpdatePartnerDocFieldValuesRequest
 */
export interface UpdatePartnerDocFieldValuesRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value PartnerDocId = 2
     */
    partnerDocId?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value FieldConfigId = 3
     */
    fieldConfigId?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue FieldValueText = 4
     */
    fieldValueText?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value IsActived = 5
     */
    isActived?: Int32Value;
}
/**
 * @generated from protobuf message PartnerDocFieldValues.DeletePartnerDocFieldValuesRequest
 */
export interface DeletePartnerDocFieldValuesRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreatePartnerDocFieldValuesRequest$Type extends MessageType<CreatePartnerDocFieldValuesRequest> {
    constructor() {
        super("PartnerDocFieldValues.CreatePartnerDocFieldValuesRequest", [
            { no: 1, name: "PartnerDocId", kind: "message", jsonName: "PartnerDocId", T: () => Int32Value },
            { no: 2, name: "FieldConfigId", kind: "message", jsonName: "FieldConfigId", T: () => Int32Value },
            { no: 3, name: "FieldValueText", kind: "message", jsonName: "FieldValueText", T: () => StringValue },
            { no: 4, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<CreatePartnerDocFieldValuesRequest>): CreatePartnerDocFieldValuesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreatePartnerDocFieldValuesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePartnerDocFieldValuesRequest): CreatePartnerDocFieldValuesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value PartnerDocId */ 1:
                    message.partnerDocId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.partnerDocId);
                    break;
                case /* optional google.protobuf.Int32Value FieldConfigId */ 2:
                    message.fieldConfigId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.fieldConfigId);
                    break;
                case /* optional google.protobuf.StringValue FieldValueText */ 3:
                    message.fieldValueText = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.fieldValueText);
                    break;
                case /* optional google.protobuf.Int32Value IsActived */ 4:
                    message.isActived = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePartnerDocFieldValuesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value PartnerDocId = 1; */
        if (message.partnerDocId)
            Int32Value.internalBinaryWrite(message.partnerDocId, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value FieldConfigId = 2; */
        if (message.fieldConfigId)
            Int32Value.internalBinaryWrite(message.fieldConfigId, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue FieldValueText = 3; */
        if (message.fieldValueText)
            StringValue.internalBinaryWrite(message.fieldValueText, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value IsActived = 4; */
        if (message.isActived)
            Int32Value.internalBinaryWrite(message.isActived, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerDocFieldValues.CreatePartnerDocFieldValuesRequest
 */
export const CreatePartnerDocFieldValuesRequest = new CreatePartnerDocFieldValuesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatePartnerDocFieldValuesRequest$Type extends MessageType<UpdatePartnerDocFieldValuesRequest> {
    constructor() {
        super("PartnerDocFieldValues.UpdatePartnerDocFieldValuesRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value },
            { no: 2, name: "PartnerDocId", kind: "message", jsonName: "PartnerDocId", T: () => Int32Value },
            { no: 3, name: "FieldConfigId", kind: "message", jsonName: "FieldConfigId", T: () => Int32Value },
            { no: 4, name: "FieldValueText", kind: "message", jsonName: "FieldValueText", T: () => StringValue },
            { no: 5, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<UpdatePartnerDocFieldValuesRequest>): UpdatePartnerDocFieldValuesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdatePartnerDocFieldValuesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdatePartnerDocFieldValuesRequest): UpdatePartnerDocFieldValuesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* optional google.protobuf.Int32Value PartnerDocId */ 2:
                    message.partnerDocId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.partnerDocId);
                    break;
                case /* optional google.protobuf.Int32Value FieldConfigId */ 3:
                    message.fieldConfigId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.fieldConfigId);
                    break;
                case /* optional google.protobuf.StringValue FieldValueText */ 4:
                    message.fieldValueText = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.fieldValueText);
                    break;
                case /* optional google.protobuf.Int32Value IsActived */ 5:
                    message.isActived = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdatePartnerDocFieldValuesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value PartnerDocId = 2; */
        if (message.partnerDocId)
            Int32Value.internalBinaryWrite(message.partnerDocId, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value FieldConfigId = 3; */
        if (message.fieldConfigId)
            Int32Value.internalBinaryWrite(message.fieldConfigId, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue FieldValueText = 4; */
        if (message.fieldValueText)
            StringValue.internalBinaryWrite(message.fieldValueText, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value IsActived = 5; */
        if (message.isActived)
            Int32Value.internalBinaryWrite(message.isActived, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerDocFieldValues.UpdatePartnerDocFieldValuesRequest
 */
export const UpdatePartnerDocFieldValuesRequest = new UpdatePartnerDocFieldValuesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeletePartnerDocFieldValuesRequest$Type extends MessageType<DeletePartnerDocFieldValuesRequest> {
    constructor() {
        super("PartnerDocFieldValues.DeletePartnerDocFieldValuesRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<DeletePartnerDocFieldValuesRequest>): DeletePartnerDocFieldValuesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DeletePartnerDocFieldValuesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeletePartnerDocFieldValuesRequest): DeletePartnerDocFieldValuesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeletePartnerDocFieldValuesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerDocFieldValues.DeletePartnerDocFieldValuesRequest
 */
export const DeletePartnerDocFieldValuesRequest = new DeletePartnerDocFieldValuesRequest$Type();
/**
 * @generated ServiceType for protobuf service PartnerDocFieldValues.PartnerDocFieldValuesCommand
 */
export const PartnerDocFieldValuesCommand = new ServiceType("PartnerDocFieldValues.PartnerDocFieldValuesCommand", [
    { name: "CreatePartnerDocFieldValues", options: {}, I: CreatePartnerDocFieldValuesRequest, O: CommonResult },
    { name: "UpdatePartnerDocFieldValues", options: {}, I: UpdatePartnerDocFieldValuesRequest, O: CommonResult },
    { name: "DeletePartnerDocFieldValues", options: {}, I: DeletePartnerDocFieldValuesRequest, O: CommonResult },
    { name: "AdminCreatePartnerDocFieldValues", options: {}, I: CreatePartnerDocFieldValuesRequest, O: CommonResult },
    { name: "AdminUpdatePartnerDocFieldValues", options: {}, I: UpdatePartnerDocFieldValuesRequest, O: CommonResult },
    { name: "AdminDeletePartnerDocFieldValues", options: {}, I: DeletePartnerDocFieldValuesRequest, O: CommonResult }
]);
