// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "user_address_command.proto" (package "UserAddress", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { UserAddressCommand } from "./user_address_command";
import type { DeleteUserAddressRequest } from "./user_address_command";
import type { UpdateUserAddressRequest } from "./user_address_command";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { CreateUserAddressRequest } from "./user_address_command";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service UserAddress.UserAddressCommand
 */
export interface IUserAddressCommandClient {
    /**
     * @generated from protobuf rpc: CreateUserAddress
     */
    createUserAddress(input: CreateUserAddressRequest, options?: RpcOptions): UnaryCall<CreateUserAddressRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: UpdateUserAddress
     */
    updateUserAddress(input: UpdateUserAddressRequest, options?: RpcOptions): UnaryCall<UpdateUserAddressRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: DeleteUserAddress
     */
    deleteUserAddress(input: DeleteUserAddressRequest, options?: RpcOptions): UnaryCall<DeleteUserAddressRequest, CommonResult>;
}
/**
 * @generated from protobuf service UserAddress.UserAddressCommand
 */
export class UserAddressCommandClient implements IUserAddressCommandClient, ServiceInfo {
    typeName = UserAddressCommand.typeName;
    methods = UserAddressCommand.methods;
    options = UserAddressCommand.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateUserAddress
     */
    createUserAddress(input: CreateUserAddressRequest, options?: RpcOptions): UnaryCall<CreateUserAddressRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateUserAddressRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateUserAddress
     */
    updateUserAddress(input: UpdateUserAddressRequest, options?: RpcOptions): UnaryCall<UpdateUserAddressRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateUserAddressRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteUserAddress
     */
    deleteUserAddress(input: DeleteUserAddressRequest, options?: RpcOptions): UnaryCall<DeleteUserAddressRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteUserAddressRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
