// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "user_auth_command.proto" (package "UserAuth", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { BoolValue } from "../../Utils/google/protobuf/wrappers";
import { StringValue } from "../../Utils/google/protobuf/wrappers";
/**
 * @generated from protobuf message UserAuth.LoginRequest
 */
export interface LoginRequest {
    /**
     * @generated from protobuf field: google.protobuf.StringValue Tel = 1
     */
    tel?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue Password = 2
     */
    password?: StringValue;
}
/**
 * @generated from protobuf message UserAuth.LogoutRequest
 */
export interface LogoutRequest {
}
/**
 * @generated from protobuf message UserAuth.RefreshTokenRequest
 */
export interface RefreshTokenRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue RefreshToken = 1
     */
    refreshToken?: StringValue;
}
/**
 * @generated from protobuf message UserAuth.RegisterRequest
 */
export interface RegisterRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Tel = 1
     */
    tel?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Password = 2
     */
    password?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.BoolValue Type = 3
     */
    type?: BoolValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue FirstName = 4
     */
    firstName?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue LastName = 5
     */
    lastName?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Email = 6
     */
    email?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue SendOTPMethod = 7
     */
    sendOTPMethod?: StringValue; // Currently support: EMAIL. Future support: SMS
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue MailLanguage = 8
     */
    mailLanguage?: StringValue; // Currently support: VN (default), EN
}
/**
 * @generated from protobuf message UserAuth.ActivateAccountRequest
 */
export interface ActivateAccountRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Tel = 1
     */
    tel?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue OTP = 2
     */
    oTP?: StringValue;
}
/**
 * @generated from protobuf message UserAuth.VerifyOTPRequest
 */
export interface VerifyOTPRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Tel = 1
     */
    tel?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue OTP = 2
     */
    oTP?: StringValue;
}
/**
 * @generated from protobuf message UserAuth.ResetPasswordRequest
 */
export interface ResetPasswordRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Tel = 1
     */
    tel?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Method = 2
     */
    method?: StringValue; // Currently support: EMAIL. Future support: SMS
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue OTP = 3
     */
    oTP?: StringValue; // Need OTP send before to verify reset request is valid
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue MailLanguage = 4
     */
    mailLanguage?: StringValue; // Currently support: VN (default), EN
}
/**
 * @generated from protobuf message UserAuth.ReSendOTPRequest
 */
export interface ReSendOTPRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Tel = 1
     */
    tel?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Case = 2
     */
    case?: StringValue; // Use for chose appropriate mail content and subject for each case. Currently support: DEFAULT (default), ACTIVATE_ACCOUNT, RESET_PASSWORD
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Method = 3
     */
    method?: StringValue; // Currently support: EMAIL. Future support: SMS
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue MailLanguage = 4
     */
    mailLanguage?: StringValue; // Currently support: VN (default), EN
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Email = 5
     */
    email?: StringValue;
}
/**
 * @generated from protobuf message UserAuth.GetSessionRequest
 */
export interface GetSessionRequest {
}
// @generated message type with reflection information, may provide speed optimized methods
class LoginRequest$Type extends MessageType<LoginRequest> {
    constructor() {
        super("UserAuth.LoginRequest", [
            { no: 1, name: "Tel", kind: "message", jsonName: "Tel", T: () => StringValue },
            { no: 2, name: "Password", kind: "message", jsonName: "Password", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<LoginRequest>): LoginRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<LoginRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LoginRequest): LoginRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.StringValue Tel */ 1:
                    message.tel = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.tel);
                    break;
                case /* google.protobuf.StringValue Password */ 2:
                    message.password = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.password);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LoginRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.StringValue Tel = 1; */
        if (message.tel)
            StringValue.internalBinaryWrite(message.tel, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue Password = 2; */
        if (message.password)
            StringValue.internalBinaryWrite(message.password, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserAuth.LoginRequest
 */
export const LoginRequest = new LoginRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LogoutRequest$Type extends MessageType<LogoutRequest> {
    constructor() {
        super("UserAuth.LogoutRequest", []);
    }
    create(value?: PartialMessage<LogoutRequest>): LogoutRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<LogoutRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LogoutRequest): LogoutRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LogoutRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserAuth.LogoutRequest
 */
export const LogoutRequest = new LogoutRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RefreshTokenRequest$Type extends MessageType<RefreshTokenRequest> {
    constructor() {
        super("UserAuth.RefreshTokenRequest", [
            { no: 1, name: "RefreshToken", kind: "message", jsonName: "RefreshToken", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<RefreshTokenRequest>): RefreshTokenRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<RefreshTokenRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RefreshTokenRequest): RefreshTokenRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue RefreshToken */ 1:
                    message.refreshToken = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.refreshToken);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RefreshTokenRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue RefreshToken = 1; */
        if (message.refreshToken)
            StringValue.internalBinaryWrite(message.refreshToken, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserAuth.RefreshTokenRequest
 */
export const RefreshTokenRequest = new RefreshTokenRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterRequest$Type extends MessageType<RegisterRequest> {
    constructor() {
        super("UserAuth.RegisterRequest", [
            { no: 1, name: "Tel", kind: "message", jsonName: "Tel", T: () => StringValue },
            { no: 2, name: "Password", kind: "message", jsonName: "Password", T: () => StringValue },
            { no: 3, name: "Type", kind: "message", jsonName: "Type", T: () => BoolValue },
            { no: 4, name: "FirstName", kind: "message", jsonName: "FirstName", T: () => StringValue },
            { no: 5, name: "LastName", kind: "message", jsonName: "LastName", T: () => StringValue },
            { no: 6, name: "Email", kind: "message", jsonName: "Email", T: () => StringValue },
            { no: 7, name: "SendOTPMethod", kind: "message", jsonName: "SendOTPMethod", T: () => StringValue },
            { no: 8, name: "MailLanguage", kind: "message", jsonName: "MailLanguage", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<RegisterRequest>): RegisterRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<RegisterRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterRequest): RegisterRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Tel */ 1:
                    message.tel = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.tel);
                    break;
                case /* optional google.protobuf.StringValue Password */ 2:
                    message.password = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.password);
                    break;
                case /* optional google.protobuf.BoolValue Type */ 3:
                    message.type = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.type);
                    break;
                case /* optional google.protobuf.StringValue FirstName */ 4:
                    message.firstName = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.firstName);
                    break;
                case /* optional google.protobuf.StringValue LastName */ 5:
                    message.lastName = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.lastName);
                    break;
                case /* optional google.protobuf.StringValue Email */ 6:
                    message.email = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.email);
                    break;
                case /* optional google.protobuf.StringValue SendOTPMethod */ 7:
                    message.sendOTPMethod = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.sendOTPMethod);
                    break;
                case /* optional google.protobuf.StringValue MailLanguage */ 8:
                    message.mailLanguage = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.mailLanguage);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Tel = 1; */
        if (message.tel)
            StringValue.internalBinaryWrite(message.tel, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue Password = 2; */
        if (message.password)
            StringValue.internalBinaryWrite(message.password, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.BoolValue Type = 3; */
        if (message.type)
            BoolValue.internalBinaryWrite(message.type, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue FirstName = 4; */
        if (message.firstName)
            StringValue.internalBinaryWrite(message.firstName, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue LastName = 5; */
        if (message.lastName)
            StringValue.internalBinaryWrite(message.lastName, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue Email = 6; */
        if (message.email)
            StringValue.internalBinaryWrite(message.email, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue SendOTPMethod = 7; */
        if (message.sendOTPMethod)
            StringValue.internalBinaryWrite(message.sendOTPMethod, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue MailLanguage = 8; */
        if (message.mailLanguage)
            StringValue.internalBinaryWrite(message.mailLanguage, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserAuth.RegisterRequest
 */
export const RegisterRequest = new RegisterRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ActivateAccountRequest$Type extends MessageType<ActivateAccountRequest> {
    constructor() {
        super("UserAuth.ActivateAccountRequest", [
            { no: 1, name: "Tel", kind: "message", jsonName: "Tel", T: () => StringValue },
            { no: 2, name: "OTP", kind: "message", jsonName: "OTP", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<ActivateAccountRequest>): ActivateAccountRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ActivateAccountRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ActivateAccountRequest): ActivateAccountRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Tel */ 1:
                    message.tel = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.tel);
                    break;
                case /* optional google.protobuf.StringValue OTP */ 2:
                    message.oTP = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.oTP);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ActivateAccountRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Tel = 1; */
        if (message.tel)
            StringValue.internalBinaryWrite(message.tel, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue OTP = 2; */
        if (message.oTP)
            StringValue.internalBinaryWrite(message.oTP, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserAuth.ActivateAccountRequest
 */
export const ActivateAccountRequest = new ActivateAccountRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VerifyOTPRequest$Type extends MessageType<VerifyOTPRequest> {
    constructor() {
        super("UserAuth.VerifyOTPRequest", [
            { no: 1, name: "Tel", kind: "message", jsonName: "Tel", T: () => StringValue },
            { no: 2, name: "OTP", kind: "message", jsonName: "OTP", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<VerifyOTPRequest>): VerifyOTPRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<VerifyOTPRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VerifyOTPRequest): VerifyOTPRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Tel */ 1:
                    message.tel = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.tel);
                    break;
                case /* optional google.protobuf.StringValue OTP */ 2:
                    message.oTP = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.oTP);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: VerifyOTPRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Tel = 1; */
        if (message.tel)
            StringValue.internalBinaryWrite(message.tel, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue OTP = 2; */
        if (message.oTP)
            StringValue.internalBinaryWrite(message.oTP, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserAuth.VerifyOTPRequest
 */
export const VerifyOTPRequest = new VerifyOTPRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ResetPasswordRequest$Type extends MessageType<ResetPasswordRequest> {
    constructor() {
        super("UserAuth.ResetPasswordRequest", [
            { no: 1, name: "Tel", kind: "message", jsonName: "Tel", T: () => StringValue },
            { no: 2, name: "Method", kind: "message", jsonName: "Method", T: () => StringValue },
            { no: 3, name: "OTP", kind: "message", jsonName: "OTP", T: () => StringValue },
            { no: 4, name: "MailLanguage", kind: "message", jsonName: "MailLanguage", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<ResetPasswordRequest>): ResetPasswordRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ResetPasswordRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ResetPasswordRequest): ResetPasswordRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Tel */ 1:
                    message.tel = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.tel);
                    break;
                case /* optional google.protobuf.StringValue Method */ 2:
                    message.method = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.method);
                    break;
                case /* optional google.protobuf.StringValue OTP */ 3:
                    message.oTP = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.oTP);
                    break;
                case /* optional google.protobuf.StringValue MailLanguage */ 4:
                    message.mailLanguage = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.mailLanguage);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ResetPasswordRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Tel = 1; */
        if (message.tel)
            StringValue.internalBinaryWrite(message.tel, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue Method = 2; */
        if (message.method)
            StringValue.internalBinaryWrite(message.method, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue OTP = 3; */
        if (message.oTP)
            StringValue.internalBinaryWrite(message.oTP, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue MailLanguage = 4; */
        if (message.mailLanguage)
            StringValue.internalBinaryWrite(message.mailLanguage, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserAuth.ResetPasswordRequest
 */
export const ResetPasswordRequest = new ResetPasswordRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReSendOTPRequest$Type extends MessageType<ReSendOTPRequest> {
    constructor() {
        super("UserAuth.ReSendOTPRequest", [
            { no: 1, name: "Tel", kind: "message", jsonName: "Tel", T: () => StringValue },
            { no: 2, name: "Case", kind: "message", jsonName: "Case", T: () => StringValue },
            { no: 3, name: "Method", kind: "message", jsonName: "Method", T: () => StringValue },
            { no: 4, name: "MailLanguage", kind: "message", jsonName: "MailLanguage", T: () => StringValue },
            { no: 5, name: "Email", kind: "message", jsonName: "Email", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<ReSendOTPRequest>): ReSendOTPRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ReSendOTPRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReSendOTPRequest): ReSendOTPRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Tel */ 1:
                    message.tel = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.tel);
                    break;
                case /* optional google.protobuf.StringValue Case */ 2:
                    message.case = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.case);
                    break;
                case /* optional google.protobuf.StringValue Method */ 3:
                    message.method = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.method);
                    break;
                case /* optional google.protobuf.StringValue MailLanguage */ 4:
                    message.mailLanguage = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.mailLanguage);
                    break;
                case /* optional google.protobuf.StringValue Email */ 5:
                    message.email = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.email);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReSendOTPRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Tel = 1; */
        if (message.tel)
            StringValue.internalBinaryWrite(message.tel, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue Case = 2; */
        if (message.case)
            StringValue.internalBinaryWrite(message.case, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue Method = 3; */
        if (message.method)
            StringValue.internalBinaryWrite(message.method, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue MailLanguage = 4; */
        if (message.mailLanguage)
            StringValue.internalBinaryWrite(message.mailLanguage, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue Email = 5; */
        if (message.email)
            StringValue.internalBinaryWrite(message.email, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserAuth.ReSendOTPRequest
 */
export const ReSendOTPRequest = new ReSendOTPRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSessionRequest$Type extends MessageType<GetSessionRequest> {
    constructor() {
        super("UserAuth.GetSessionRequest", []);
    }
    create(value?: PartialMessage<GetSessionRequest>): GetSessionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetSessionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetSessionRequest): GetSessionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetSessionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserAuth.GetSessionRequest
 */
export const GetSessionRequest = new GetSessionRequest$Type();
/**
 * @generated ServiceType for protobuf service UserAuth.UserAuthCommand
 */
export const UserAuthCommand = new ServiceType("UserAuth.UserAuthCommand", [
    { name: "Login", options: {}, I: LoginRequest, O: CommonResult },
    { name: "Logout", options: {}, I: LogoutRequest, O: CommonResult },
    { name: "RefreshToken", options: {}, I: RefreshTokenRequest, O: CommonResult },
    { name: "Register", options: {}, I: RegisterRequest, O: CommonResult },
    { name: "ActivateAccount", options: {}, I: ActivateAccountRequest, O: CommonResult },
    { name: "ResetPassword", options: {}, I: ResetPasswordRequest, O: CommonResult },
    { name: "ReSendOTP", options: {}, I: ReSendOTPRequest, O: CommonResult },
    { name: "VerifyOTP", options: {}, I: VerifyOTPRequest, O: CommonResult },
    { name: "GetSession", options: {}, I: GetSessionRequest, O: CommonResult }
]);
