// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "user_account_command.proto" (package "UserAccount", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { StringValue } from "../../Utils/google/protobuf/wrappers";
import { Int32Value } from "../../Utils/google/protobuf/wrappers";
/**
 * @generated from protobuf message UserAccount.ChangePasswordRequest
 */
export interface ChangePasswordRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue OldPassword = 2
     */
    oldPassword?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue NewPassword = 3
     */
    newPassword?: StringValue;
}
/**
 * @generated from protobuf message UserAccount.UpdateEmailRequest
 */
export interface UpdateEmailRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Email = 2
     */
    email?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue OTP = 3
     */
    oTP?: StringValue;
}
/**
 * @generated from protobuf message UserAccount.DeleteUserAccountRequest
 */
export interface DeleteUserAccountRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
}
/**
 * @generated from protobuf message UserAccount.UpdateUserInformationRequest
 */
export interface UpdateUserInformationRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue NumCustomer = 2
     */
    numCustomer?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue FirstName = 3
     */
    firstName?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue LastName = 4
     */
    lastName?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value Gender = 5
     */
    gender?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value DateOfBirth = 6
     */
    dateOfBirth?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Img = 7
     */
    img?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue IdCard = 8
     */
    idCard?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Address = 9
     */
    address?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value WardId = 10
     */
    wardId?: Int32Value;
}
/**
 * Admin
 *
 * @generated from protobuf message UserAccount.AdminCreateUserAccountRequest
 */
export interface AdminCreateUserAccountRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue UserTel = 1
     */
    userTel?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue UserPassword = 2
     */
    userPassword?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue UserOtp = 3
     */
    userOtp?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value IsActived = 4
     */
    isActived?: Int32Value;
}
/**
 * @generated from protobuf message UserAccount.AdminUpdateUserAccountRequest
 */
export interface AdminUpdateUserAccountRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue UserTel = 2
     */
    userTel?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue UserPassword = 3
     */
    userPassword?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue UserOtp = 4
     */
    userOtp?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value IsActived = 5
     */
    isActived?: Int32Value;
}
// @generated message type with reflection information, may provide speed optimized methods
class ChangePasswordRequest$Type extends MessageType<ChangePasswordRequest> {
    constructor() {
        super("UserAccount.ChangePasswordRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value },
            { no: 2, name: "OldPassword", kind: "message", jsonName: "OldPassword", T: () => StringValue },
            { no: 3, name: "NewPassword", kind: "message", jsonName: "NewPassword", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<ChangePasswordRequest>): ChangePasswordRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ChangePasswordRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ChangePasswordRequest): ChangePasswordRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* optional google.protobuf.StringValue OldPassword */ 2:
                    message.oldPassword = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.oldPassword);
                    break;
                case /* optional google.protobuf.StringValue NewPassword */ 3:
                    message.newPassword = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.newPassword);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ChangePasswordRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue OldPassword = 2; */
        if (message.oldPassword)
            StringValue.internalBinaryWrite(message.oldPassword, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue NewPassword = 3; */
        if (message.newPassword)
            StringValue.internalBinaryWrite(message.newPassword, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserAccount.ChangePasswordRequest
 */
export const ChangePasswordRequest = new ChangePasswordRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateEmailRequest$Type extends MessageType<UpdateEmailRequest> {
    constructor() {
        super("UserAccount.UpdateEmailRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value },
            { no: 2, name: "Email", kind: "message", jsonName: "Email", T: () => StringValue },
            { no: 3, name: "OTP", kind: "message", jsonName: "OTP", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<UpdateEmailRequest>): UpdateEmailRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateEmailRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateEmailRequest): UpdateEmailRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* optional google.protobuf.StringValue Email */ 2:
                    message.email = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.email);
                    break;
                case /* optional google.protobuf.StringValue OTP */ 3:
                    message.oTP = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.oTP);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateEmailRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue Email = 2; */
        if (message.email)
            StringValue.internalBinaryWrite(message.email, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue OTP = 3; */
        if (message.oTP)
            StringValue.internalBinaryWrite(message.oTP, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserAccount.UpdateEmailRequest
 */
export const UpdateEmailRequest = new UpdateEmailRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteUserAccountRequest$Type extends MessageType<DeleteUserAccountRequest> {
    constructor() {
        super("UserAccount.DeleteUserAccountRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<DeleteUserAccountRequest>): DeleteUserAccountRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DeleteUserAccountRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteUserAccountRequest): DeleteUserAccountRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteUserAccountRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserAccount.DeleteUserAccountRequest
 */
export const DeleteUserAccountRequest = new DeleteUserAccountRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateUserInformationRequest$Type extends MessageType<UpdateUserInformationRequest> {
    constructor() {
        super("UserAccount.UpdateUserInformationRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value },
            { no: 2, name: "NumCustomer", kind: "message", jsonName: "NumCustomer", T: () => StringValue },
            { no: 3, name: "FirstName", kind: "message", jsonName: "FirstName", T: () => StringValue },
            { no: 4, name: "LastName", kind: "message", jsonName: "LastName", T: () => StringValue },
            { no: 5, name: "Gender", kind: "message", jsonName: "Gender", T: () => Int32Value },
            { no: 6, name: "DateOfBirth", kind: "message", jsonName: "DateOfBirth", T: () => Int32Value },
            { no: 7, name: "Img", kind: "message", jsonName: "Img", T: () => StringValue },
            { no: 8, name: "IdCard", kind: "message", jsonName: "IdCard", T: () => StringValue },
            { no: 9, name: "Address", kind: "message", jsonName: "Address", T: () => StringValue },
            { no: 10, name: "WardId", kind: "message", jsonName: "WardId", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<UpdateUserInformationRequest>): UpdateUserInformationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateUserInformationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateUserInformationRequest): UpdateUserInformationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* optional google.protobuf.StringValue NumCustomer */ 2:
                    message.numCustomer = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.numCustomer);
                    break;
                case /* optional google.protobuf.StringValue FirstName */ 3:
                    message.firstName = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.firstName);
                    break;
                case /* optional google.protobuf.StringValue LastName */ 4:
                    message.lastName = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.lastName);
                    break;
                case /* optional google.protobuf.Int32Value Gender */ 5:
                    message.gender = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.gender);
                    break;
                case /* optional google.protobuf.Int32Value DateOfBirth */ 6:
                    message.dateOfBirth = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.dateOfBirth);
                    break;
                case /* optional google.protobuf.StringValue Img */ 7:
                    message.img = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.img);
                    break;
                case /* optional google.protobuf.StringValue IdCard */ 8:
                    message.idCard = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.idCard);
                    break;
                case /* optional google.protobuf.StringValue Address */ 9:
                    message.address = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.address);
                    break;
                case /* optional google.protobuf.Int32Value WardId */ 10:
                    message.wardId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.wardId);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateUserInformationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue NumCustomer = 2; */
        if (message.numCustomer)
            StringValue.internalBinaryWrite(message.numCustomer, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue FirstName = 3; */
        if (message.firstName)
            StringValue.internalBinaryWrite(message.firstName, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue LastName = 4; */
        if (message.lastName)
            StringValue.internalBinaryWrite(message.lastName, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value Gender = 5; */
        if (message.gender)
            Int32Value.internalBinaryWrite(message.gender, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value DateOfBirth = 6; */
        if (message.dateOfBirth)
            Int32Value.internalBinaryWrite(message.dateOfBirth, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue Img = 7; */
        if (message.img)
            StringValue.internalBinaryWrite(message.img, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue IdCard = 8; */
        if (message.idCard)
            StringValue.internalBinaryWrite(message.idCard, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue Address = 9; */
        if (message.address)
            StringValue.internalBinaryWrite(message.address, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value WardId = 10; */
        if (message.wardId)
            Int32Value.internalBinaryWrite(message.wardId, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserAccount.UpdateUserInformationRequest
 */
export const UpdateUserInformationRequest = new UpdateUserInformationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AdminCreateUserAccountRequest$Type extends MessageType<AdminCreateUserAccountRequest> {
    constructor() {
        super("UserAccount.AdminCreateUserAccountRequest", [
            { no: 1, name: "UserTel", kind: "message", jsonName: "UserTel", T: () => StringValue },
            { no: 2, name: "UserPassword", kind: "message", jsonName: "UserPassword", T: () => StringValue },
            { no: 3, name: "UserOtp", kind: "message", jsonName: "UserOtp", T: () => StringValue },
            { no: 4, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<AdminCreateUserAccountRequest>): AdminCreateUserAccountRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AdminCreateUserAccountRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AdminCreateUserAccountRequest): AdminCreateUserAccountRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue UserTel */ 1:
                    message.userTel = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.userTel);
                    break;
                case /* optional google.protobuf.StringValue UserPassword */ 2:
                    message.userPassword = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.userPassword);
                    break;
                case /* optional google.protobuf.StringValue UserOtp */ 3:
                    message.userOtp = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.userOtp);
                    break;
                case /* optional google.protobuf.Int32Value IsActived */ 4:
                    message.isActived = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AdminCreateUserAccountRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue UserTel = 1; */
        if (message.userTel)
            StringValue.internalBinaryWrite(message.userTel, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue UserPassword = 2; */
        if (message.userPassword)
            StringValue.internalBinaryWrite(message.userPassword, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue UserOtp = 3; */
        if (message.userOtp)
            StringValue.internalBinaryWrite(message.userOtp, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value IsActived = 4; */
        if (message.isActived)
            Int32Value.internalBinaryWrite(message.isActived, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserAccount.AdminCreateUserAccountRequest
 */
export const AdminCreateUserAccountRequest = new AdminCreateUserAccountRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AdminUpdateUserAccountRequest$Type extends MessageType<AdminUpdateUserAccountRequest> {
    constructor() {
        super("UserAccount.AdminUpdateUserAccountRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value },
            { no: 2, name: "UserTel", kind: "message", jsonName: "UserTel", T: () => StringValue },
            { no: 3, name: "UserPassword", kind: "message", jsonName: "UserPassword", T: () => StringValue },
            { no: 4, name: "UserOtp", kind: "message", jsonName: "UserOtp", T: () => StringValue },
            { no: 5, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<AdminUpdateUserAccountRequest>): AdminUpdateUserAccountRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AdminUpdateUserAccountRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AdminUpdateUserAccountRequest): AdminUpdateUserAccountRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* optional google.protobuf.StringValue UserTel */ 2:
                    message.userTel = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.userTel);
                    break;
                case /* optional google.protobuf.StringValue UserPassword */ 3:
                    message.userPassword = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.userPassword);
                    break;
                case /* optional google.protobuf.StringValue UserOtp */ 4:
                    message.userOtp = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.userOtp);
                    break;
                case /* optional google.protobuf.Int32Value IsActived */ 5:
                    message.isActived = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AdminUpdateUserAccountRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue UserTel = 2; */
        if (message.userTel)
            StringValue.internalBinaryWrite(message.userTel, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue UserPassword = 3; */
        if (message.userPassword)
            StringValue.internalBinaryWrite(message.userPassword, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue UserOtp = 4; */
        if (message.userOtp)
            StringValue.internalBinaryWrite(message.userOtp, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value IsActived = 5; */
        if (message.isActived)
            Int32Value.internalBinaryWrite(message.isActived, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserAccount.AdminUpdateUserAccountRequest
 */
export const AdminUpdateUserAccountRequest = new AdminUpdateUserAccountRequest$Type();
/**
 * @generated ServiceType for protobuf service UserAccount.UserAccountCommand
 */
export const UserAccountCommand = new ServiceType("UserAccount.UserAccountCommand", [
    { name: "ChangePassword", options: {}, I: ChangePasswordRequest, O: CommonResult },
    { name: "DeleteUserAccount", options: {}, I: DeleteUserAccountRequest, O: CommonResult },
    { name: "UpdateUserInformation", options: {}, I: UpdateUserInformationRequest, O: CommonResult },
    { name: "UpdateEmail", options: {}, I: UpdateEmailRequest, O: CommonResult },
    { name: "AdminCreateUserAccount", options: {}, I: AdminCreateUserAccountRequest, O: CommonResult },
    { name: "AdminUpdateUserAccount", options: {}, I: AdminUpdateUserAccountRequest, O: CommonResult },
    { name: "AdminDeleteUserAccount", options: {}, I: DeleteUserAccountRequest, O: CommonResult }
]);
