// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "user_payment_method_command.proto" (package "UserPaymentMethod", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { UserPaymentMethodCommand } from "./user_payment_method_command";
import type { DeleteUserPaymentMethodRequest } from "./user_payment_method_command";
import type { UpdateUserPaymentMethodRequest } from "./user_payment_method_command";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { CreateUserPaymentMethodRequest } from "./user_payment_method_command";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service UserPaymentMethod.UserPaymentMethodCommand
 */
export interface IUserPaymentMethodCommandClient {
    /**
     * @generated from protobuf rpc: CreateUserPaymentMethod
     */
    createUserPaymentMethod(input: CreateUserPaymentMethodRequest, options?: RpcOptions): UnaryCall<CreateUserPaymentMethodRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: UpdateUserPaymentMethod
     */
    updateUserPaymentMethod(input: UpdateUserPaymentMethodRequest, options?: RpcOptions): UnaryCall<UpdateUserPaymentMethodRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: DeleteUserPaymentMethod
     */
    deleteUserPaymentMethod(input: DeleteUserPaymentMethodRequest, options?: RpcOptions): UnaryCall<DeleteUserPaymentMethodRequest, CommonResult>;
}
/**
 * @generated from protobuf service UserPaymentMethod.UserPaymentMethodCommand
 */
export class UserPaymentMethodCommandClient implements IUserPaymentMethodCommandClient, ServiceInfo {
    typeName = UserPaymentMethodCommand.typeName;
    methods = UserPaymentMethodCommand.methods;
    options = UserPaymentMethodCommand.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateUserPaymentMethod
     */
    createUserPaymentMethod(input: CreateUserPaymentMethodRequest, options?: RpcOptions): UnaryCall<CreateUserPaymentMethodRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateUserPaymentMethodRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateUserPaymentMethod
     */
    updateUserPaymentMethod(input: UpdateUserPaymentMethodRequest, options?: RpcOptions): UnaryCall<UpdateUserPaymentMethodRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateUserPaymentMethodRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteUserPaymentMethod
     */
    deleteUserPaymentMethod(input: DeleteUserPaymentMethodRequest, options?: RpcOptions): UnaryCall<DeleteUserPaymentMethodRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteUserPaymentMethodRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
