// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "user_payment_method_command.proto" (package "UserPaymentMethod", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Int32Value } from "../../Utils/google/protobuf/wrappers";
import { StringValue } from "../../Utils/google/protobuf/wrappers";
/**
 * Request and Response Messages
 *
 * @generated from protobuf message UserPaymentMethod.CreateUserPaymentMethodRequest
 */
export interface CreateUserPaymentMethodRequest {
    /**
     * @generated from protobuf field: google.protobuf.StringValue PayName = 1
     */
    payName?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue PayNumber = 2
     */
    payNumber?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value UserId = 3
     */
    userId?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value BankId = 4
     */
    bankId?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value IsActived = 5
     */
    isActived?: Int32Value;
}
/**
 * @generated from protobuf message UserPaymentMethod.UpdateUserPaymentMethodRequest
 */
export interface UpdateUserPaymentMethodRequest {
    /**
     * @generated from protobuf field: google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.StringValue PayName = 2
     */
    payName?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue PayNumber = 3
     */
    payNumber?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value UserId = 4
     */
    userId?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value BankId = 5
     */
    bankId?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value IsActived = 6
     */
    isActived?: Int32Value;
}
/**
 * @generated from protobuf message UserPaymentMethod.DeleteUserPaymentMethodRequest
 */
export interface DeleteUserPaymentMethodRequest {
    /**
     * @generated from protobuf field: google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateUserPaymentMethodRequest$Type extends MessageType<CreateUserPaymentMethodRequest> {
    constructor() {
        super("UserPaymentMethod.CreateUserPaymentMethodRequest", [
            { no: 1, name: "PayName", kind: "message", jsonName: "PayName", T: () => StringValue },
            { no: 2, name: "PayNumber", kind: "message", jsonName: "PayNumber", T: () => StringValue },
            { no: 3, name: "UserId", kind: "message", jsonName: "UserId", T: () => Int32Value },
            { no: 4, name: "BankId", kind: "message", jsonName: "BankId", T: () => Int32Value },
            { no: 5, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<CreateUserPaymentMethodRequest>): CreateUserPaymentMethodRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateUserPaymentMethodRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateUserPaymentMethodRequest): CreateUserPaymentMethodRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.StringValue PayName */ 1:
                    message.payName = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.payName);
                    break;
                case /* google.protobuf.StringValue PayNumber */ 2:
                    message.payNumber = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.payNumber);
                    break;
                case /* google.protobuf.Int32Value UserId */ 3:
                    message.userId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.userId);
                    break;
                case /* google.protobuf.Int32Value BankId */ 4:
                    message.bankId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.bankId);
                    break;
                case /* google.protobuf.Int32Value IsActived */ 5:
                    message.isActived = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateUserPaymentMethodRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.StringValue PayName = 1; */
        if (message.payName)
            StringValue.internalBinaryWrite(message.payName, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue PayNumber = 2; */
        if (message.payNumber)
            StringValue.internalBinaryWrite(message.payNumber, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value UserId = 3; */
        if (message.userId)
            Int32Value.internalBinaryWrite(message.userId, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value BankId = 4; */
        if (message.bankId)
            Int32Value.internalBinaryWrite(message.bankId, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value IsActived = 5; */
        if (message.isActived)
            Int32Value.internalBinaryWrite(message.isActived, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserPaymentMethod.CreateUserPaymentMethodRequest
 */
export const CreateUserPaymentMethodRequest = new CreateUserPaymentMethodRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateUserPaymentMethodRequest$Type extends MessageType<UpdateUserPaymentMethodRequest> {
    constructor() {
        super("UserPaymentMethod.UpdateUserPaymentMethodRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value },
            { no: 2, name: "PayName", kind: "message", jsonName: "PayName", T: () => StringValue },
            { no: 3, name: "PayNumber", kind: "message", jsonName: "PayNumber", T: () => StringValue },
            { no: 4, name: "UserId", kind: "message", jsonName: "UserId", T: () => Int32Value },
            { no: 5, name: "BankId", kind: "message", jsonName: "BankId", T: () => Int32Value },
            { no: 6, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<UpdateUserPaymentMethodRequest>): UpdateUserPaymentMethodRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateUserPaymentMethodRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateUserPaymentMethodRequest): UpdateUserPaymentMethodRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* google.protobuf.StringValue PayName */ 2:
                    message.payName = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.payName);
                    break;
                case /* google.protobuf.StringValue PayNumber */ 3:
                    message.payNumber = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.payNumber);
                    break;
                case /* google.protobuf.Int32Value UserId */ 4:
                    message.userId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.userId);
                    break;
                case /* google.protobuf.Int32Value BankId */ 5:
                    message.bankId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.bankId);
                    break;
                case /* google.protobuf.Int32Value IsActived */ 6:
                    message.isActived = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateUserPaymentMethodRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue PayName = 2; */
        if (message.payName)
            StringValue.internalBinaryWrite(message.payName, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue PayNumber = 3; */
        if (message.payNumber)
            StringValue.internalBinaryWrite(message.payNumber, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value UserId = 4; */
        if (message.userId)
            Int32Value.internalBinaryWrite(message.userId, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value BankId = 5; */
        if (message.bankId)
            Int32Value.internalBinaryWrite(message.bankId, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value IsActived = 6; */
        if (message.isActived)
            Int32Value.internalBinaryWrite(message.isActived, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserPaymentMethod.UpdateUserPaymentMethodRequest
 */
export const UpdateUserPaymentMethodRequest = new UpdateUserPaymentMethodRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteUserPaymentMethodRequest$Type extends MessageType<DeleteUserPaymentMethodRequest> {
    constructor() {
        super("UserPaymentMethod.DeleteUserPaymentMethodRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<DeleteUserPaymentMethodRequest>): DeleteUserPaymentMethodRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DeleteUserPaymentMethodRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteUserPaymentMethodRequest): DeleteUserPaymentMethodRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteUserPaymentMethodRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserPaymentMethod.DeleteUserPaymentMethodRequest
 */
export const DeleteUserPaymentMethodRequest = new DeleteUserPaymentMethodRequest$Type();
/**
 * @generated ServiceType for protobuf service UserPaymentMethod.UserPaymentMethodCommand
 */
export const UserPaymentMethodCommand = new ServiceType("UserPaymentMethod.UserPaymentMethodCommand", [
    { name: "CreateUserPaymentMethod", options: {}, I: CreateUserPaymentMethodRequest, O: CommonResult },
    { name: "UpdateUserPaymentMethod", options: {}, I: UpdateUserPaymentMethodRequest, O: CommonResult },
    { name: "DeleteUserPaymentMethod", options: {}, I: DeleteUserPaymentMethodRequest, O: CommonResult }
]);
