// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "partner_service_pricing_query.proto" (package "PartnerServicePricing", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PartnerServicePricingQuery } from "./partner_service_pricing_query";
import type { GetAveragePriceAppliedRequest } from "./partner_service_pricing_query";
import type { GetAllPartnerServicePricingsRequest } from "./partner_service_pricing_query";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { GetDetailPartnerServicePricingRequest } from "./partner_service_pricing_query";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service PartnerServicePricing.PartnerServicePricingQuery
 */
export interface IPartnerServicePricingQueryClient {
    /**
     * @generated from protobuf rpc: GetDetailPartnerServicePricing
     */
    getDetailPartnerServicePricing(input: GetDetailPartnerServicePricingRequest, options?: RpcOptions): UnaryCall<GetDetailPartnerServicePricingRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: GetAllPartnerServicePricings
     */
    getAllPartnerServicePricings(input: GetAllPartnerServicePricingsRequest, options?: RpcOptions): UnaryCall<GetAllPartnerServicePricingsRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: GetAveragePriceApplied
     */
    getAveragePriceApplied(input: GetAveragePriceAppliedRequest, options?: RpcOptions): UnaryCall<GetAveragePriceAppliedRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminGetDetailPartnerServicePricing
     */
    adminGetDetailPartnerServicePricing(input: GetDetailPartnerServicePricingRequest, options?: RpcOptions): UnaryCall<GetDetailPartnerServicePricingRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminGetAllPartnerServicePricings
     */
    adminGetAllPartnerServicePricings(input: GetAllPartnerServicePricingsRequest, options?: RpcOptions): UnaryCall<GetAllPartnerServicePricingsRequest, CommonResult>;
}
/**
 * @generated from protobuf service PartnerServicePricing.PartnerServicePricingQuery
 */
export class PartnerServicePricingQueryClient implements IPartnerServicePricingQueryClient, ServiceInfo {
    typeName = PartnerServicePricingQuery.typeName;
    methods = PartnerServicePricingQuery.methods;
    options = PartnerServicePricingQuery.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetDetailPartnerServicePricing
     */
    getDetailPartnerServicePricing(input: GetDetailPartnerServicePricingRequest, options?: RpcOptions): UnaryCall<GetDetailPartnerServicePricingRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDetailPartnerServicePricingRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllPartnerServicePricings
     */
    getAllPartnerServicePricings(input: GetAllPartnerServicePricingsRequest, options?: RpcOptions): UnaryCall<GetAllPartnerServicePricingsRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllPartnerServicePricingsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAveragePriceApplied
     */
    getAveragePriceApplied(input: GetAveragePriceAppliedRequest, options?: RpcOptions): UnaryCall<GetAveragePriceAppliedRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAveragePriceAppliedRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminGetDetailPartnerServicePricing
     */
    adminGetDetailPartnerServicePricing(input: GetDetailPartnerServicePricingRequest, options?: RpcOptions): UnaryCall<GetDetailPartnerServicePricingRequest, CommonResult> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDetailPartnerServicePricingRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminGetAllPartnerServicePricings
     */
    adminGetAllPartnerServicePricings(input: GetAllPartnerServicePricingsRequest, options?: RpcOptions): UnaryCall<GetAllPartnerServicePricingsRequest, CommonResult> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllPartnerServicePricingsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
