// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "partner_services_query.proto" (package "PartnerServices", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PartnerServicesQuery } from "./partner_services_query";
import type { GetDetailPartnerServicesRequest } from "./partner_services_query";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { GetAllPartnerServicesRequest } from "./partner_services_query";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service PartnerServices.PartnerServicesQuery
 */
export interface IPartnerServicesQueryClient {
    /**
     * @generated from protobuf rpc: GetAllPartnerServices
     */
    getAllPartnerServices(input: GetAllPartnerServicesRequest, options?: RpcOptions): UnaryCall<GetAllPartnerServicesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: GetDetailPartnerServices
     */
    getDetailPartnerServices(input: GetDetailPartnerServicesRequest, options?: RpcOptions): UnaryCall<GetDetailPartnerServicesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminGetAllPartnerServices
     */
    adminGetAllPartnerServices(input: GetAllPartnerServicesRequest, options?: RpcOptions): UnaryCall<GetAllPartnerServicesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminGetDetailPartnerServices
     */
    adminGetDetailPartnerServices(input: GetDetailPartnerServicesRequest, options?: RpcOptions): UnaryCall<GetDetailPartnerServicesRequest, CommonResult>;
}
/**
 * @generated from protobuf service PartnerServices.PartnerServicesQuery
 */
export class PartnerServicesQueryClient implements IPartnerServicesQueryClient, ServiceInfo {
    typeName = PartnerServicesQuery.typeName;
    methods = PartnerServicesQuery.methods;
    options = PartnerServicesQuery.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetAllPartnerServices
     */
    getAllPartnerServices(input: GetAllPartnerServicesRequest, options?: RpcOptions): UnaryCall<GetAllPartnerServicesRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllPartnerServicesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDetailPartnerServices
     */
    getDetailPartnerServices(input: GetDetailPartnerServicesRequest, options?: RpcOptions): UnaryCall<GetDetailPartnerServicesRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDetailPartnerServicesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminGetAllPartnerServices
     */
    adminGetAllPartnerServices(input: GetAllPartnerServicesRequest, options?: RpcOptions): UnaryCall<GetAllPartnerServicesRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllPartnerServicesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminGetDetailPartnerServices
     */
    adminGetDetailPartnerServices(input: GetDetailPartnerServicesRequest, options?: RpcOptions): UnaryCall<GetDetailPartnerServicesRequest, CommonResult> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDetailPartnerServicesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
