// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "partner_service_pricing_query.proto" (package "PartnerServicePricing", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { NullListInt32 } from "../../Utils/common";
import { OrderByOption } from "../../Utils/common";
import { FilterOption } from "../../Utils/common";
import { PagingOption } from "../../Utils/common";
import { SkipTakeOption } from "../../Utils/common";
import { Int32Value } from "../../Utils/google/protobuf/wrappers";
/**
 * @generated from protobuf message PartnerServicePricing.GetDetailPartnerServicePricingRequest
 */
export interface GetDetailPartnerServicePricingRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
}
/**
 * @generated from protobuf message PartnerServicePricing.GetAllPartnerServicePricingsRequest
 */
export interface GetAllPartnerServicePricingsRequest {
    /**
     * @generated from protobuf field: optional SkipTakeOption SkipTakeOption = 1
     */
    skipTakeOption?: SkipTakeOption;
    /**
     * @generated from protobuf field: optional PagingOption PagingOption = 2
     */
    pagingOption?: PagingOption;
    /**
     * @generated from protobuf field: repeated FilterOption Filter = 3
     */
    filter: FilterOption[];
    /**
     * @generated from protobuf field: repeated OrderByOption OrderBy = 4
     */
    orderBy: OrderByOption[];
    /**
     * @generated from protobuf field: optional string SearchValue = 5
     */
    searchValue?: string;
    /**
     * @generated from protobuf field: repeated string SearchFields = 6
     */
    searchFields: string[];
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value FilterPartnerId = 7
     */
    filterPartnerId?: Int32Value;
}
/**
 * @generated from protobuf message PartnerServicePricing.GetAveragePriceAppliedRequest
 */
export interface GetAveragePriceAppliedRequest {
    /**
     * @generated from protobuf field: NullListInt32 ServiceIds = 1
     */
    serviceIds?: NullListInt32;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetDetailPartnerServicePricingRequest$Type extends MessageType<GetDetailPartnerServicePricingRequest> {
    constructor() {
        super("PartnerServicePricing.GetDetailPartnerServicePricingRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<GetDetailPartnerServicePricingRequest>): GetDetailPartnerServicePricingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetDetailPartnerServicePricingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDetailPartnerServicePricingRequest): GetDetailPartnerServicePricingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDetailPartnerServicePricingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerServicePricing.GetDetailPartnerServicePricingRequest
 */
export const GetDetailPartnerServicePricingRequest = new GetDetailPartnerServicePricingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllPartnerServicePricingsRequest$Type extends MessageType<GetAllPartnerServicePricingsRequest> {
    constructor() {
        super("PartnerServicePricing.GetAllPartnerServicePricingsRequest", [
            { no: 1, name: "SkipTakeOption", kind: "message", jsonName: "SkipTakeOption", T: () => SkipTakeOption },
            { no: 2, name: "PagingOption", kind: "message", jsonName: "PagingOption", T: () => PagingOption },
            { no: 3, name: "Filter", kind: "message", jsonName: "Filter", repeat: 2 /*RepeatType.UNPACKED*/, T: () => FilterOption },
            { no: 4, name: "OrderBy", kind: "message", jsonName: "OrderBy", repeat: 2 /*RepeatType.UNPACKED*/, T: () => OrderByOption },
            { no: 5, name: "SearchValue", kind: "scalar", jsonName: "SearchValue", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "SearchFields", kind: "scalar", jsonName: "SearchFields", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "FilterPartnerId", kind: "message", jsonName: "FilterPartnerId", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<GetAllPartnerServicePricingsRequest>): GetAllPartnerServicePricingsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.filter = [];
        message.orderBy = [];
        message.searchFields = [];
        if (value !== undefined)
            reflectionMergePartial<GetAllPartnerServicePricingsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllPartnerServicePricingsRequest): GetAllPartnerServicePricingsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional SkipTakeOption SkipTakeOption */ 1:
                    message.skipTakeOption = SkipTakeOption.internalBinaryRead(reader, reader.uint32(), options, message.skipTakeOption);
                    break;
                case /* optional PagingOption PagingOption */ 2:
                    message.pagingOption = PagingOption.internalBinaryRead(reader, reader.uint32(), options, message.pagingOption);
                    break;
                case /* repeated FilterOption Filter */ 3:
                    message.filter.push(FilterOption.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated OrderByOption OrderBy */ 4:
                    message.orderBy.push(OrderByOption.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional string SearchValue */ 5:
                    message.searchValue = reader.string();
                    break;
                case /* repeated string SearchFields */ 6:
                    message.searchFields.push(reader.string());
                    break;
                case /* optional google.protobuf.Int32Value FilterPartnerId */ 7:
                    message.filterPartnerId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.filterPartnerId);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllPartnerServicePricingsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional SkipTakeOption SkipTakeOption = 1; */
        if (message.skipTakeOption)
            SkipTakeOption.internalBinaryWrite(message.skipTakeOption, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional PagingOption PagingOption = 2; */
        if (message.pagingOption)
            PagingOption.internalBinaryWrite(message.pagingOption, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated FilterOption Filter = 3; */
        for (let i = 0; i < message.filter.length; i++)
            FilterOption.internalBinaryWrite(message.filter[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* repeated OrderByOption OrderBy = 4; */
        for (let i = 0; i < message.orderBy.length; i++)
            OrderByOption.internalBinaryWrite(message.orderBy[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* optional string SearchValue = 5; */
        if (message.searchValue !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.searchValue);
        /* repeated string SearchFields = 6; */
        for (let i = 0; i < message.searchFields.length; i++)
            writer.tag(6, WireType.LengthDelimited).string(message.searchFields[i]);
        /* optional google.protobuf.Int32Value FilterPartnerId = 7; */
        if (message.filterPartnerId)
            Int32Value.internalBinaryWrite(message.filterPartnerId, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerServicePricing.GetAllPartnerServicePricingsRequest
 */
export const GetAllPartnerServicePricingsRequest = new GetAllPartnerServicePricingsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAveragePriceAppliedRequest$Type extends MessageType<GetAveragePriceAppliedRequest> {
    constructor() {
        super("PartnerServicePricing.GetAveragePriceAppliedRequest", [
            { no: 1, name: "ServiceIds", kind: "message", jsonName: "ServiceIds", T: () => NullListInt32 }
        ]);
    }
    create(value?: PartialMessage<GetAveragePriceAppliedRequest>): GetAveragePriceAppliedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetAveragePriceAppliedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAveragePriceAppliedRequest): GetAveragePriceAppliedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* NullListInt32 ServiceIds */ 1:
                    message.serviceIds = NullListInt32.internalBinaryRead(reader, reader.uint32(), options, message.serviceIds);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAveragePriceAppliedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* NullListInt32 ServiceIds = 1; */
        if (message.serviceIds)
            NullListInt32.internalBinaryWrite(message.serviceIds, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PartnerServicePricing.GetAveragePriceAppliedRequest
 */
export const GetAveragePriceAppliedRequest = new GetAveragePriceAppliedRequest$Type();
/**
 * @generated ServiceType for protobuf service PartnerServicePricing.PartnerServicePricingQuery
 */
export const PartnerServicePricingQuery = new ServiceType("PartnerServicePricing.PartnerServicePricingQuery", [
    { name: "GetDetailPartnerServicePricing", options: {}, I: GetDetailPartnerServicePricingRequest, O: CommonResult },
    { name: "GetAllPartnerServicePricings", options: {}, I: GetAllPartnerServicePricingsRequest, O: CommonResult },
    { name: "GetAveragePriceApplied", options: {}, I: GetAveragePriceAppliedRequest, O: CommonResult },
    { name: "AdminGetDetailPartnerServicePricing", options: {}, I: GetDetailPartnerServicePricingRequest, O: CommonResult },
    { name: "AdminGetAllPartnerServicePricings", options: {}, I: GetAllPartnerServicePricingsRequest, O: CommonResult }
]);
