// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "partner_doc_field_configs_query.proto" (package "PartnerDocFieldConfigs", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PartnerDocFieldConfigsQuery } from "./partner_doc_field_configs_query";
import type { GetDetailPartnerDocFieldConfigsRequest } from "./partner_doc_field_configs_query";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { GetAllPartnerDocFieldConfigsRequest } from "./partner_doc_field_configs_query";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service PartnerDocFieldConfigs.PartnerDocFieldConfigsQuery
 */
export interface IPartnerDocFieldConfigsQueryClient {
    /**
     * @generated from protobuf rpc: GetAllPartnerDocFieldConfigs
     */
    getAllPartnerDocFieldConfigs(input: GetAllPartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<GetAllPartnerDocFieldConfigsRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: GetDetailPartnerDocFieldConfigs
     */
    getDetailPartnerDocFieldConfigs(input: GetDetailPartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<GetDetailPartnerDocFieldConfigsRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminGetAllPartnerDocFieldConfigs
     */
    adminGetAllPartnerDocFieldConfigs(input: GetAllPartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<GetAllPartnerDocFieldConfigsRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminGetDetailPartnerDocFieldConfigs
     */
    adminGetDetailPartnerDocFieldConfigs(input: GetDetailPartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<GetDetailPartnerDocFieldConfigsRequest, CommonResult>;
}
/**
 * @generated from protobuf service PartnerDocFieldConfigs.PartnerDocFieldConfigsQuery
 */
export class PartnerDocFieldConfigsQueryClient implements IPartnerDocFieldConfigsQueryClient, ServiceInfo {
    typeName = PartnerDocFieldConfigsQuery.typeName;
    methods = PartnerDocFieldConfigsQuery.methods;
    options = PartnerDocFieldConfigsQuery.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetAllPartnerDocFieldConfigs
     */
    getAllPartnerDocFieldConfigs(input: GetAllPartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<GetAllPartnerDocFieldConfigsRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllPartnerDocFieldConfigsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDetailPartnerDocFieldConfigs
     */
    getDetailPartnerDocFieldConfigs(input: GetDetailPartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<GetDetailPartnerDocFieldConfigsRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDetailPartnerDocFieldConfigsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminGetAllPartnerDocFieldConfigs
     */
    adminGetAllPartnerDocFieldConfigs(input: GetAllPartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<GetAllPartnerDocFieldConfigsRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllPartnerDocFieldConfigsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminGetDetailPartnerDocFieldConfigs
     */
    adminGetDetailPartnerDocFieldConfigs(input: GetDetailPartnerDocFieldConfigsRequest, options?: RpcOptions): UnaryCall<GetDetailPartnerDocFieldConfigsRequest, CommonResult> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDetailPartnerDocFieldConfigsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
