// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "user_payment_method_query.proto" (package "UserPaymentMethod", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { UserPaymentMethodQuery } from "./user_payment_method_query";
import type { GetAllUserPaymentMethodsRequest } from "./user_payment_method_query";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { GetDetailUserPaymentMethodRequest } from "./user_payment_method_query";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service UserPaymentMethod.UserPaymentMethodQuery
 */
export interface IUserPaymentMethodQueryClient {
    /**
     * @generated from protobuf rpc: GetDetailUserPaymentMethod
     */
    getDetailUserPaymentMethod(input: GetDetailUserPaymentMethodRequest, options?: RpcOptions): UnaryCall<GetDetailUserPaymentMethodRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: GetAllUserPaymentMethods
     */
    getAllUserPaymentMethods(input: GetAllUserPaymentMethodsRequest, options?: RpcOptions): UnaryCall<GetAllUserPaymentMethodsRequest, CommonResult>;
}
/**
 * @generated from protobuf service UserPaymentMethod.UserPaymentMethodQuery
 */
export class UserPaymentMethodQueryClient implements IUserPaymentMethodQueryClient, ServiceInfo {
    typeName = UserPaymentMethodQuery.typeName;
    methods = UserPaymentMethodQuery.methods;
    options = UserPaymentMethodQuery.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetDetailUserPaymentMethod
     */
    getDetailUserPaymentMethod(input: GetDetailUserPaymentMethodRequest, options?: RpcOptions): UnaryCall<GetDetailUserPaymentMethodRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDetailUserPaymentMethodRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllUserPaymentMethods
     */
    getAllUserPaymentMethods(input: GetAllUserPaymentMethodsRequest, options?: RpcOptions): UnaryCall<GetAllUserPaymentMethodsRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllUserPaymentMethodsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
