// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "bank_catalog_query.proto" (package "BankCatalog", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { FilterOption } from "../../Utils/common";
import { Int32Value } from "../../Utils/google/protobuf/wrappers";
import { OrderByOption } from "../../Utils/common";
import { PagingOption } from "../../Utils/common";
import { SkipTakeOption } from "../../Utils/common";
/**
 * @generated from protobuf message BankCatalog.GetAllBankCatalogsRequest
 */
export interface GetAllBankCatalogsRequest {
    /**
     * @generated from protobuf field: optional SkipTakeOption SkipTakeOption = 1
     */
    skipTakeOption?: SkipTakeOption;
    /**
     * @generated from protobuf field: optional PagingOption PagingOption = 2
     */
    pagingOption?: PagingOption;
    /**
     * @generated from protobuf field: repeated OrderByOption OrderBy = 3
     */
    orderBy: OrderByOption[];
}
/**
 * @generated from protobuf message BankCatalog.GetDetailBankCatalogRequest
 */
export interface GetDetailBankCatalogRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
}
/**
 * @generated from protobuf message BankCatalog.AdminGetAllBankCatalogsRequest
 */
export interface AdminGetAllBankCatalogsRequest {
    /**
     * @generated from protobuf field: optional SkipTakeOption SkipTakeOption = 1
     */
    skipTakeOption?: SkipTakeOption;
    /**
     * @generated from protobuf field: optional PagingOption PagingOption = 2
     */
    pagingOption?: PagingOption;
    /**
     * @generated from protobuf field: repeated FilterOption Filter = 3
     */
    filter: FilterOption[];
    /**
     * @generated from protobuf field: repeated OrderByOption OrderBy = 4
     */
    orderBy: OrderByOption[];
}
// @generated message type with reflection information, may provide speed optimized methods
class GetAllBankCatalogsRequest$Type extends MessageType<GetAllBankCatalogsRequest> {
    constructor() {
        super("BankCatalog.GetAllBankCatalogsRequest", [
            { no: 1, name: "SkipTakeOption", kind: "message", jsonName: "SkipTakeOption", T: () => SkipTakeOption },
            { no: 2, name: "PagingOption", kind: "message", jsonName: "PagingOption", T: () => PagingOption },
            { no: 3, name: "OrderBy", kind: "message", jsonName: "OrderBy", repeat: 2 /*RepeatType.UNPACKED*/, T: () => OrderByOption }
        ]);
    }
    create(value?: PartialMessage<GetAllBankCatalogsRequest>): GetAllBankCatalogsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.orderBy = [];
        if (value !== undefined)
            reflectionMergePartial<GetAllBankCatalogsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllBankCatalogsRequest): GetAllBankCatalogsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional SkipTakeOption SkipTakeOption */ 1:
                    message.skipTakeOption = SkipTakeOption.internalBinaryRead(reader, reader.uint32(), options, message.skipTakeOption);
                    break;
                case /* optional PagingOption PagingOption */ 2:
                    message.pagingOption = PagingOption.internalBinaryRead(reader, reader.uint32(), options, message.pagingOption);
                    break;
                case /* repeated OrderByOption OrderBy */ 3:
                    message.orderBy.push(OrderByOption.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllBankCatalogsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional SkipTakeOption SkipTakeOption = 1; */
        if (message.skipTakeOption)
            SkipTakeOption.internalBinaryWrite(message.skipTakeOption, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional PagingOption PagingOption = 2; */
        if (message.pagingOption)
            PagingOption.internalBinaryWrite(message.pagingOption, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated OrderByOption OrderBy = 3; */
        for (let i = 0; i < message.orderBy.length; i++)
            OrderByOption.internalBinaryWrite(message.orderBy[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message BankCatalog.GetAllBankCatalogsRequest
 */
export const GetAllBankCatalogsRequest = new GetAllBankCatalogsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetDetailBankCatalogRequest$Type extends MessageType<GetDetailBankCatalogRequest> {
    constructor() {
        super("BankCatalog.GetDetailBankCatalogRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<GetDetailBankCatalogRequest>): GetDetailBankCatalogRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetDetailBankCatalogRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDetailBankCatalogRequest): GetDetailBankCatalogRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDetailBankCatalogRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message BankCatalog.GetDetailBankCatalogRequest
 */
export const GetDetailBankCatalogRequest = new GetDetailBankCatalogRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AdminGetAllBankCatalogsRequest$Type extends MessageType<AdminGetAllBankCatalogsRequest> {
    constructor() {
        super("BankCatalog.AdminGetAllBankCatalogsRequest", [
            { no: 1, name: "SkipTakeOption", kind: "message", jsonName: "SkipTakeOption", T: () => SkipTakeOption },
            { no: 2, name: "PagingOption", kind: "message", jsonName: "PagingOption", T: () => PagingOption },
            { no: 3, name: "Filter", kind: "message", jsonName: "Filter", repeat: 2 /*RepeatType.UNPACKED*/, T: () => FilterOption },
            { no: 4, name: "OrderBy", kind: "message", jsonName: "OrderBy", repeat: 2 /*RepeatType.UNPACKED*/, T: () => OrderByOption }
        ]);
    }
    create(value?: PartialMessage<AdminGetAllBankCatalogsRequest>): AdminGetAllBankCatalogsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.filter = [];
        message.orderBy = [];
        if (value !== undefined)
            reflectionMergePartial<AdminGetAllBankCatalogsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AdminGetAllBankCatalogsRequest): AdminGetAllBankCatalogsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional SkipTakeOption SkipTakeOption */ 1:
                    message.skipTakeOption = SkipTakeOption.internalBinaryRead(reader, reader.uint32(), options, message.skipTakeOption);
                    break;
                case /* optional PagingOption PagingOption */ 2:
                    message.pagingOption = PagingOption.internalBinaryRead(reader, reader.uint32(), options, message.pagingOption);
                    break;
                case /* repeated FilterOption Filter */ 3:
                    message.filter.push(FilterOption.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated OrderByOption OrderBy */ 4:
                    message.orderBy.push(OrderByOption.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AdminGetAllBankCatalogsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional SkipTakeOption SkipTakeOption = 1; */
        if (message.skipTakeOption)
            SkipTakeOption.internalBinaryWrite(message.skipTakeOption, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional PagingOption PagingOption = 2; */
        if (message.pagingOption)
            PagingOption.internalBinaryWrite(message.pagingOption, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated FilterOption Filter = 3; */
        for (let i = 0; i < message.filter.length; i++)
            FilterOption.internalBinaryWrite(message.filter[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* repeated OrderByOption OrderBy = 4; */
        for (let i = 0; i < message.orderBy.length; i++)
            OrderByOption.internalBinaryWrite(message.orderBy[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message BankCatalog.AdminGetAllBankCatalogsRequest
 */
export const AdminGetAllBankCatalogsRequest = new AdminGetAllBankCatalogsRequest$Type();
/**
 * @generated ServiceType for protobuf service BankCatalog.BankCatalogQuery
 */
export const BankCatalogQuery = new ServiceType("BankCatalog.BankCatalogQuery", [
    { name: "GetAllBankCatalogs", options: {}, I: GetAllBankCatalogsRequest, O: CommonResult },
    { name: "GetDetailBankCatalog", options: {}, I: GetDetailBankCatalogRequest, O: CommonResult },
    { name: "AdminGetAllBankCatalogs", options: {}, I: AdminGetAllBankCatalogsRequest, O: CommonResult }
]);
