// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "config_lang_query.proto" (package "ConfigLang", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ConfigLangQuery } from "./config_lang_query";
import type { GetDetailConfigLangRequest } from "./config_lang_query";
import type { AdminGetAllConfigLangsRequest } from "./config_lang_query";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { GetAllConfigLangsActivedRequest } from "./config_lang_query";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service ConfigLang.ConfigLangQuery
 */
export interface IConfigLangQueryClient {
    /**
     * @generated from protobuf rpc: GetAllConfigLangsActived
     */
    getAllConfigLangsActived(input: GetAllConfigLangsActivedRequest, options?: RpcOptions): UnaryCall<GetAllConfigLangsActivedRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminGetAllConfigLangs
     */
    adminGetAllConfigLangs(input: AdminGetAllConfigLangsRequest, options?: RpcOptions): UnaryCall<AdminGetAllConfigLangsRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: GetDetailConfigLang
     */
    getDetailConfigLang(input: GetDetailConfigLangRequest, options?: RpcOptions): UnaryCall<GetDetailConfigLangRequest, CommonResult>;
}
/**
 * @generated from protobuf service ConfigLang.ConfigLangQuery
 */
export class ConfigLangQueryClient implements IConfigLangQueryClient, ServiceInfo {
    typeName = ConfigLangQuery.typeName;
    methods = ConfigLangQuery.methods;
    options = ConfigLangQuery.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetAllConfigLangsActived
     */
    getAllConfigLangsActived(input: GetAllConfigLangsActivedRequest, options?: RpcOptions): UnaryCall<GetAllConfigLangsActivedRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllConfigLangsActivedRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminGetAllConfigLangs
     */
    adminGetAllConfigLangs(input: AdminGetAllConfigLangsRequest, options?: RpcOptions): UnaryCall<AdminGetAllConfigLangsRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AdminGetAllConfigLangsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDetailConfigLang
     */
    getDetailConfigLang(input: GetDetailConfigLangRequest, options?: RpcOptions): UnaryCall<GetDetailConfigLangRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDetailConfigLangRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
