// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "config_lang_query.proto" (package "ConfigLang", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { StringValue } from "../../Utils/google/protobuf/wrappers";
/**
 * @generated from protobuf message ConfigLang.GetDetailConfigLangRequest
 */
export interface GetDetailConfigLangRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
}
/**
 * @generated from protobuf message ConfigLang.GetAllConfigLangsActivedRequest
 */
export interface GetAllConfigLangsActivedRequest {
}
/**
 * optional bool IsActived = 1;
 *
 * @generated from protobuf message ConfigLang.AdminGetAllConfigLangsRequest
 */
export interface AdminGetAllConfigLangsRequest {
}
// @generated message type with reflection information, may provide speed optimized methods
class GetDetailConfigLangRequest$Type extends MessageType<GetDetailConfigLangRequest> {
    constructor() {
        super("ConfigLang.GetDetailConfigLangRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<GetDetailConfigLangRequest>): GetDetailConfigLangRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetDetailConfigLangRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDetailConfigLangRequest): GetDetailConfigLangRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDetailConfigLangRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ConfigLang.GetDetailConfigLangRequest
 */
export const GetDetailConfigLangRequest = new GetDetailConfigLangRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllConfigLangsActivedRequest$Type extends MessageType<GetAllConfigLangsActivedRequest> {
    constructor() {
        super("ConfigLang.GetAllConfigLangsActivedRequest", []);
    }
    create(value?: PartialMessage<GetAllConfigLangsActivedRequest>): GetAllConfigLangsActivedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetAllConfigLangsActivedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllConfigLangsActivedRequest): GetAllConfigLangsActivedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllConfigLangsActivedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ConfigLang.GetAllConfigLangsActivedRequest
 */
export const GetAllConfigLangsActivedRequest = new GetAllConfigLangsActivedRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AdminGetAllConfigLangsRequest$Type extends MessageType<AdminGetAllConfigLangsRequest> {
    constructor() {
        super("ConfigLang.AdminGetAllConfigLangsRequest", []);
    }
    create(value?: PartialMessage<AdminGetAllConfigLangsRequest>): AdminGetAllConfigLangsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AdminGetAllConfigLangsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AdminGetAllConfigLangsRequest): AdminGetAllConfigLangsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AdminGetAllConfigLangsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ConfigLang.AdminGetAllConfigLangsRequest
 */
export const AdminGetAllConfigLangsRequest = new AdminGetAllConfigLangsRequest$Type();
/**
 * @generated ServiceType for protobuf service ConfigLang.ConfigLangQuery
 */
export const ConfigLangQuery = new ServiceType("ConfigLang.ConfigLangQuery", [
    { name: "GetAllConfigLangsActived", options: {}, I: GetAllConfigLangsActivedRequest, O: CommonResult },
    { name: "AdminGetAllConfigLangs", options: {}, I: AdminGetAllConfigLangsRequest, O: CommonResult },
    { name: "GetDetailConfigLang", options: {}, I: GetDetailConfigLangRequest, O: CommonResult }
]);
