// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "helpdesk_catalog_query.proto" (package "HelpdeskCatalog", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Int32Value } from "../../Utils/google/protobuf/wrappers";
/**
 * @generated from protobuf message HelpdeskCatalog.GetDetailHelpdeskCatalogRequest
 */
export interface GetDetailHelpdeskCatalogRequest {
    /**
     * @generated from protobuf field: google.protobuf.Int32Value Id = 1
     */
    id?: Int32Value;
}
/**
 * @generated from protobuf message HelpdeskCatalog.GetAllHelpdeskCatalogsActivedRequest
 */
export interface GetAllHelpdeskCatalogsActivedRequest {
}
/**
 * @generated from protobuf message HelpdeskCatalog.AdminGetAllHelpdeskCatalogsRequest
 */
export interface AdminGetAllHelpdeskCatalogsRequest {
}
// @generated message type with reflection information, may provide speed optimized methods
class GetDetailHelpdeskCatalogRequest$Type extends MessageType<GetDetailHelpdeskCatalogRequest> {
    constructor() {
        super("HelpdeskCatalog.GetDetailHelpdeskCatalogRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<GetDetailHelpdeskCatalogRequest>): GetDetailHelpdeskCatalogRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetDetailHelpdeskCatalogRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDetailHelpdeskCatalogRequest): GetDetailHelpdeskCatalogRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Int32Value Id */ 1:
                    message.id = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDetailHelpdeskCatalogRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Int32Value Id = 1; */
        if (message.id)
            Int32Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message HelpdeskCatalog.GetDetailHelpdeskCatalogRequest
 */
export const GetDetailHelpdeskCatalogRequest = new GetDetailHelpdeskCatalogRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllHelpdeskCatalogsActivedRequest$Type extends MessageType<GetAllHelpdeskCatalogsActivedRequest> {
    constructor() {
        super("HelpdeskCatalog.GetAllHelpdeskCatalogsActivedRequest", []);
    }
    create(value?: PartialMessage<GetAllHelpdeskCatalogsActivedRequest>): GetAllHelpdeskCatalogsActivedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetAllHelpdeskCatalogsActivedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllHelpdeskCatalogsActivedRequest): GetAllHelpdeskCatalogsActivedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllHelpdeskCatalogsActivedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message HelpdeskCatalog.GetAllHelpdeskCatalogsActivedRequest
 */
export const GetAllHelpdeskCatalogsActivedRequest = new GetAllHelpdeskCatalogsActivedRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AdminGetAllHelpdeskCatalogsRequest$Type extends MessageType<AdminGetAllHelpdeskCatalogsRequest> {
    constructor() {
        super("HelpdeskCatalog.AdminGetAllHelpdeskCatalogsRequest", []);
    }
    create(value?: PartialMessage<AdminGetAllHelpdeskCatalogsRequest>): AdminGetAllHelpdeskCatalogsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AdminGetAllHelpdeskCatalogsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AdminGetAllHelpdeskCatalogsRequest): AdminGetAllHelpdeskCatalogsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AdminGetAllHelpdeskCatalogsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message HelpdeskCatalog.AdminGetAllHelpdeskCatalogsRequest
 */
export const AdminGetAllHelpdeskCatalogsRequest = new AdminGetAllHelpdeskCatalogsRequest$Type();
/**
 * @generated ServiceType for protobuf service HelpdeskCatalog.HelpdeskCatalogQuery
 */
export const HelpdeskCatalogQuery = new ServiceType("HelpdeskCatalog.HelpdeskCatalogQuery", [
    { name: "GetAllHelpdeskCatalogsActived", options: {}, I: GetAllHelpdeskCatalogsActivedRequest, O: CommonResult },
    { name: "AdminGetAllHelpdeskCatalogs", options: {}, I: AdminGetAllHelpdeskCatalogsRequest, O: CommonResult },
    { name: "GetDetailHelpdeskCatalog", options: {}, I: GetDetailHelpdeskCatalogRequest, O: CommonResult }
]);
