// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "helpdesk_content_query.proto" (package "HelpdeskContent", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { HelpdeskContentQuery } from "./helpdesk_content_query";
import type { GetDetailHelpdeskContentRequest } from "./helpdesk_content_query";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { GetAllHelpdeskContentsRequest } from "./helpdesk_content_query";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service HelpdeskContent.HelpdeskContentQuery
 */
export interface IHelpdeskContentQueryClient {
    /**
     * @generated from protobuf rpc: GetAllHelpdeskContents
     */
    getAllHelpdeskContents(input: GetAllHelpdeskContentsRequest, options?: RpcOptions): UnaryCall<GetAllHelpdeskContentsRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: GetDetailHelpdeskContent
     */
    getDetailHelpdeskContent(input: GetDetailHelpdeskContentRequest, options?: RpcOptions): UnaryCall<GetDetailHelpdeskContentRequest, CommonResult>;
}
/**
 * @generated from protobuf service HelpdeskContent.HelpdeskContentQuery
 */
export class HelpdeskContentQueryClient implements IHelpdeskContentQueryClient, ServiceInfo {
    typeName = HelpdeskContentQuery.typeName;
    methods = HelpdeskContentQuery.methods;
    options = HelpdeskContentQuery.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetAllHelpdeskContents
     */
    getAllHelpdeskContents(input: GetAllHelpdeskContentsRequest, options?: RpcOptions): UnaryCall<GetAllHelpdeskContentsRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllHelpdeskContentsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDetailHelpdeskContent
     */
    getDetailHelpdeskContent(input: GetDetailHelpdeskContentRequest, options?: RpcOptions): UnaryCall<GetDetailHelpdeskContentRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDetailHelpdeskContentRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
