// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "share_social_network.proto" (package "ShareSocialNetwork", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { StringValue } from "../../Utils/google/protobuf/wrappers";
/**
 * @generated from protobuf message ShareSocialNetwork.GetDetailShareSocialNetworkRequest
 */
export interface GetDetailShareSocialNetworkRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
}
/**
 * @generated from protobuf message ShareSocialNetwork.GetAllShareSocialNetworksRequest
 */
export interface GetAllShareSocialNetworksRequest {
}
// @generated message type with reflection information, may provide speed optimized methods
class GetDetailShareSocialNetworkRequest$Type extends MessageType<GetDetailShareSocialNetworkRequest> {
    constructor() {
        super("ShareSocialNetwork.GetDetailShareSocialNetworkRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<GetDetailShareSocialNetworkRequest>): GetDetailShareSocialNetworkRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetDetailShareSocialNetworkRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDetailShareSocialNetworkRequest): GetDetailShareSocialNetworkRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDetailShareSocialNetworkRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ShareSocialNetwork.GetDetailShareSocialNetworkRequest
 */
export const GetDetailShareSocialNetworkRequest = new GetDetailShareSocialNetworkRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllShareSocialNetworksRequest$Type extends MessageType<GetAllShareSocialNetworksRequest> {
    constructor() {
        super("ShareSocialNetwork.GetAllShareSocialNetworksRequest", []);
    }
    create(value?: PartialMessage<GetAllShareSocialNetworksRequest>): GetAllShareSocialNetworksRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetAllShareSocialNetworksRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllShareSocialNetworksRequest): GetAllShareSocialNetworksRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllShareSocialNetworksRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ShareSocialNetwork.GetAllShareSocialNetworksRequest
 */
export const GetAllShareSocialNetworksRequest = new GetAllShareSocialNetworksRequest$Type();
/**
 * @generated ServiceType for protobuf service ShareSocialNetwork.ShareSocialNetworkQuery
 */
export const ShareSocialNetworkQuery = new ServiceType("ShareSocialNetwork.ShareSocialNetworkQuery", [
    { name: "GetDetailShareSocialNetwork", options: {}, I: GetDetailShareSocialNetworkRequest, O: CommonResult },
    { name: "GetAllShareSocialNetworks", options: {}, I: GetAllShareSocialNetworksRequest, O: CommonResult }
]);
