// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "website_currency_query.proto" (package "WebsiteWebsiteCurrency", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { BoolValue } from "../../Utils/google/protobuf/wrappers";
import { StringValue } from "../../Utils/google/protobuf/wrappers";
/**
 * @generated from protobuf message WebsiteWebsiteCurrency.GetDetailWebsiteCurrencyRequest
 */
export interface GetDetailWebsiteCurrencyRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
}
/**
 * @generated from protobuf message WebsiteWebsiteCurrency.GetAllWebsiteCurrenciesActivedRequest
 */
export interface GetAllWebsiteCurrenciesActivedRequest {
}
/**
 * @generated from protobuf message WebsiteWebsiteCurrency.AdminGetAllWebsiteCurrenciesRequest
 */
export interface AdminGetAllWebsiteCurrenciesRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.BoolValue IsActived = 1
     */
    isActived?: BoolValue;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetDetailWebsiteCurrencyRequest$Type extends MessageType<GetDetailWebsiteCurrencyRequest> {
    constructor() {
        super("WebsiteWebsiteCurrency.GetDetailWebsiteCurrencyRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<GetDetailWebsiteCurrencyRequest>): GetDetailWebsiteCurrencyRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetDetailWebsiteCurrencyRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDetailWebsiteCurrencyRequest): GetDetailWebsiteCurrencyRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDetailWebsiteCurrencyRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message WebsiteWebsiteCurrency.GetDetailWebsiteCurrencyRequest
 */
export const GetDetailWebsiteCurrencyRequest = new GetDetailWebsiteCurrencyRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllWebsiteCurrenciesActivedRequest$Type extends MessageType<GetAllWebsiteCurrenciesActivedRequest> {
    constructor() {
        super("WebsiteWebsiteCurrency.GetAllWebsiteCurrenciesActivedRequest", []);
    }
    create(value?: PartialMessage<GetAllWebsiteCurrenciesActivedRequest>): GetAllWebsiteCurrenciesActivedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetAllWebsiteCurrenciesActivedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllWebsiteCurrenciesActivedRequest): GetAllWebsiteCurrenciesActivedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllWebsiteCurrenciesActivedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message WebsiteWebsiteCurrency.GetAllWebsiteCurrenciesActivedRequest
 */
export const GetAllWebsiteCurrenciesActivedRequest = new GetAllWebsiteCurrenciesActivedRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AdminGetAllWebsiteCurrenciesRequest$Type extends MessageType<AdminGetAllWebsiteCurrenciesRequest> {
    constructor() {
        super("WebsiteWebsiteCurrency.AdminGetAllWebsiteCurrenciesRequest", [
            { no: 1, name: "IsActived", kind: "message", jsonName: "IsActived", T: () => BoolValue }
        ]);
    }
    create(value?: PartialMessage<AdminGetAllWebsiteCurrenciesRequest>): AdminGetAllWebsiteCurrenciesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AdminGetAllWebsiteCurrenciesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AdminGetAllWebsiteCurrenciesRequest): AdminGetAllWebsiteCurrenciesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.BoolValue IsActived */ 1:
                    message.isActived = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.isActived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AdminGetAllWebsiteCurrenciesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.BoolValue IsActived = 1; */
        if (message.isActived)
            BoolValue.internalBinaryWrite(message.isActived, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message WebsiteWebsiteCurrency.AdminGetAllWebsiteCurrenciesRequest
 */
export const AdminGetAllWebsiteCurrenciesRequest = new AdminGetAllWebsiteCurrenciesRequest$Type();
/**
 * @generated ServiceType for protobuf service WebsiteWebsiteCurrency.WebsiteWebsiteCurrencyQuery
 */
export const WebsiteWebsiteCurrencyQuery = new ServiceType("WebsiteWebsiteCurrency.WebsiteWebsiteCurrencyQuery", [
    { name: "GetAllWebsiteCurrenciesActived", options: {}, I: GetAllWebsiteCurrenciesActivedRequest, O: CommonResult },
    { name: "AdminGetAllWebsiteCurrencies", options: {}, I: AdminGetAllWebsiteCurrenciesRequest, O: CommonResult },
    { name: "GetDetailWebsiteCurrency", options: {}, I: GetDetailWebsiteCurrencyRequest, O: CommonResult }
]);
