// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "website_currency_query.proto" (package "WebsiteWebsiteCurrency", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { WebsiteWebsiteCurrencyQuery } from "./website_currency_query";
import type { GetDetailWebsiteCurrencyRequest } from "./website_currency_query";
import type { AdminGetAllWebsiteCurrenciesRequest } from "./website_currency_query";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { GetAllWebsiteCurrenciesActivedRequest } from "./website_currency_query";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service WebsiteWebsiteCurrency.WebsiteWebsiteCurrencyQuery
 */
export interface IWebsiteWebsiteCurrencyQueryClient {
    /**
     * @generated from protobuf rpc: GetAllWebsiteCurrenciesActived
     */
    getAllWebsiteCurrenciesActived(input: GetAllWebsiteCurrenciesActivedRequest, options?: RpcOptions): UnaryCall<GetAllWebsiteCurrenciesActivedRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminGetAllWebsiteCurrencies
     */
    adminGetAllWebsiteCurrencies(input: AdminGetAllWebsiteCurrenciesRequest, options?: RpcOptions): UnaryCall<AdminGetAllWebsiteCurrenciesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: GetDetailWebsiteCurrency
     */
    getDetailWebsiteCurrency(input: GetDetailWebsiteCurrencyRequest, options?: RpcOptions): UnaryCall<GetDetailWebsiteCurrencyRequest, CommonResult>;
}
/**
 * @generated from protobuf service WebsiteWebsiteCurrency.WebsiteWebsiteCurrencyQuery
 */
export class WebsiteWebsiteCurrencyQueryClient implements IWebsiteWebsiteCurrencyQueryClient, ServiceInfo {
    typeName = WebsiteWebsiteCurrencyQuery.typeName;
    methods = WebsiteWebsiteCurrencyQuery.methods;
    options = WebsiteWebsiteCurrencyQuery.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetAllWebsiteCurrenciesActived
     */
    getAllWebsiteCurrenciesActived(input: GetAllWebsiteCurrenciesActivedRequest, options?: RpcOptions): UnaryCall<GetAllWebsiteCurrenciesActivedRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllWebsiteCurrenciesActivedRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminGetAllWebsiteCurrencies
     */
    adminGetAllWebsiteCurrencies(input: AdminGetAllWebsiteCurrenciesRequest, options?: RpcOptions): UnaryCall<AdminGetAllWebsiteCurrenciesRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AdminGetAllWebsiteCurrenciesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDetailWebsiteCurrency
     */
    getDetailWebsiteCurrency(input: GetDetailWebsiteCurrencyRequest, options?: RpcOptions): UnaryCall<GetDetailWebsiteCurrencyRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDetailWebsiteCurrencyRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
