// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "website_file_setting_query.proto" (package "WebsiteFileSetting", syntax proto3)
// tslint:disable
import { CommonResult } from "../../Utils/result";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { StringValue } from "../../Utils/google/protobuf/wrappers";
/**
 * @generated from protobuf message WebsiteFileSetting.GetDetailWebsiteFileSettingRequest
 */
export interface GetDetailWebsiteFileSettingRequest {
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue Id = 1
     */
    id?: StringValue;
}
/**
 * @generated from protobuf message WebsiteFileSetting.GetAllWebsiteFileSettingsRequest
 */
export interface GetAllWebsiteFileSettingsRequest {
}
// @generated message type with reflection information, may provide speed optimized methods
class GetDetailWebsiteFileSettingRequest$Type extends MessageType<GetDetailWebsiteFileSettingRequest> {
    constructor() {
        super("WebsiteFileSetting.GetDetailWebsiteFileSettingRequest", [
            { no: 1, name: "Id", kind: "message", jsonName: "Id", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<GetDetailWebsiteFileSettingRequest>): GetDetailWebsiteFileSettingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetDetailWebsiteFileSettingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDetailWebsiteFileSettingRequest): GetDetailWebsiteFileSettingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.StringValue Id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDetailWebsiteFileSettingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.StringValue Id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message WebsiteFileSetting.GetDetailWebsiteFileSettingRequest
 */
export const GetDetailWebsiteFileSettingRequest = new GetDetailWebsiteFileSettingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllWebsiteFileSettingsRequest$Type extends MessageType<GetAllWebsiteFileSettingsRequest> {
    constructor() {
        super("WebsiteFileSetting.GetAllWebsiteFileSettingsRequest", []);
    }
    create(value?: PartialMessage<GetAllWebsiteFileSettingsRequest>): GetAllWebsiteFileSettingsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetAllWebsiteFileSettingsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllWebsiteFileSettingsRequest): GetAllWebsiteFileSettingsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllWebsiteFileSettingsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message WebsiteFileSetting.GetAllWebsiteFileSettingsRequest
 */
export const GetAllWebsiteFileSettingsRequest = new GetAllWebsiteFileSettingsRequest$Type();
/**
 * @generated ServiceType for protobuf service WebsiteFileSetting.WebsiteFileSettingQuery
 */
export const WebsiteFileSettingQuery = new ServiceType("WebsiteFileSetting.WebsiteFileSettingQuery", [
    { name: "GetDetailWebsiteFileSetting", options: {}, I: GetDetailWebsiteFileSettingRequest, O: CommonResult },
    { name: "GetAllWebsiteFileSettings", options: {}, I: GetAllWebsiteFileSettingsRequest, O: CommonResult }
]);
