// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "website_localization_query.proto" (package "WebsiteLocalization", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { WebsiteLocalizationQuery } from "./website_localization_query";
import type { GetDetailWebsiteLocalizationRequest } from "./website_localization_query";
import type { AdminGetAllWebsiteLocalizationsRequest } from "./website_localization_query";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { GetAllWebsiteLocalizationsAcitvedRequest } from "./website_localization_query";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service WebsiteLocalization.WebsiteLocalizationQuery
 */
export interface IWebsiteLocalizationQueryClient {
    /**
     * @generated from protobuf rpc: GetAllWebsiteLocalizationsAcitved
     */
    getAllWebsiteLocalizationsAcitved(input: GetAllWebsiteLocalizationsAcitvedRequest, options?: RpcOptions): UnaryCall<GetAllWebsiteLocalizationsAcitvedRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminGetAllWebsiteLocalizations
     */
    adminGetAllWebsiteLocalizations(input: AdminGetAllWebsiteLocalizationsRequest, options?: RpcOptions): UnaryCall<AdminGetAllWebsiteLocalizationsRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: GetDetailWebsiteLocalization
     */
    getDetailWebsiteLocalization(input: GetDetailWebsiteLocalizationRequest, options?: RpcOptions): UnaryCall<GetDetailWebsiteLocalizationRequest, CommonResult>;
}
/**
 * @generated from protobuf service WebsiteLocalization.WebsiteLocalizationQuery
 */
export class WebsiteLocalizationQueryClient implements IWebsiteLocalizationQueryClient, ServiceInfo {
    typeName = WebsiteLocalizationQuery.typeName;
    methods = WebsiteLocalizationQuery.methods;
    options = WebsiteLocalizationQuery.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetAllWebsiteLocalizationsAcitved
     */
    getAllWebsiteLocalizationsAcitved(input: GetAllWebsiteLocalizationsAcitvedRequest, options?: RpcOptions): UnaryCall<GetAllWebsiteLocalizationsAcitvedRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllWebsiteLocalizationsAcitvedRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminGetAllWebsiteLocalizations
     */
    adminGetAllWebsiteLocalizations(input: AdminGetAllWebsiteLocalizationsRequest, options?: RpcOptions): UnaryCall<AdminGetAllWebsiteLocalizationsRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AdminGetAllWebsiteLocalizationsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDetailWebsiteLocalization
     */
    getDetailWebsiteLocalization(input: GetDetailWebsiteLocalizationRequest, options?: RpcOptions): UnaryCall<GetDetailWebsiteLocalizationRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDetailWebsiteLocalizationRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
