// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "booking_catalog_service_command.proto" (package "BookingCatalogService", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { BookingCatalogServiceCommand } from "./booking_catalog_service_command";
import type { DeleteBookingCatalogServiceRequest } from "./booking_catalog_service_command";
import type { UpdateBookingCatalogServiceRequest } from "./booking_catalog_service_command";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../Utils/result";
import type { CreateBookingCatalogServiceRequest } from "./booking_catalog_service_command";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service BookingCatalogService.BookingCatalogServiceCommand
 */
export interface IBookingCatalogServiceCommandClient {
    /**
     * @generated from protobuf rpc: CreateBookingCatalogService
     */
    createBookingCatalogService(input: CreateBookingCatalogServiceRequest, options?: RpcOptions): UnaryCall<CreateBookingCatalogServiceRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: UpdateBookingCatalogService
     */
    updateBookingCatalogService(input: UpdateBookingCatalogServiceRequest, options?: RpcOptions): UnaryCall<UpdateBookingCatalogServiceRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: DeleteBookingCatalogService
     */
    deleteBookingCatalogService(input: DeleteBookingCatalogServiceRequest, options?: RpcOptions): UnaryCall<DeleteBookingCatalogServiceRequest, CommonResult>;
}
/**
 * @generated from protobuf service BookingCatalogService.BookingCatalogServiceCommand
 */
export class BookingCatalogServiceCommandClient implements IBookingCatalogServiceCommandClient, ServiceInfo {
    typeName = BookingCatalogServiceCommand.typeName;
    methods = BookingCatalogServiceCommand.methods;
    options = BookingCatalogServiceCommand.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateBookingCatalogService
     */
    createBookingCatalogService(input: CreateBookingCatalogServiceRequest, options?: RpcOptions): UnaryCall<CreateBookingCatalogServiceRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateBookingCatalogServiceRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateBookingCatalogService
     */
    updateBookingCatalogService(input: UpdateBookingCatalogServiceRequest, options?: RpcOptions): UnaryCall<UpdateBookingCatalogServiceRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateBookingCatalogServiceRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteBookingCatalogService
     */
    deleteBookingCatalogService(input: DeleteBookingCatalogServiceRequest, options?: RpcOptions): UnaryCall<DeleteBookingCatalogServiceRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteBookingCatalogServiceRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
